### ISSUE TITLE
Filtros de Blog, Notícias e Estudos não funcionam

### ISSUE THREAD

**Issue by mpinho** [DataViva/dataviva-site#1049]
Os filtros das páginas Blog, Notícias e Estudos não estão funcionando. Quando selecionado um assunto, o nome do filtro deve aparecer em negrito.

![image](https://cloud.githubusercontent.com/assets/15732270/15119084/7e868088-15e5-11e6-94ee-970efa2e4719.png)

**Comment by eltonfreitas** [comment]
Continua sem funcionar corretamente, quando clico no filtro ele muda a linguagem do site.

**Comment by AnaCarolinaFDias** [comment]
@eltonfreitas aqui ta funcionando norma, e ele não mudou a linguagem do site, a unica coisa que nao mostra e em qual filtro você clicou.
