### ISSUE TITLE
Ajuda - As fontes de dados estão incompletas

### ISSUE THREAD

**Issue by mpinho** [DataViva/dataviva-site#1052]
O texto de resposta para a pergunta 'Qual a fonte dos dados?' está incompleto, falta citar os dados de Educação (Censo Escolar e do Ensino Superior).

![image](https://cloud.githubusercontent.com/assets/15732270/15119787/f8ae5856-15e8-11e6-95ca-113d529bb1f5.png)

**Comment by AnaCarolinaFDias** [comment]
@mpinho pode ver com o Elton e mandar como vai ficar o texto acrescentando os dados de Educacao?

**Comment by AnaCarolinaFDias** [comment]
@eltonfreitas  como vai ficar o texto?

**Comment by eltonfreitas** [comment]
As bases de dados foram disponibilizadas pelos ministérios do Trabalho e Previdência Social (MTPS) e do Desenvolvimento, Indústria e Comércio Exterior (MDIC). O DataViva apresenta dados relativos à exportação de 1.256 produtos da Secretaria de Comércio Exterior (SECEX/MDIC) e as 865 ocupações em 427 atividades econômicas da Relação Anual de Informações Sociais (RAIS/MTPS), matrículas de 236 Cursos Técnicos e de 255 Nível Superior do INEP/MEC.

**Comment by AnaCarolinaFDias** [comment]
@eltonfreitas Os meninos foram atualizar e disseram que nao tem essa tradução para o Ingles , poderia disponibilizar Elton?

**Comment by eltonfreitas** [comment]
Ver a tradução com o @lucasdiasas, pf!!

**Comment by AnaCarolinaFDias** [comment]
@lucasdiasas Mandei mas ele ainda nao respondeu , vou esperar mais um pouco entao.

**Comment by AnaCarolinaFDias** [comment]
The database was provided by Ministério do Trabalho e Previdência Social (MTPS) – the Brazilian Ministry of Labor and Social Security – and Ministério do Desenvolvimento, Indústria e Comércio Exterior (MDIC) – the Brazilian Ministry of Development, Industry and Foreign Trade. DataViva presents data related to the exports of 1,256 products of the Brazilian Secretariat of Foreign Trade – Secretaria de Comércio Exterior (SECEX/MDIC) – 865 occupations in 427 economic activities of the Annual List of Social Information – RAIS/MTPS – and enrollments of 236 Technical Courses and 255 Higher Education Courses of INEP/MEC.
