### ISSUE TITLE
No menu Ajuda, os textos de Classificações por categoria não estão inseridos.

### ISSUE THREAD

**Issue by mpinho** [DataViva/dataviva-site#1054]
A seção Classificações por categoria não apresenta os textos corretos.

![image](https://cloud.githubusercontent.com/assets/15732270/15120019/f9a3a1f2-15e9-11e6-808c-07c658f8ff64.png)

**Comment by AnaCarolinaFDias** [comment]
@mpinho Isso ainda vai ser modificado , na verdade essa seção e uma tabela. 

![image](https://cloud.githubusercontent.com/assets/15165646/15120142/bacba24e-15ea-11e6-86e0-b7080b41eab4.png)

**Comment by AnaCarolinaFDias** [comment]
@mpinho Ja tem uma issue Aberta sobre isso, vou fechar essa ta bom?
