### ISSUE TITLE
Tabelas de Conversão e Acesso ao Código estão em branco

### ISSUE THREAD

**Issue by mpinho** [DataViva/dataviva-site#1055]
As seções Tabelas de Conversão e Acesso ao Código, do menu Ajuda, estão em branco:

![image](https://cloud.githubusercontent.com/assets/15732270/15120163/cf097bb4-15ea-11e6-881b-7a6074e86090.png)

**Comment by AnaCarolinaFDias** [comment]
@mpinho Os meninos ainda nao terminaram o Help, temos uma issue aberta para cada seção do Help ainda, vou fechar essa aqui ta bom?
