### ISSUE TITLE
Apresentar apenas os dados de exportação de 2014

### ISSUE THREAD

**Issue by mpinho** [DataViva/dataviva-site#1059]
O município de Sabinópolis - MG apresenta dados de importação e exportação do ano de 2003. O último que este município realizou operações de comércio exterior foi em 2005. Neste caso, como não houve operações em 2014, a aba Comércio Internacional não deve ser apresentada. 

![image](https://cloud.githubusercontent.com/assets/15732270/15145733/bcfff72e-168d-11e6-9bac-5b2bd6d8fde2.png)

**Comment by litodaldegan** [comment]
Voce nao sabe de nada!
