### ISSUE TITLE
Localidade - Aba Educação apresenta dados de 2012 e visualizações de 2014

### ISSUE THREAD

**Issue by mpinho** [DataViva/dataviva-site#1060]
A aba Educação, em Localidade, apresenta dados de 2012 e visualizações de 2014, para o município de Sabinópolis - MG.

![image](https://cloud.githubusercontent.com/assets/15732270/15145883/77121ebc-168e-11e6-8dbc-e70140d8c326.png)

**Comment by lauradebella** [comment]
Este nāo é um erro de dado - no caso, a aba educaçāo nāo deveria ser exibida. Este tipo de bug será resolvido na nova fase.

**Comment by lauradebella** [comment]
Neste caso, como a aba educaçāo contém dados da base de universidade e de cursos básicos, entramos em um acordo de exibir o ano mais recente comum aos dois. Está vindo da base de universidade, que nāo tem dados de 2013, entāo o primeiro ano disponível seria 2012.
