### ISSUE TITLE
RAIS data download not well formated

### ISSUE THREAD

**Issue by cesifoti** [DataViva/dataviva-site#1064]
Hi,

When downloading the .csv data from the data section of DataViva, I find the latter columns are ill formatted.

http://imgur.com/yBKonXG

Thanks!

C

**Comment by eltonfreitas** [comment]
Hi @cesifoti,

This probably happened due to the type of delimiters that the data contains. Try using **comma** and for text qualifier try using **"**.

![image](https://cloud.githubusercontent.com/assets/6808970/15150982/bf32da76-16a5-11e6-8b40-b46c5d618a97.png)

**Comment by cesifoti** [comment]
Hi Elton,

If I open the file in sublime, as plain text, I still get curly braces {
and colons :

It is not a problem of how I am opening the file in excel. The problem is
in the file (maybe some Json got poorly parsed into the table).

[image: Inline image 1]

*__________________**________*
César A. Hidalgo | @cesifoti <http://twitter.com/cesifoti>

Associate Professor, The MIT Media Lab,
Massachusetts Institute of Technology (MIT)
http://www.chidalgo.com | http://macro.media.mit.edu
<http://macroconnections.media.mit.edu>

Do you know Why Information Grows
<http://www.amazon.com/Why-Information-Grows-Evolution-Economies/dp/0465048994>
?

**Comment by FredericoVieira** [comment]
Hi @cesifoti, the column 'hist' is well formated. It contains a json data which is used to build a histogram.
