### ISSUE TITLE
Cruzamento Minério de Ferro em São Paulo - SP

### ISSUE THREAD

**Issue by AnaCarolinaFDias** [DataViva/dataviva-site#1074]
Antes da atualização dos dados o cruzamento entre Minério de Ferro e a localidade de São Paulo retornava alguns valores, juntamente com alguns NAN. 

![image](https://cloud.githubusercontent.com/assets/15165646/15223310/2bad87b4-184a-11e6-9958-9ea8685aa42f.png)

![image](https://cloud.githubusercontent.com/assets/15165646/15223315/36d1c79a-184a-11e6-896e-ee235a1ec7ed.png)

Quando eu tento fazer o mesmo cruzamento agora retorna o erro 404. Era pra isso acontecer mesmo?! 

![image](https://cloud.githubusercontent.com/assets/15165646/15223336/51a1926c-184a-11e6-9998-95fd3510cda8.png)

**Comment by lauradebella** [comment]
É isso mesmo. Por padrāo só serāo exibidas páginas com dados presentes e atualizados.
