### ISSUE TITLE
Selecione do Brasil  nos perfis

### ISSUE THREAD

**Issue by AnaCarolinaFDias** [DataViva/dataviva-site#1075]
Quando eu entro nos perfis e escolho uma pergunta que tem a localidade o único indicativo que eu selecionei o Brasil está na pergunta em cima do seletor.

![image](https://cloud.githubusercontent.com/assets/15165646/15223418/b438f262-184a-11e6-952e-c3ae42c92da4.png)

Se eu clico em alguma outra localidade e volto a clicar no Brasil, a localidade fica com a caixa de seleção como se estivesse selecionada e a pergunta fica com a localidade Brasil.

![image](https://cloud.githubusercontent.com/assets/15165646/15223465/f9ccb516-184a-11e6-8ed3-3d902201a057.png)

**Comment by eltonfreitas** [comment]
Aqui não está funcionando. Eu selecionei Brasil, mas o botão de seleção não indica que em fiz essa seleção:
![image](https://cloud.githubusercontent.com/assets/6808970/19476930/7e9437c8-951a-11e6-9a95-dd41d6fb5cb5.png)

Depois disso, selecionei São Paulo, e em seguida voltei a selecionar Brasil. Veja que o botão de São Paulo ficou destacado, mas Brasil não ficou e o nome no título da pergunta fica Brasil.
![image](https://cloud.githubusercontent.com/assets/6808970/19476971/c4360374-951a-11e6-8b5d-763408aaa1f7.png)

Para repetir isso, vá na tela de entrada do site em Empreendedores, escolha a pergunta: Qual o salário médio da Atividade Econômica X, na Localidade Y?
