### ISSUE TITLE
Download Salário e Emprego Rais 

### ISSUE THREAD

**Issue by AnaCarolinaFDias** [DataViva/dataviva-site#1077]
Tentei fazer o Download por esse filtro e abre uma página como nas imagens abaixo. 
Eu realmente não consigo baixar com o Filtro tudo em localidades? Porque se não tiver essa informação não seria melhor ocultar essa opção ? 

![image](https://cloud.githubusercontent.com/assets/15165646/15225442/d48ab94c-1854-11e6-8d8c-b96be29554f1.png)

![image](https://cloud.githubusercontent.com/assets/15165646/15225446/dd1b2376-1854-11e6-8420-1381bc243162.png)

Esse também não consegui fazer o Download, 
![image](https://cloud.githubusercontent.com/assets/15165646/15225547/4aa16f54-1855-11e6-8917-96e2def120d4.png)

![image](https://cloud.githubusercontent.com/assets/15165646/15225588/69dae45e-1855-11e6-9fe1-1bd990b6c346.png)

**Comment by lauradebella** [comment]
Este era o bug do botāo de download quando todos os filtros sāo all. Acabei de dar o merge - o botāo de download fica desativado quando nāo tem nenhum filtro selecionado.
