### ISSUE TITLE
Perfil Localidades: Mapa apresenta valores de 2015 e indicadores de 2014

### ISSUE THREAD

**Issue by AnaCarolinaFDias** [DataViva/dataviva-site#1078]
![image](https://cloud.githubusercontent.com/assets/15165646/15225868/b7be82b0-1856-11e6-83e0-766c8dcbfd76.png)

Alem disso temos abas com informações de 2013 , outra com informações de 2014 outra com informações de 2015 .

![image](https://cloud.githubusercontent.com/assets/15165646/15225909/df68a804-1856-11e6-85e2-b468da4fe8dd.png)

**Comment by lauradebella** [comment]
É isso mesmo! Os dados de ganho de oportunidade para Localidade sāo de 2014. Como cada aba vem de um banco diferente, os dados tem anos diferentes mesmo.

**Comment by eltonfreitas** [comment]
Na verdade o problema é outro. Os indicadores de listados para Oportunidades Econômicas deveriam ser também para 2015, assim como a Rede que é pra 2015.
![image](https://cloud.githubusercontent.com/assets/6808970/15514747/f8f891a8-21c0-11e6-9dca-5472ed11c737.png)

**Comment by eltonfreitas** [comment]
O gráfico não está mostrando este indicador, tem certeza que está correto? Há esse dado no banco? Pq não aparece no gráfico?
![image](https://cloud.githubusercontent.com/assets/6808970/15934674/d18922a0-2e3a-11e6-83e6-fd6a4b2cfbf6.png)
