### ISSUE TITLE
Estudos 

### ISSUE THREAD

**Issue by AnaCarolinaFDias** [DataViva/dataviva-site#1081]
Quando eu clico em algum estudo, e quero voltar para ver os outros estudos o Filtro Todos não funciona. 

![image](https://cloud.githubusercontent.com/assets/15165646/15290337/33febabc-1b4e-11e6-93fc-1482f1a08f9c.png)

**Comment by eltonfreitas** [comment]
Ainda não funciona, retirei o Ready!!

**Comment by lauradebella** [comment]
Está funcionando no staging, pode conferir por lá!
