### ISSUE TITLE
Estabelecimento de ensino Privada 

### ISSUE THREAD

**Issue by AnaCarolinaFDias** [DataViva/dataviva-site#1083]
Precisamos separar estabelecimento de ensino e a indicação de ser uma instituição  Privada sem fins lucrativos 

![image](https://cloud.githubusercontent.com/assets/15165646/15291771/fab26116-1b55-11e6-95cd-a51bbad9b0fd.png)

**Comment by lauradebella** [comment]
@AnaCarolinaFDias, precisamos do texto exato que deverá ser substituido!

**Comment by AnaCarolinaFDias** [comment]
@lauradebella 

Aonde tiver: é um estabelecimento de ensino Pública Federal  vai ser 
... é um estabelecimento de ensino da categoria Pública Federal...

Aonde tiver: é um estabelecimento de ensino Privada vai ser 
... é um estabelecimento de ensino da categoria Privada ...

**Comment by eltonfreitas** [comment]
![image](https://cloud.githubusercontent.com/assets/6808970/15514607/3ed4e498-21c0-11e6-9f1f-f51cf5b7f6a9.png)

**Comment by AnaCarolinaFDias** [comment]
@eltonfreitas A Laura chegou a arrumar mas acho que precisa da aprovação do Diogo para aparecer no site.

**Comment by eltonfreitas** [comment]
ok, quando estiver liberado então, coloca pra ready!!
