### ISSUE TITLE
Valor de exportação no Gráfico está diferente do que é apresentado no quadro resumo

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#1093]
Quando busco as informações da Balança Comercial, o quadro resumo (quadrados azuis) apresenta um número que é exatamente o DOBRO do valor que de fato aparece no gráfico e na base de dados, para EXP e IMP.

http://dataviva.info/pt/location/all

![image](https://cloud.githubusercontent.com/assets/6808970/15647615/2a0a2eb8-263b-11e6-8c30-cf6bff786d0a.png)

![image](https://cloud.githubusercontent.com/assets/6808970/15647626/3cc0d958-263b-11e6-93f1-02ea888bd085.png)

**Comment by VictorDMor** [comment]
Resolvido.
