### ISSUE TITLE
Melhorias: Postagem de visualização de gráficos nas notícias e no blog

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#1107]
Atualmente só é possível postar as visualizações como imagens, precisamos embedar os gráficos do DV para que os conteúdos fiquem interativos.

Tal como aqui:
`<iframe` width="560" height="315" src="http://legacy.dataviva.info/en/apps/embed/tree_map/secex/4mg/all/all/hs/?controls=true&year=2014&size=export_val&depth=hs_6&color=color" frameborder="0"></iframe>`

**Comment by Gilmardealcantara** [comment]
Olá Elton.
Para embedar os gráficos no editor de texto do blog é necessário usar a opção que habilita o uso de texto html, como mostrado abaixo : 

![captura de tela 2016-06-21 as 16 26 17](https://cloud.githubusercontent.com/assets/7262614/16243658/bc7d1914-37ce-11e6-8326-b78c364283a1.png)

Ao postar a notícia temos : 

![captura de tela 2016-06-21 as 16 35 01](https://cloud.githubusercontent.com/assets/7262614/16243695/deb1a694-37ce-11e6-9421-f4ee7ab01d03.png)

**Comment by eltonfreitas** [comment]
Gilmar, dá uma olhada na parte do editor html, está muito lento, se for o caso, mudar o tipo de editor html.

**Comment by FredericoVieira** [comment]
@eltonfreitas, não há necessidade de mudar o editor e sim de salvar as imagens no s3. Atualmente as imagens inseridas no editor são salvas diretamente no HTML causando lentidão na ferramenta. Essa modificação deve ser tratada em uma nova issue.

**Comment by eltonfreitas** [comment]
Ok @FredericoVieira, fecha essa issue então e abre outra com esse indicativo. Acho que vc explicaria melhor o que deve ter nessa nova issue. A gente tem que ter em mente que quem vai postar no blog não mexe no s3.
