### ISSUE TITLE
Correção dos botões para compartilhar conteúdo do site nas redes sociais

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#1108]
Botão para compartilhar conteúdo não funciona.
![image](https://cloud.githubusercontent.com/assets/6808970/15978578/59184d2c-2f35-11e6-800a-3bb741e62b77.png)

![image](https://cloud.githubusercontent.com/assets/6808970/15978591/71ff35e4-2f35-11e6-82db-c4390946b279.png)

**Comment by Gilmardealcantara** [comment]
O compartilhamento e feito com a url abreviada que não se comporta, exibindo os meta dados, como a url completa.
