### ISSUE TITLE
Botão "Add files" na aba "Publique um estudo" não está funcionando 

### ISSUE THREAD

**Issue by rafamape** [DataViva/dataviva-site#1118]
http://dataviva.info/pt/scholar/admin/article/new

Ao clicar no Botão "Add files" na aba "Publique um estudo" nada acontece.

![image](https://cloud.githubusercontent.com/assets/13002836/16117490/c02204fa-33a8-11e6-96a3-2729e5ae8ecc.png)

**Comment by FredericoVieira** [comment]
Rafa, essa correção está disponível no ambiente de homologação (staging.dataviva.info)

**Comment by rafamape** [comment]
Ok. O que falta para subir para produção? Como está ocorrendo este processo?

**Comment by FredericoVieira** [comment]
Basicamente correções no módulo de admin, help, upload de arquivos do Scholar. Temos que definir qual período faremos o merge para produção.
