### ISSUE TITLE
Limitações em download de dados

### ISSUE THREAD

**Issue by ebergoncalves** [DataViva/dataviva-site#1127]
Não existe a opção para baixar todos os anos. A série de dados está começando em 2002 e não em 2000.

![image](https://cloud.githubusercontent.com/assets/10499898/16317583/3338e5a8-3962-11e6-9678-d2462ec194a0.png)

**Comment by ebergoncalves** [comment]
Também não encontrei a opção para fazer download dos rankings. Sugiro colocar uma opção para download lá em rankings ou a opção rankings em Download de Dados/Banco de Dados.

**Comment by eltonfreitas** [comment]
@ebergoncalves não tem como disponibilizar todos os anos juntos pq ficaria inviável dado o tamanho do banco, daí quebramos o banco por anos e profundidade de cada agregação. Quanto ao download dos Rankings está indicada na #348.

**Comment by ebergoncalves** [comment]
@eltonfreitas Entendido. E sobre começar em 2002 e não em 2000?

**Comment by eltonfreitas** [comment]
Isso vai pra correção!! hehe
