### ISSUE TITLE
Impossivilidade de identificar município csv baixado de uma visualização

### ISSUE THREAD

**Issue by ebergoncalves** [DataViva/dataviva-site#1130]
@eltonfreitas 
Não é possível identificar os municípios na base de dados baixada a partir de uma visualização de dados municipais. Sugestão: sempre deixar o código ibge na base de dados.

![image](https://cloud.githubusercontent.com/assets/10499898/16322670/3bf6840c-397b-11e6-807e-8bb491a2de32.png)

![image](https://cloud.githubusercontent.com/assets/10499898/16322679/446debca-397b-11e6-933b-4bedee94d825.png)

**Comment by eltonfreitas** [comment]
@Gilmardealcantara  aqui a sugestão não é apresentar o Nome do Município, mas sim o ID IBGE desses municípios. Com ID o usuário poderá cruzar essa informação com qualquer outra tabela, fazer isso com Nome do Município pode gerar problemas.
