### ISSUE TITLE
Dados de exportações baixados não bate com informação visualizada

### ISSUE THREAD

**Issue by ebergoncalves** [DataViva/dataviva-site#1131]
@eltonfreitas 

Dados baixados das exportações por município de Goiás não bate com a informações de exportações totais exibidas em cima do gráfico. Verifiquei isso para 2013, 2012 e 2010. Não conferi os anos anteriores. Exemplo: exportações na base = US$ 4,7 bi. Informação em cima do gráfico: US$ 4,85 bi.

![image](https://cloud.githubusercontent.com/assets/10499898/16341517/d4bb41e0-3a03-11e6-9563-e0c96a7a0c91.png)

**Comment by ebergoncalves** [comment]
@eltonfreitas 
Peguei dados de 2012 e 2013 dos cinco municípios mais representativos de Goiás pelo Aliceweb (Rio Verde, Alto Horizonte, Luziânia, Itumbiara e Barro Alto). Os valores de  Itumbiara e Rio Verde para 2012 não batem com os da tabela baixada pelo DataViva. Assim, concluo que o erro pode estar na tabela disponível para download e não no valor exibido.

**Comment by eltonfreitas** [comment]
@ebergoncalves tentei refazer os passos aqui. Mas cheguei em um valor diferente do que você encontrou, tanto via perfil quanto via construa seu gráfico. Tenta refazer esse gráfico para ver se não há nenhum seleção a mais. 
http://dataviva.info/pt/location/3go
![image](https://cloud.githubusercontent.com/assets/6808970/16380198/f5d4a656-3c4b-11e6-9c54-1ff03f6bcf83.png)

http://dataviva.info/pt/build_graph/
![image](https://cloud.githubusercontent.com/assets/6808970/16380240/362ace9c-3c4c-11e6-82e8-6c966cf3af92.png)

Quanto ao download de dados, encontrei uma diferença no valor total exportado por goiás exibido no site e somando na tabela baixada. Vamos olhar isso.
