### ISSUE TITLE
Otimizar inserção de imagens no corpo do editor de texto summernote

### ISSUE THREAD

**Issue by FredericoVieira** [DataViva/dataviva-site#1162]
Salvar as imagens no serviço de armazenamento de imagens S3 e retornar o link da imagem para o summernote.

**Comment by eltonfreitas** [comment]
Não é possível inserir fotos com maior tamanho. Carrega infinitamente e nada acontece.

**Comment by FredericoVieira** [comment]
@eltonfreitas correção foi efetuada!
