### ISSUE TITLE
Primeiros Passos sumiram!!

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#1176]
![image](https://cloud.githubusercontent.com/assets/6808970/17065827/56e80352-501a-11e6-9873-23e05a78070e.png)

**Comment by eltonfreitas** [comment]
Também para as demais categorias

![image](https://cloud.githubusercontent.com/assets/6808970/17065846/74988ec6-501a-11e6-8887-1c8ee537c41e.png)

**Comment by FredericoVieira** [comment]
@eltonfreitas problema resolvido, o script que rodamos no banco não tinha atualizado a tabela.
