### ISSUE TITLE
legacy.dataviva.info down?

### ISSUE THREAD

**Issue by jspeis** [DataViva/dataviva-site#1220]
http://legacy.dataviva.info used to display the previous version of DataViva, but it appears to not be working at the moment? 

This breaks some of the embed functionality of [DataViva on the OEC](http://atlas.media.mit.edu/en/profile/country/bra/#dataviva)

**Comment by eltonfreitas** [comment]
Hi @jspeis, we'll look at here this problem.

**Comment by jspeis** [comment]
thanks @eltonfreitas!

**Comment by davelandry** [comment]
@eltonfreitas any update on this?

**Comment by eltonfreitas** [comment]
Hi @davelandry, I requested to @diogolundberg fix this problem. There was an exchange of servers AWS from São Paulo to US, for this legacy database down.

**Comment by FredericoVieira** [comment]
The Legacy server settings have been updated. The server is now available for access.
http://legacy.dataviva.info/en/

**Comment by davelandry** [comment]
👍

**Comment by alexandersimoes** [comment]
Nice thanks guys! 🍻
