### ISSUE TITLE
Possibilidade de postar no blog em duas línguas (pt/en)

### ISSUE THREAD

**Issue by luizalages** [DataViva/dataviva-site#1227]
Desenvolver na página de postagem do blog (http://dataviva.info/pt/blog/admin/post/new) campos para inserção de texto em inglês.
Os campos na primeira língua (pt) permaneceriam obrigatórios para postagem e os na segunda (en) seriam opcionais.
Para o usuário/leitor, desenvolver um botão para acesso ao texto na outra língua, quando esta opção existir.

**Comment by luisccf** [comment]
Boa tarde, Luiza!
@luizalages 

Essa funcionalidade deve ser implementada também na seção de notícias?

**Comment by luizalages** [comment]
Falta um campo em segunda língua, para postagem de autor.

**Comment by luizalages** [comment]
No blog da página en (http://dataviva.info/en/blog) não aparecer os textos em português: se a opção de postar em inglês for selecionada, o post, em inglês, aparece (na versão en); se a opção de postar em inglês não for selecionada, nada vai para a versão en.

**Comment by luizalages** [comment]
Como os textos vão se dividir nas páginas en/pt, retirar o botão de tradução "português/english"

**Comment by luisccf** [comment]
#1318 

Posts em inglês e português não estão mais relacionados. Ao criar um novo, é possível especificar o idioma.
