### ISSUE TITLE
Postar e baixar conteúdo na aba "estudos" com o condicional de estar logado

### ISSUE THREAD

**Issue by luizalages** [DataViva/dataviva-site#1251]
Desenvolver um condicional de estar logado no site para baixar e postar conteúdo no campo "estudos" (http://dataviva.info/pt/scholar/). Caso o usuário não esteja logado, ao clicar no botão "Baixar arquivo" (ex: http://dataviva.info/pt/scholar/article/64), aparecer o pop-up de cadastro no site. E, para postar um estudo, caso o usuário não esteja logado, aparecer o pop-up de cadastro ao clicar no botão "enviar" (http://dataviva.info/pt/scholar/admin/article/new). O texto explicativo na aba "Publique um estudo" deve deixar claro que o usuário precisa estar logado para fazer a postagem. O mesmo vale para o texto introdutório em Estudos, no caso de baixar conteúdo.

Dar um prazo de até 10 dias úteis para aceite do estudo postado - os administradores devem ser avisados via e-mail de nova postagem no campo estudos. O e-mail notificado pode ser o dataviva@fapemig.br

**Comment by FredericoVieira** [comment]
Quando o usuário faz o cadastro ou loga no site para baixar/publicar um estudo, é redirecionado para a página inicial, usuário deve permanecer na página atual. Verificar opção de criar um modal de aviso com login ou cadastra-se.

**Comment by luizalages** [comment]
Bug para logar via Facebook e Twitter ao baixar um arquivo em estudos. 
![erro](https://cloud.githubusercontent.com/assets/21228162/19284404/2536e6f6-8fcc-11e6-9702-9554d1259adb.JPG)
