### ISSUE TITLE
Link retorna página não encontrada

### ISSUE THREAD

**Issue by lucasdiasas** [DataViva/dataviva-site#1273]
http://dataviva.info/pt/location/4sp?menu=exports-municipality-tree_map&url=tree_map%2Fsecex%2F4mg%2Fall%2Fall%2Fbra%3Fdepth%3Dbra_9%26controls%3Dtrue%26size%3Dexport_val

Em exportações > por estado > ao clicar no link trocar de estado/município (São Paulo p.ex.)

**Comment by FredericoVieira** [comment]
@lucasdiasas onde esse link foi gerado?

O correto seria:
http://dataviva.info/en/location/4sp/trade-partner?menu=exports-municipality-tree_map&url=tree_map%2Fsecex%2F4sp%2Fall%2Fall%2Fbra%3Fdepth%3Dbra_9%26controls%3Dtrue%26size%3Dexport_val

**Comment by lucasdiasas** [comment]
Tentei seguir os passos anteriores e não houve o mesmo erro. Aparecendo novamente reporto pra vcs. @FredericoVieira

**Comment by FredericoVieira** [comment]
Ok! Obrigado @lucasdiasas!
