### ISSUE TITLE
Ajuste de imagens e gráficos para acesso mobile

### ISSUE THREAD

**Issue by luizalages** [DataViva/dataviva-site#1283]
Desenvolver ajuste das imagens e gráficos embedados postados em blog e notícias, para a visualização mobile. Atualmente o texto se ajusta à tela em dispositivo móvel, mas esses outros formatos não.

**Comment by FredericoVieira** [comment]
Desfiguração de imagens com diferença significativa entre altura e largura; Gráficos não se enquandram em certas resoluções.

**Comment by FredericoVieira** [comment]
Adicionar responsividade nos gráficos da plataforma.
