### ISSUE TITLE
Columns names and ID's in Data Section

### ISSUE THREAD

**Issue by mariohmol** [DataViva/dataviva-site#129]
Today we have in Data section the attributes showed just as ID's. 
Examples:
* ID BRA ( ex.: MGPLR01	) 
* ID HS
* ID WLD
* CBO ID ( ex,: 5101)

In some cases those ID's are relevant just for Dataviva, but not for the user. Ex.:
* ID BRA - The ideal is to use IBGE Code

Migrate:
* One work is to migrate ID BRA to IBGE Code
* Other is to cut HS (show just 4 digits as the original HS code)
* Check if others classifications should change (is CBO and WLD ok? ) 

Add at the end of the Data Table the descriptive columns used in the query.
For example, if it have a HS ID, we should add at the end of the table the respective name of the Product (HS).  Apply this for all attributes (listed in top)

**Comment by eltonfreitas** [comment]
@davelandry, it's issue could be closed?

**Comment by davelandry** [comment]
@eltonfreitas, can you explain what you mean?

**Comment by eltonfreitas** [comment]
Dave, I think it is now ok!  Data section show now ID from IBGE and ID CNAE, etc. I think this is already solved, right?

**Comment by davelandry** [comment]
Looks good to me!
