### ISSUE TITLE
Criar comunicado para divulgação de disponibilidade e atualizações do DataViva

### ISSUE THREAD

**Issue by FredericoVieira** [DataViva/dataviva-site#1297]

**Comment by FredericoVieira** [comment]
@luizalages, é viável adicionar dois comunicados ao RD para avisarmos aos usuários sobre as atualizações do DataViva?
1. Informativo com data e hora da atualização além do período de indisponibilidade da plataforma (Envios 7 dias antes e no dia da atualização por exemplo).
2. Informativo do fim da atualização e liberação da plataforma, contendo as issues resolvidas e as melhorias implementadas.

**Comment by luizalages** [comment]
@FredericoVieira é possível sim. Vocês só precisam me passar o texto (pode ser mais bruto, eu edito) com certa antecedência. Mas isso só vai ser possível após a contratação da RD. Até lá, sugiro utilizarmos o nosso email ou outros mecanismos de disparo (mail chimp, por exemplo).
