### ISSUE TITLE
Melhoria do layout e responsividade no modal de login

### ISSUE THREAD

**Issue by FredericoVieira** [DataViva/dataviva-site#1298]

**Comment by eltonfreitas** [comment]
@FredericoVieira o que significa isso pra que eu possa testar?

**Comment by FredericoVieira** [comment]
O estilo do modal e responsividade.

![1](https://cloud.githubusercontent.com/assets/8905198/19736970/57a36bc6-9b90-11e6-878e-ca9e90bf6f19.png)

![2](https://cloud.githubusercontent.com/assets/8905198/19736971/5b5e5424-9b90-11e6-8faa-917d0ffaf0c3.png)
