### ISSUE TITLE
Stacked breaks showing average monthly wage

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#130]
When you try to filter the staked by Average monthly wage it shows a wrong result: 
http://dataviva.info/apps/builder/stacked/rais/mg/all/2312/isic/?controls=true&value_var=wage_avg&sort=color&depth=isic_1&layout=value&order=asc

![image](https://cloud.githubusercontent.com/assets/7582295/3085537/a70ae8fa-e513-11e3-936f-6e370fe59691.png)

**Comment by davelandry** [comment]
Confirmed fixed by the new version.
