### ISSUE TITLE
Imagens da seção "Veja também" possuem tamanhos diferentes em algumas resoluções

### ISSUE THREAD

**Issue by FredericoVieira** [DataViva/dataviva-site#1302]
![issues_imagens com tamanhos diferentes na listagem](https://cloud.githubusercontent.com/assets/8905198/19280575/f2125d3c-8fbc-11e6-9d65-0a3fdbb8265c.png)

**Comment by eltonfreitas** [comment]
@luizalages pode dar uma checada nessa issue?
