### ISSUE TITLE
Fazer uma revisão dos títulos de todos os gráficos

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#1317]
@FredericoVieira prepara uma lista com todos os títulos dos gráficos que aparecem no DV. Vamos fazer uma revisão deles.

**Comment by PriscillaOmegatel** [comment]
@eltonfreitas 
Os títulos estão sendo corrigidos a medida em que os gráficos estão sendo atualizados e as issues estão sendo encerrada a medida que estamos atualizando.

**Comment by PriscillaOmegatel** [comment]
Não temos a especificação de nenhum gráfico a ser corrigido até o momento.
