### ISSUE TITLE
visualização classificação localidades

### ISSUE THREAD

**Issue by msbandrade** [DataViva/dataviva-site#1327]
Notei um pequeno problema para visualisar classificação de localidades brasileiras:

![bus](https://cloud.githubusercontent.com/assets/20859423/19600554/63767188-9784-11e6-979f-64d96e03e210.jpg)

**Comment by Gilmardealcantara** [comment]
Olá Marcelo, não estou conseguindo reproduzir esse erro, você podeira descrever o passo a passo ou colocar outra imagem, a resolução não está ajudando muito.

**Comment by msbandrade** [comment]
Parece que voltou ao normal mesmo Gilmar. Valew. 
Vou retirar a issue. Abs.
