### ISSUE TITLE
Missing MDIC Code

### ISSUE THREAD

**Issue by mariohmol** [DataViva/dataviva-site#137]
There is some municpalities missing MDIC code from raw data here some examples:

3413900
3432504
3447908
4220000
4212650
4314548
5300100 
5300605
5303500
5304953
5207976
5316908
5321858
5322203 

So the ideia is to review the attrs_bra to guarantee that all codes are there.

**Comment by alexandersimoes** [comment]
These municipalities have all been fixed and data was recalculated with the 2.0 updates.
