### ISSUE TITLE
Occugrid tooltip improvements

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#14]
Dave and Alex,

I was taking a look at the occugrid and found some regions that have RCA>1 but have not filled areas. You said that when the location had RCA it would show all filled because was compared to itself. What is happening?

![image](https://f.cloud.github.com/assets/6068338/1646442/58ee9d94-591b-11e3-9500-98ce2a6090aa.png)
![image](https://f.cloud.github.com/assets/6068338/1646443/5e3b0152-591b-11e3-828f-7c06a800708f.png)

![image](https://f.cloud.github.com/assets/6068338/1646444/64b80804-591b-11e3-9ced-fc79f2903863.png)
![image](https://f.cloud.github.com/assets/6068338/1646445/6a882462-591b-11e3-9872-610635692273.png)

**Comment by dgomes2004** [comment]
Guys, since we are keeping the same calculation for occugrid, we need to clarify the first point of this issue and also check the similar locations (bellow an example of how it is not making sense, the comparison is just with MG itself, so why it is not all filled?)

![image](https://cloud.githubusercontent.com/assets/6068338/6644875/4c5ddab2-c996-11e4-805f-452f05c260c2.png)

http://dv2.datawheel.us/apps/builder/occugrid/rais/4mg/c30415/all/cbo/?controls=true&year=2013&size=required&order=name

**Comment by dgomes2004** [comment]
The point is: we need to sort out what is being shown on occugrid.

**Comment by davelandry** [comment]
I created a new issue for your example of the similar location list not making sense: #265 

As far as what is being shown, what is the issue here? We are showing the same as we've always shown. We could do 2 things to simplify the output:
* remove the holes in the centers to create just simple pie charts
* remove the shaded area of "employees available elsewhere"

What do you guys think?

**Comment by dgomes2004** [comment]
I think the output is ok and should stay as it is. My point is about what each number says. Example: my understading was that the Estimated Employees number was by establishment, but as you can see bellow, it shows that a restaurant needs 879 bakers, and this does not make any sense.

![image](https://cloud.githubusercontent.com/assets/6068338/6668393/6b6770a2-cbd1-11e4-8736-d17307f8f9f7.png)

http://dv2.datawheel.us/apps/builder/occugrid/rais/4mg/i56112/all/cbo/?controls=true&year=2013&size=required&order=name

This example may be a bug, but what I think we need in the Occugrid is a tooltip that explains what each number means (as we have an explanation for the similar location, this one is good). And to put them in a more logical order: since de estimated is the whole circle, this could be the first info, then the number of employees in the industry, then the number of employees in other industries. And it needs to be clear it is for 1 establishment, the average for the similar locations.

Makes sense?

**Comment by davelandry** [comment]
I've cleaned up the tooltip using your suggestions, and I've also changed the variable used to fill in the circles. Previously we were using number of employees per establishment, but that does not line up with how we are now calculating the estimated number, so I've changed it to just number of employees for all establishments (and the visualizations look much better).
