### ISSUE TITLE
Mapa mostra estados do Brasil quando um estado é selecionado

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#1435]
Foi Selecionado Minas Gerais, mas o Mapa mostra o Brasil.
http://staging.dataviva.info/pt/location/4mg/health?menu=equipments-municipality-map&url=cnes_equipment%2Fequipments%3Ffilters%3Dequipment_type

![image](https://cloud.githubusercontent.com/assets/6808970/24625290/eb77f878-1884-11e7-93ef-e89cd06dcc9f.png)

**Comment by luisccf** [comment]
#1463
