### ISSUE TITLE
Privado com fins lucrativos

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#1438]
Existem dois grupos com título igual (PRIVADO COM FINS LUCRATIVOS). Fica confuso mesmo sendo de grupos diferentes. É preciso checar os agrupamentos.

http://staging.dataviva.info/pt/location/4sp090607/health?menu=establishments-provider-type-tree_map&url=cnes_establishment%2Fprovider_type%2Festablishments%3Ffilters%3Dambulatory_attention%2Bhospital_attention%26hierarchy%3Dfalse%26year%3D2015%26id_ibge%3D3550308

![image](https://cloud.githubusercontent.com/assets/6808970/24625681/30a942ca-1886-11e7-93b9-909cbe9f6652.png)

**Comment by luisccf** [comment]
#1469
