### ISSUE TITLE
Gráfico só mostra São Paulo

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#1440]
![image](https://cloud.githubusercontent.com/assets/6808970/24627674/1cf83fb4-188c-11e7-9ce6-1b17c41c0734.png)

http://staging.dataviva.info/pt/location/4sp090607/health?menu=equipments-municipality-tree_map&url=cnes_equipment%2Fmunicipality%2Fequipments%3Fhierarchy%3Dfalse%26year%3D2015%26id_ibge%3D3550308

**Comment by luisccf** [comment]
#1464
