### ISSUE TITLE
Gráfico de equipamentos por município, tipo evolução, não está carregando

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#1443]
http://staging.dataviva.info/pt/location/4mg/health?menu=equipments-municipality-stacked&url=cnes_equipment%2Fmunicipality%2Fequipment_quantity%3Fvalues%3Dequipment_quantity%2Bequipment_quantity_in_use%26depths%3Dmunicipality%2Bhealth_region%2Bequipment_type%2Bequipment_code%2Bunit_type%2Bsus_availability_indicator%26filters%3Dequipment_type%2Bequipment_code%2Bunit_type%2Bsus_availability_indicator%26id_ibge%3D31

![image](https://cloud.githubusercontent.com/assets/6808970/24628578/5614fb7e-188d-11e7-8cca-b1c8a8923cb9.png)

**Comment by sauloantuness** [comment]
#1465 Duplicada
