### ISSUE TITLE
Rótulos do eixo y são muito extensos

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#1449]
Usar M para milhão e k para mil, etc. Assim como já é no DataViva.

http://staging.dataviva.info/pt/location/4sp090607/health?menu=equipments-type-stacked&url=cnes_equipment%2Fequipment_type%2Fequipment_quantity%3F%26values%3Dequipment_quantity%2Bequipment_quantity_in_use%26depths%3Dequipment_type%2Bequipment_code%2Bhealth_region%2Bunit_type%2Bsus_availability_indicator%26filters%3Dunit_type%2Bsus_availability_indicator%26id_ibge%3D3550308

![image](https://cloud.githubusercontent.com/assets/6808970/24629149/6d920fb6-188e-11e7-90b3-c52a5a1eb6ae.png)

**Comment by sauloantuness** [comment]
A abreviação acontece apenas quando o idioma selecionado é o Inglês. Exatamente como é no DataViva.

![en](https://cloud.githubusercontent.com/assets/1711258/24879386/1a74e19e-1e0d-11e7-817c-cc59e30ffb23.PNG)
![pt](https://cloud.githubusercontent.com/assets/1711258/24879387/1a82deb6-1e0d-11e7-90d2-8fc6216c34cb.PNG)
![en2](https://cloud.githubusercontent.com/assets/1711258/24879484/74208dba-1e0d-11e7-9ae0-625a75fe5ace.PNG)
![pt2](https://cloud.githubusercontent.com/assets/1711258/24879483/741b8284-1e0d-11e7-99e8-e26c6d176796.PNG)
