### ISSUE TITLE
NH 2-Médiam1 ao invés de NH 2-Média M1???

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#1455]
![image](https://cloud.githubusercontent.com/assets/6808970/24630335/b17d1b54-1892-11e7-932c-163b1ce26c16.png)

http://staging.dataviva.info/pt/location/4sp090607/health?menu=establishments-provider-type-tree_map&url=cnes_establishment%2Fprovider_type%2Festablishments%3Ffilters%3Dambulatory_attention%2Bhospital_attention%26hierarchy%3Dfalse%26year%3D2015%26id_ibge%3D3550308

**Comment by eltonfreitas** [comment]
@Yasminef temos que melhorar esses rótulos.

**Comment by Yasminef** [comment]
Concordo

**Comment by Yasminef** [comment]
@eltonfreitas 

**NH 1-PAB-PABA** = Estabelecimento de Saúde ambulatorial que realiza somente Procedimentos de Atenção Básica – PAB e ou Procedimentos de Atenção Básica Ampliada – PABA, definidos pela NOAS. 
**NH 2-MÉDIAM1** = Estabelecimento de Saúde ambulatorial que realiza somente procedimentos de Média Complexidade definidos pela NOAS como de 1º nível de referência – M1. 
**NH 3-MÉDIA M2 e M3** = Estabelecimento de Saúde ambulatorial que realiza procedimentos de Média Complexidade definidos pelo Ministério da Saúde como de 2º nível de referência – M2 e/ou de 3º nível de referência – M3
**NH 4-ALTA COMPLEXIDADE AMBULATORIAL** = Estabelecimento de Saúde ambulatorial que realiza procedimentos de Alta Complexidade definidos pelo Ministério da Saúde 
**NH 5-BAIXA M1 e M2** = Estabelecimento de Saúde que realiza além de procedimentos nos de níveis de hierarquia 01 e 02, efetua, primeiro atendimento hospitalar em pediatria e em clínica médico, partos e outros procedimentos hospitalares de menor complexidade em clínica, cirurgia, pediatria e obstetrícia. 
**NH 6-MÉDIA M2 e M3** = Estabelecimento de Saúde que realiza procedimentos nos níveis de hierarquia 02 e 03. Além de procedimentos hospitalares de média complexidade. Por definição, enquadram-se neste nível, os hospitais especializados.
**NH 7- MÉDIA M3** = Estabelecimento de Saúde que realiza procedimentos hospitalares de média complexidade. Realiza procedimentos previstos nos estabelecimentos de níveis de hierarquia 02 e 03, abrangendo SADT ambulatorial de alta complexidade. 
**NH 8-ALTA COMPLEXIDADE HOSPITALAR/AMBULATORIAL** = Estabelecimento de Saúde capacitado a realizar procedimentos de alta complexidade no âmbito hospitalar e ou ambulatorial.
