### ISSUE TITLE
Estabelecimentos por Tipo de Unidade - Treemap

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#1470]
![screen shot 2017-04-05 at 11 12 41](https://cloud.githubusercontent.com/assets/6808970/24709602/cfd601a6-19f0-11e7-82e7-96d8195611ea.png)

http://staging.dataviva.info/pt/location/4mg/health?menu=establishments-unit-type-tree_map&url=cnes_establishment%2Funit_type%2Festablishments%3Ffilters%3Dambulatory_attention%2Bhospital_attention%26hierarchy%3Dfalse%26id_ibge%3D31

1.  Exibir no gráfico Tipo de Unidades. No entanto, disponibilizar filtro para a troca da agregação entre Tipo de Unidade(tp_unid) e Tipo de Prestador (tp_prest).

Excluir essas opções aqui da forma como são apresentadas:
![screen shot 2017-04-05 at 11 17 14](https://cloud.githubusercontent.com/assets/6808970/24709773/7256a6f6-19f1-11e7-9f16-a01471acbb94.png)

2. Tamanho/Valor: Número de Estabelecimentos (count número de cnes)

3. Acrescentar filtro para indicar "Disponibilidade para o SUS" (vinc_sus): tem que ter 3 opções nesse filtro: Todos; Disponível; Não Disponível

4. Título: Estabelecimentos de saúde em [Nome da Localidade] por Tipo de Unidade [ou agregação escolhida, Tipo de Prestador]: lembrar de tratar a preposição em com o artigo adequado do Nome da Localidade, isso já existe na tabela de atributos.

5. Filtro "Nível de Atenção": Concatenar as variáveis Nível de atenção ambulatorial (nivate_a) e Nível de atenção hospitalar (nivate_h) e transformar em um único filtro com as seguintes opções de escolha: Ambulatorial (nivate_a = 1 e nivate_h=0); Hospitalar (nivate_a = 0 e nivate_h=1); Ambulatorial/Hospitalar (nivate_a = 1 e nivate_h=1); Nenhum (nivate_a = 0 e nivate_h=0); Todos (acrescentar aqui também a opção "Todos" para marcar todos os níveis de atenção).

6. Filtro "Nível de Hierarquia":  incluir filtro Nível de Hierarquia (niv_hier_2); acrescentar aqui também a opção "Todos" para marcar todos os níveis de hierarquia.

7. Default - O que exibir quando o gráfico abrir : Ano mais recente;  Número de Estabelecimentos; Todos (Disponibilidade para o SUS); Todos (Nível de Atenção). Esses devem está marcados quando o gráfico abrir pela primeira vez.

**Comment by luisccf** [comment]
Tipo de unidade é agregado por tipo de provedor?


Por exemplo:

**Tipo de unidade selecionado (agregado por tipo de provedor)**
Nesse caso, 38,9% dos estabelecimentos são consultórios privados com fins lucrativos (vermelho), e 8,4% são consultórios com tipo de provedor não informado (amarelo claro).
![captura de tela 2017-04-05 as 15 25 14](https://cloud.githubusercontent.com/assets/14101365/24720623/20c803de-1a14-11e7-84ec-2ef1bd1fee97.png)



E quando seleciona a agregação por tipo de provedor:

**Tipo de provedor selecionado**
![captura de tela 2017-04-05 as 15 54 23](https://cloud.githubusercontent.com/assets/14101365/24721926/329cbeac-1a18-11e7-80ae-af90ae569d66.png)


Ou é pra fazer como se fossem dois gráficos diferentes, com tipo de unidade e tipo de provedor sem relação um com o outro? Assim:

**Tipo de provedor selecionado**
![captura de tela 2017-04-05 as 15 42 30](https://cloud.githubusercontent.com/assets/14101365/24721363/8522c812-1a16-11e7-92c5-ef9a70dceb3a.png)

**Tipo de unidade selecionado**
![captura de tela 2017-04-05 as 15 41 45](https://cloud.githubusercontent.com/assets/14101365/24721515/f8da8f7e-1a16-11e7-8c74-a33c18dcb63e.png)

**Comment by eltonfreitas** [comment]
@luisccf, é exatamente a primeira opção!! Ficou show heim! É um gráfico único, onde troca apenas o nível de agregação. As legendas do gráfico será os tipos de prestador!!

**Comment by eltonfreitas** [comment]
Faltou ***Acrescentar filtro para indicar "Disponibilidade para o SUS" (vinc_sus): tem que ter 3 opções nesse filtro: Todos; Disponível; Não Disponível***

**Comment by eltonfreitas** [comment]
Checar se não existe algum erro!!
A figura mostra estabelecimentos Disponíveis ao SUS:
![image](https://cloud.githubusercontent.com/assets/6808970/25101173/8e424c0c-2389-11e7-89c8-87af63aaa951.png)

Já esta figura mostra estabelecimentos Não disponíveis ao SUS:
![image](https://cloud.githubusercontent.com/assets/6808970/25101234/d1c98ecc-2389-11e7-9c63-212a76df4e37.png)

Está certo isso? Público Municipal não ser disponível ao SUS?

**Comment by luisccf** [comment]
As opções estavam invertidas.
