### ISSUE TITLE
Leitos por Tipo - Evolução

### ISSUE THREAD

**Issue by Yasminef** [DataViva/dataviva-site#1483]
![image](https://cloud.githubusercontent.com/assets/19650037/24868192/a7594f8c-1de5-11e7-9e47-ff6b192417ca.png)
http://staging.dataviva.info/pt/location/4mg/health?menu=beds-bed-type-stacked&url=cnes_bed%2Funit_type%2Fbeds%3Fvalues%3Dbeds%2Bnumber_sus_bed%2Bnumber_non_sus_bed%26depths%3Dunit_type%2Bbed_type%2Bbed_type_per_specialty%2Bhealth_region%26filters%3Dbed_type%2Bbed_type_per_specialty%2Bhealth_region%26id_ibge%3D31

1. Exibir no gráfico Tipo de Leitos. No entanto, disponibilizar filtro para a troca da agregação entre Tipo de Leitos (tp_leito) e Especialidade do Leito (codleito).

2. Tamanho/Valor: Quantidade de Leitos (qt_exist).

3. Acrescentar filtro para indicar "Quantidade de leitos SUS" (qt_sus), Quantidade de leitos não SUS (qt_nsus), Quantidade Existente de leitos (qt_exist) : tem que ter 3 opções nesse filtro: Todos; Leitos SUS, Leitos não SUS.

4. Título: Evolução da Quantidade de Leitos em [Nome da Localidade] por Tipo de Leito [ou agregação escolhida, Especialidade]: lembrar de tratar a preposição em com o artigo adequado do Nome da Localidade, isso já existe na tabela de atributos.

5. Filtro Tipo de Unidade (tp_unid): Acrescentar aqui também a opção "Todos" para marcar todos os tipos de unidade

6. Default -  O que exibir quando o gráfico abrir : Quantidade Existente (qt_exist); Todos (Tipo de Unidade); Todos (Quantidade Existente de Leitos) . Esses devem está marcados quando o gráfico abrir pela primeira vez.

**Comment by eltonfreitas** [comment]
Está em inglês.
![image](https://cloud.githubusercontent.com/assets/6808970/24976749/0be0b5aa-1fa1-11e7-8e7d-4f57b03bfa05.png)
