### ISSUE TITLE
Profissionais por Município - Mapa

### ISSUE THREAD

**Issue by Yasminef** [DataViva/dataviva-site#1493]
![image](https://cloud.githubusercontent.com/assets/19650037/24912690/3f3d77be-1ea5-11e7-89f3-d5d69b5eff60.png)

http://staging.dataviva.info/pt/location/4mg/health?menu=professionals-municipality-map&url=cnes_professional%2Fprofessionals%3Ffilters%3Dsus_healthcare_professional%2Boccupation_family

1.  Exibir um mapa de calor por município se as opções escolhidas de localidade forem Estado, Mesorregião, Microrregião. Se as opções escolhidas forem Brasil ou Região (ex. Sudeste, Nordeste, etc) mostrar mapa de calor por UF. Ver exemplo:
![screen shot 2017-04-04 at 11 23 19](https://cloud.githubusercontent.com/assets/6808970/24661585/21e5a780-1929-11e7-9f5e-833a91c9dbfe.png)

2. Tamanho/Valor: Número de Profissionais (cnes_prof)

3. Acrescentar filtro para indicar "Profissionais de Atendimento SUS" (prof_sus): tem que ter 3 opções nesse filtro: Todos; Profissional de Atendimento ao SUS; Profissional de não Atendimento ao SUS

4. Título: Distribuição dos Profissionais de Saúde por Unidade Territorial em [Nome da Localidade]: lembrar de tratar a preposição **em** com o artigo adequado do Nome da Localidade, isso já existe na tabela de atributos.

5. Filtro Tipo de Unidade (tp_unid): Acrescentar aqui também a opção "Todos" para marcar todos os tipos de unidade

6. Default - O que exibir quando o gráfico abrir : Ano mais recente; Todos (Tipo de Prestador); Número de Profissionais; Todos (Todos os profissionais); Todos (Tipo de Unidade). Esses devem está marcados quando o gráfico abrir pela primeira vez.

**Comment by eltonfreitas** [comment]
Faltou **Filtro Tipo de Prestador (tp_prest): Acrescentar aqui também a opção "Todos" para marcar todos os tipos de prestador**

**Comment by Yasminef** [comment]
A variável Tipo de prestador (tp_prest) não existe no Banco de profissionais. Vou fazer a alteração da issue.
