### ISSUE TITLE
Profissionais por Município - Evolução 

### ISSUE THREAD

**Issue by Yasminef** [DataViva/dataviva-site#1495]
![image](https://cloud.githubusercontent.com/assets/19650037/24914301/3b330f12-1eaa-11e7-8a4c-cf55dc1b9888.png)

http://staging.dataviva.info/pt/location/4mg/health?menu=professionals-municipality-stacked&url=cnes_professional%2Fmunicipality%2Fprofessionals%3Fvalues%3Dprofessionals%26depths%3Dmunicipality%2Boccupation_family%2Bsus_healthcare_professional%2Bhealth_region%26filters%3Doccupation_family%2Bsus_healthcare_professional%2Bhealth_region%26id_ibge%3D31

1.  Exibir no gráfico a Unidade territorial imediatamente inferior a unidade selecionada. Exemplo, se Escolhido Estado de Minas Gerais, o gráfico deve exibir as Mesorregiões de MG, ou se selecionar Nordeste, o gráfico deve exibir os estados do nordeste, e assim vai. No entanto, disponibilizar filtro para a troca da agregação do território, além das agregações definidas pelo IBGE, adicionar uma opção para Região de Saúde, exemplo:
![screen shot 2017-04-05 at 11 05 33](https://cloud.githubusercontent.com/assets/6808970/24709300/d66b065c-19ef-11e7-8767-48eb96074751.png)

2. Tamanho/Valor: Número de Profissionais (cnes_prof)

3. Acrescentar filtro para indicar "Profissionais de Atendimento SUS" (prof_sus): tem que ter 3 opções nesse filtro: Todos; Profissional de Atendimento ao SUS; Profissional de não Atendimento ao SUS

4. Título: Evolução do Número de Profissionais de Saúde em [Nome da Localidade] por Município [ou agregação territorial escolhida]: lembrar de tratar a preposição **em** com o artigo adequado do Nome da Localidade, isso já existe na tabela de atributos.

5. Filtro Tipo de Unidade (tp_unid): Acrescentar aqui também a opção "Todos" para marcar todos os tipos de unidade

6. Filtro "Nível de Hierarquia": incluir filtro Nível de Hierarquia (niv_hier_2); acrescentar aqui também a opção "Todos" para marcar todos os níveis de hierarquia.

7. Default - O que exibir quando o gráfico abrir : Número de Profissionais; Todos (Disponibilidade para o SUS); Todos (Tipo de Unidade), Todos (Nível de Hierarquia). Esses devem está marcados quando o gráfico abrir pela primeira vez.

**Comment by eltonfreitas** [comment]
Checar os dados de 2009:
![image](https://cloud.githubusercontent.com/assets/6808970/24977849/f5023828-1fa4-11e7-9051-be26b9d3163a.png)
