### ISSUE TITLE
Profissionais por Tipo de Unidade - TreeMap

### ISSUE THREAD

**Issue by Yasminef** [DataViva/dataviva-site#1496]
![image](https://cloud.githubusercontent.com/assets/19650037/24915128/b893c166-1eac-11e7-929f-27b9d1688f19.png)

http://staging.dataviva.info/pt/location/4mg/health?menu=professionals-provider-unit-tree_map&url=cnes_professional%2Funit_type%2Fprofessionals%3Ffilters%3Dsus_healthcare_professional%26id_ibge%3D31

1.  Exibir no gráfico Tipo de Unidades.

2. Tamanho/Valor: Número de Profissionais

3. Acrescentar filtro para indicar "Disponibilidade para o SUS" (prof_sus): tem que ter 3 opções nesse filtro: Todos; Atendimento SUS; Não Atendimento SUS

4. Título: Profissionais de Saúde em [Nome da Localidade] por Tipo de Unidade [ou agregação escolhida, Tipo de Prestador]: lembrar de tratar a preposição em com o artigo adequado do Nome da Localidade, isso já existe na tabela de atributos.

5. Filtro "Nível de Hierarquia":  incluir filtro Nível de Hierarquia (niv_hier_2); acrescentar aqui também a opção "Todos" para marcar todos os níveis de hierarquia.

7. Default - O que exibir quando o gráfico abrir : Ano mais recente;  Número de Profissionais; Todos (Disponibilidade para o SUS); Todos (Nível de Hierarquia). Esses devem está marcados quando o gráfico abrir pela primeira vez.

**Comment by eltonfreitas** [comment]
Acrescentar filtro pra tipo de prestador ou tipo de unidade:
![image](https://cloud.githubusercontent.com/assets/6808970/24977988/6bd94fc2-1fa5-11e7-979c-20528cd99a7d.png)

Corrigir o nome para **Tipo de Unidade**:
![image](https://cloud.githubusercontent.com/assets/6808970/24978028/84af247c-1fa5-11e7-8f09-8d469f6a516f.png)

**Comment by sauloantuness** [comment]
A variável Tipo de prestador (tp_prest) não existe no Banco de profissionais.
