### ISSUE TITLE
Profissionais por Tipo de Unidade - Evolução

### ISSUE THREAD

**Issue by Yasminef** [DataViva/dataviva-site#1497]
![image](https://cloud.githubusercontent.com/assets/19650037/24915523/c1736164-1ead-11e7-878e-5a4a669c29e2.png)

http://staging.dataviva.info/pt/location/4mg/health?menu=professionals-provider-unit-stacked&url=cnes_professional%2Funit_type%2Fprofessionals%3Fvalues%3Dprofessionals%26depths%3Dunit_type%2Boccupation_family%2Bsus_healthcare_professional%2Bhealth_region%26filters%3Doccupation_family%2Bsus_healthcare_professional%2Bhealth_region%26id_ibge%3D31

1.  Exibir no gráfico Tipo de Unidade

2. Tamanho/Valor: Número de Profissionais (cnes_prof)

3. Acrescentar filtro para indicar "Profissionais de Atendimento SUS" (prof_sus): tem que ter 3 opções nesse filtro: Todos; Profissional de Atendimento ao SUS; Profissional de não Atendimento ao SUS

4. Título: Evolução do Número de Profissionais de Saúde em [Nome da Localidade] por Tipo de Unidade: lembrar de tratar a preposição **em** com o artigo adequado do Nome da Localidade, isso já existe na tabela de atributos.

5. Filtro "Nível de Hierarquia": incluir filtro Nível de Hierarquia (niv_hier_2); acrescentar aqui também a opção "Todos" para marcar todos os níveis de hierarquia.

6. Default - O que exibir quando o gráfico abrir : Número de Profissionais; Todos (Disponibilidade para o SUS); Todos (Nível de Hierarquia). Esses devem está marcados quando o gráfico abrir pela primeira vez.

**Comment by eltonfreitas** [comment]
Acrescentar filtro pra tipo de prestador ou tipo de unidade:
![image](https://cloud.githubusercontent.com/assets/6808970/24977988/6bd94fc2-1fa5-11e7-979c-20528cd99a7d.png)

Retirar esses filtros:
![image](https://cloud.githubusercontent.com/assets/6808970/24978143/f306a2e2-1fa5-11e7-88a0-546125ce93fd.png)![image](https://cloud.githubusercontent.com/assets/6808970/24978191/273c8824-1fa6-11e7-96ed-2c1ca3e43b34.png)

**Comment by sauloantuness** [comment]
A variável Tipo de prestador (tp_prest) não existe no Banco de profissionais.
