### ISSUE TITLE
Profissionais por Ocupação - Treemap

### ISSUE THREAD

**Issue by Yasminef** [DataViva/dataviva-site#1500]
![image](https://cloud.githubusercontent.com/assets/19650037/24960285/b0c68850-1f6b-11e7-850e-74b3bef1ae57.png)

http://staging.dataviva.info/pt/location/4mg/health?menu=professionals-occupation-tree_map&url=cnes_professional%2Foccupation_family%2Fprofessionals%3Ffilters%3Dsus_healthcare_professional%26id_ibge%3D31

1.  Exibir no gráfico Ocupações, com dois níveis de agrgação : 1. Familias e 2. Grandes Grupos.

2. Tamanho/Valor: Número de Profissionais.

3. Acrescentar filtro para indicar "Disponibilidade para o SUS" (prof_sus): tem que ter 3 opções nesse filtro: Todos; Atendimento SUS; Não Atendimento SUS

4. Título: Profissionais de Saúde em [Nome da Localidade] por Ocupação : lembrar de tratar a preposição em com o artigo adequado do Nome da Localidade, isso já existe na tabela de atributos.

5. Filtro "Nível de Hierarquia":  incluir filtro Nível de Hierarquia (niv_hier_2); acrescentar aqui também a opção "Todos" para marcar todos os níveis de hierarquia.

6. Default - O que exibir quando o gráfico abrir : Ano mais recente;  Número de Profissionais; Todos (Disponibilidade para o SUS); Todos (Nível de Hierarquia). Esses devem está marcados quando o gráfico abrir pela primeira vez.

**Comment by eltonfreitas** [comment]
O agrupamento não está funcionando corretamente:
![image](https://cloud.githubusercontent.com/assets/6808970/25100918/70af77ce-2388-11e7-8a62-fd030a629724.png)

Dica, ver como está no dataviva:
http://dataviva.info/pt/location/4sp090607/wages?menu=jobs-occupation-tree_map&url=tree_map%2Frais%2F4sp090607%2Fall%2Fall%2Fcbo%2F%3Fcolor%3Dcolor%26depth%3Dcbo_4%26size%3Dnum_jobs
![image](https://cloud.githubusercontent.com/assets/6808970/25100956/a6072dcc-2388-11e7-8b91-9cce5fddb44c.png)
