### ISSUE TITLE
Profissionais por Ocupação - Evolução

### ISSUE THREAD

**Issue by Yasminef** [DataViva/dataviva-site#1501]
![screenshot from 2017-04-12 10-36-05](https://cloud.githubusercontent.com/assets/19650037/24960571/8f7a717e-1f6c-11e7-9a16-2610ece6f115.png)

http://staging.dataviva.info/pt/location/4mg/health?menu=professionals-occupation-stacked&url=cnes_professional%2Foccupation_group%2Fother_hours_worked%3Fvalues%3Dother_hours_worked%2Bhospital_hour%2Bambulatory_hour%26depths%3Doccupation_group%2Boccupation_family%2Bsus_healthcare_professional%2Bhealth_region%26filters%3Dsus_healthcare_professional%2Bhealth_region%26id_ibge%3D31

1.  Exibir no gráfico Ocupações, com dois níveis de agrgação : 1. Familias e 2. Grandes Grupos.

2. Tamanho/Valor: Número de Profissionais.

3. Acrescentar filtro para indicar "Disponibilidade para o SUS" (prof_sus): tem que ter 3 opções nesse filtro: Todos; Atendimento SUS; Não Atendimento SUS

4. Título: Evolução do número de Profissionais de Saúde em [Nome da Localidade] por Ocupação : lembrar de tratar a preposição em com o artigo adequado do Nome da Localidade, isso já existe na tabela de atributos.

5. Filtro "Nível de Hierarquia":  incluir filtro Nível de Hierarquia (niv_hier_2); acrescentar aqui também a opção "Todos" para marcar todos os níveis de hierarquia.

6. Default - O que exibir quando o gráfico abrir : Ano mais recente;  Grandes Grupos(Ocupação), Número de Profissionais; Todos (Disponibilidade para o SUS); Todos (Nível de Hierarquia). Esses devem está marcados quando o gráfico abrir pela primeira vez.

**Comment by eltonfreitas** [comment]
Usar as cores da tabela de atributos attrs_cbo para ocupações.
![image](https://cloud.githubusercontent.com/assets/6808970/25101571/3428f430-238b-11e7-9575-84e7db8a233b.png)

**Comment by luisccf** [comment]
#1500
