### ISSUE TITLE
Gráficos "Bar Chart" não carregam

### ISSUE THREAD

**Issue by FredericoVieira** [DataViva/dataviva-site#1515]
- Location > Tab International Trade:
-- Exports by > Port
-- Imports by > Port
- Location > Tab Wages and Jobs:
-- Job by > Demographic Informations
-- Wage by > Establishments Informations
-Occupation > Tab Wages and Jobs:
-- Job by > Demographic Informations
-- Wage by > Establishments Informations
- Economic Activities > Tab Wages and Jobs:
-- Job by > Demographic Informations
-- Wage by > Establishments Informations
- Product > Tab International Trade:
-- Exports by > Port
-- Imports by > Port
- Trade Partner > Tab International Trade:
-- Exports by > Port
-- Imports by > Port
- Títulos
- Refatorar seguindo os padrões do Treemap: bar.js, bar/views.py...

**Comment by PriscillaOmegatel** [comment]
Os gráficos foram corrigidos. Estamos apenas corrigindo o título de alguns.

**Comment by eltonfreitas** [comment]
Gráficos sem títulos:
![image](https://user-images.githubusercontent.com/6808970/28213816-1ae9b7ec-687e-11e7-9f28-a41db177dbc5.png)
http://staging.dataviva.info/pt/location/4sp090607/trade-partner?menu=exports-port-bar&url=secex%2Fvalue%2Ckg%2Fport%3Ftype%3Dexport%26options%3Dmonth%2Cpercentage%2Csinglecolor%26id_ibge%3D3550308%26subtitle%3Dexporting_municipality

**Comment by eltonfreitas** [comment]
Não carregou o gráfico:
![image](https://user-images.githubusercontent.com/6808970/28213949-ad404930-687e-11e7-94e6-efac09adb8f0.png)
http://staging.dataviva.info/pt/location/4sp090607/wages?menu=jobs-demographic-bar&url=rais%2Fjobs%2Cwage%2Caverage_wage%2Fgender%2Cethnicity%2Cliteracy%3F%26id_ibge%3D3550308

**Comment by eltonfreitas** [comment]
Falta Título!!
![image](https://user-images.githubusercontent.com/6808970/28213989-db9c96a8-687e-11e7-9226-e10f101a48d1.png)
http://staging.dataviva.info/pt/location/4sp090607/wages?menu=wages-demographic-bar&url=rais%2Fwage%2Caverage_wage%2Cjobs%2Fgender%2Cethnicity%2Cliteracy%3F%26id_ibge%3D3550308

**Comment by eltonfreitas** [comment]
Nenhum gráfico de Barras carregou em 
-Occupation > Tab Wages and Jobs:
-- Job by > Demographic Informations
-- Wage by > Establishments Informations

http://staging.dataviva.info/pt/occupation/4110/wages?menu=jobs-demographic-bar&url=rais%2Fjobs%2Fgender%2Cethnicity%2Cliteracy%3Foccupation%3D4110

**Comment by eltonfreitas** [comment]
Também não carrega aqui:
http://staging.dataviva.info/pt/industry/o84116/wages?menu=jobs-demographic-bar&url=rais%2Fjobs%2Cwage%2Caverage_wage%2Fgender%2Cethnicity%2Cliteracy%3Findustry%3Do84116

Economic Activities > Tab Wages and Jobs:
-- Job by > Demographic Informations
-- Wage by > Establishments Informations

**Comment by eltonfreitas** [comment]
Também não:
http://staging.dataviva.info/pt/product/021201/trade-partner?menu=exports-destination-bar&url=secex%2Fvalue%2Ckg%2Fport%3Ftype%3Dexport%26options%3Dsinglecolor%2Cmonth%26product%3D021201%26subtitle%3Dstate_production

**Comment by eltonfreitas** [comment]
Há gráficos de barra que não estão carregando. Esperei mais qu 5 minutos e nada surgiu. Por exemplo, ver esse gráfico abaixo:
http://staging.dataviva.info/pt/location/4sp090607/wages?menu=jobs-establishments-bar&url=rais%2Fjobs%2Cwage%2Caverage_wage%2Cestablishment_count%2Caverage_establishment_size%2Fsimple%2Cestablishment_size%2Clegal_nature%3Fcount%3Destablishment%26id_ibge%3D3550308

**Comment by sauloantuness** [comment]
**[Corrigido] Gráficos sem títulos:**

Localidades Brasileiras > Comércio Internacional > Exportações por > Porto > Bar new API

![screen shot 2017-07-17 at 14 42 01](https://user-images.githubusercontent.com/1711258/28281629-22138dd6-6afe-11e7-8381-24486cb6c2bf.png)

Localidades Brasileiras > Comércio Internacional > Importações por > Porto > Bar new API

![screen shot 2017-07-17 at 14 40 55](https://user-images.githubusercontent.com/1711258/28281586-02a3925c-6afe-11e7-8237-69619fac2108.png)

**Comment by sauloantuness** [comment]
**Não carregou o gráfico**

Localidades Brasileiras > Salário e Emprego > Empregos por > Informações Demográficas > Bar new API

![screen shot 2017-07-17 at 14 47 51](https://user-images.githubusercontent.com/1711258/28281964-27a2ced2-6aff-11e7-8e46-d8cb644661f9.png)

Localidades Brasileiras > Salário e Emprego > Empregos por > Informações dos Estabelecimentos > Bar new API

![screen shot 2017-07-17 at 14 50 52](https://user-images.githubusercontent.com/1711258/28282025-5aa8cd22-6aff-11e7-942d-d9a67646cc18.png)

**Comment by sauloantuness** [comment]
**Falta Título!!**

![screen shot 2017-07-17 at 14 54 38](https://user-images.githubusercontent.com/1711258/28282172-e91f4590-6aff-11e7-8239-c95e9a31592f.png)

**Comment by sauloantuness** [comment]
**Nenhum gráfico de Barras carregou em Occupation ...**

Occupation > Wages and Jobs  > Jobs by > Demographic Informations

![screen shot 2017-07-17 at 15 10 42](https://user-images.githubusercontent.com/1711258/28282798-1f645ae4-6b02-11e7-99e9-efaf2b89d728.png)

Occupation > Wages and Jobs  > Wages by > Establishments Informations

![screen shot 2017-07-17 at 15 11 10](https://user-images.githubusercontent.com/1711258/28282823-30ccab06-6b02-11e7-83e0-7c70825f7d73.png)

**Comment by sauloantuness** [comment]
Economic Activities > Wages and Job > Jobs by > Demographic Informations

![screen shot 2017-07-17 at 15 16 38](https://user-images.githubusercontent.com/1711258/28283068-fa3677ce-6b02-11e7-8c21-88f353271353.png)

Economic Activities > Wages and Job > Wages by > Establishments Informations

![screen shot 2017-07-17 at 15 21 59](https://user-images.githubusercontent.com/1711258/28283277-b34b787c-6b03-11e7-8542-0a4df4deb213.png)

**Comment by sauloantuness** [comment]
@eltonfreitas alguns gráficos podem demorar a carregar pela primeira vez, dado que foi necessário limpar todo o _cache_ da API para atualização de alguns _datasets_.

Talvez o motivo da demora excessiva na sexta-feira foi porque estávamos fazendo o _load_ dos _datasets_ a serem atualizados.

**Comment by eltonfreitas** [comment]
Ok @sauloantuness, neste caso, há como trocar aquele símbolo que indica que o gráfico está carregando. Devida a demora, o usuário pode ter a sensação de que o gráfico não irá carregar. Se substituíssemos aquela engrenagem por uma contagem de 0 a 100%. Assim o usuário poderá perceber que a coisa está avançando.

**Comment by sauloantuness** [comment]
@eltonfreitas a idéia da barra de progresso pode ser uma boa solução. Adicionei a barra de progresso na parte superior dos gráficos, seguindo os mesmos padrões da barra presente no site.

**Comment by eltonfreitas** [comment]
@sauloantuness nesse gráfico tem uma opção de escolher natureza jurídica, mas não está aparecendo aqui, mas no Localidade e no Industry está.
http://staging.dataviva.info/pt/occupation/4110/wages?menu=wages-establishments-bar&url=rais%2Fwage%2Caverage_wage%2Fsimple%2Cestablishment_size%3Foccupation%3D4110
![image](https://user-images.githubusercontent.com/6808970/28384386-f1123bc6-6c9a-11e7-88e6-b8c2a0ac528b.png)
