### ISSUE TITLE
Aplicar "Geo Map - New API" nas demais categorias

### ISSUE THREAD

**Issue by FredericoVieira** [DataViva/dataviva-site#1516]
Exemplo: [Product > Imports > GeoMap](http://localhost:5000/en/product/021201/trade-partner?menu=imports-municipality-geo_map&url=geo_map%2Fsecex%2Fall%2F021201%2Fall%2Fbra%2F%3Fcolor%3Dimport_val)

*Verificar utilização nas demais categorias.

**Comment by FredericoVieira** [comment]
Faltou o novo gráfico map nas seguintes categorias:
- Trade Partner > Exports by > Municipality
- Trade Partner > Imports by > Municipality
- Higher Education > Enrollments by > Municipalitiy
- Basic Course > Enrollments by > Municipalitiy

**Comment by PriscillaOmegatel** [comment]
Os gráficos foram corrigidos. Falta apenas corrigir os títulos de alguns.
