### ISSUE TITLE
Staging - Perfil de Ocupações

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#1519]
Os dados novos que já haviam sido incluídos, não estão carregando no staging no perfil de ocupações.
http://staging.dataviva.info/en/occupation/4110/wages?menu=jobs-demographic-bar&url=rais%2Fjobs%2Fgender%2Cethnicity%2Cliteracy%3Foccupation%3D4110

**Comment by FredericoVieira** [comment]
Problema relatado em #1515
