### ISSUE TITLE
Staging - Perfil de indústrias

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#1520]
Problema similar, não está carregando os novos dados que já haviam sido incluídos.

http://staging.dataviva.info/en/industry/o84116/wages?menu=jobs-demographic-bar&url=rais%2Fjobs%2Cwage%2Caverage_wage%2Fgender%2Cethnicity%2Cliteracy%3Findustry%3Do84116

**Comment by FredericoVieira** [comment]
Caso relatado em outro perfil, favor verificar #1515
