### ISSUE TITLE
Aplicar novo gráfico de barras na categoria "Industry"

### ISSUE THREAD

**Issue by FredericoVieira** [DataViva/dataviva-site#1525]
Gráfico de barras no modelo novo deve ser inserido em:
- Industry > Wages by > Distribution

**Comment by eltonfreitas** [comment]
@sauloantuness essa issue é para aplicar o novo código usado para construir o gráfico de barras na nova api. Para não ter que usar mais recursos do dv antigo.

Caso então não der para fazer a leitura com os novos dados, sugiro excluir esse gráfico então.

http://staging.dataviva.info/en/industry/o84116/wages?menu=wages-distribution-bar&url=bar%2Frais%2Fall%2Fo84116%2Fall%2Fcnae%2F

![image](https://user-images.githubusercontent.com/6808970/28084060-e2c71648-664d-11e7-9818-1867478acbc6.png)

**Comment by eltonfreitas** [comment]
Falta retirar do site.
