### ISSUE TITLE
Atualizar base de Censo Escolar no Redshift

### ISSUE THREAD

**Issue by FredericoVieira** [DataViva/dataviva-site#1527]

**Comment by eltonfreitas** [comment]
Essa Issue não está completa:

**Dependência administrativa e Escolas não foram atualizadas para a nova API.**
![image](https://user-images.githubusercontent.com/6808970/28213103-ff33bc62-687a-11e7-805b-89fb8f7378bd.png)
http://staging.dataviva.info/en/location/4sp090607/education?menu=new-api-basic-education-level-tree_map&url=sc%2Fsc_course%2Fstudents%3Fsizes%3Dstudents%26colors%3Dstudents%2Baverage_age%26sc_course_field%3Dxx%26nuances%3Dsinglecolor%26id_ibge%3D3550308

**Retirar da caixa de seleção os cursos que não existem mais (ex. 1ª série do fundamental, etc.)**
![image](https://user-images.githubusercontent.com/6808970/28213175-49050346-687b-11e7-9586-5e2329bd38b2.png)

**Dados não foram atualizados para 2016**
![image](https://user-images.githubusercontent.com/6808970/28213290-cb3834a0-687b-11e7-8a75-b679551cad27.png)
http://staging.dataviva.info/en/basic_course/01006/enrollments?menu=enrollments-municipality-tree_map&url=sc%2Fmunicipality%2Fstudents%3Fsizes%3Dstudents%26colors%3Dstudents%2Baverage_age%26basic_course%3D01006

**Escolas não usam a nova API**
http://staging.dataviva.info/en/basic_course/01006/enrollments?menu=enrollments-school-tree_map&url=tree_map%2Fsc%2Fall%2Fall%2F01006%2Fschool%2F%3Fcolor%3Dcolor%26depth%3Dschool_8%26size%3Denrolled

**Comment by eltonfreitas** [comment]
Também não atualizado. Checar esses box que estão desatualizados.
![image](https://user-images.githubusercontent.com/6808970/28213522-ca51de50-687c-11e7-96c0-eb48c4009336.png)
