### ISSUE TITLE
Atualizar base do Datasus no Redshift

### ISSUE THREAD

**Issue by FredericoVieira** [DataViva/dataviva-site#1528]

**Comment by eltonfreitas** [comment]
@sauloantuness os dados de 2016 ainda estão sendo trabalhados e não foram concluídos a tempo, sendo assim, pode apagar do redshift o que for referente a 2016. O que tem que ser feito é atualizar o banco de dados do Datasus de 2008 a 2015 utilizando os arquivos que estão como STEP4 no ETL.

Algumas variáveis mudaram de nome depois que esse tratamento foi realizado, os novos nomes a serem utilizados são:
retencao_2
niv_hier_2
tp_unid2
tp_prest2

Passar a considerar essas variáveis.
![image](https://user-images.githubusercontent.com/6808970/28081585-24c1e80a-6646-11e7-9f41-3c225755b549.png)

**Comment by leandrocollares** [comment]
@eltonfreitas, @sauloantuness: se possível for, sugiro remover a palavra **Mil** dos rótulos do eixo y e modificar o título de eixo mencionado para **estabelecimentos (em milhares)**.
