### ISSUE TITLE
Atualizar "Ajuda - Tipos de Gráfico" com descrição do gráfico de barras horizontais

### ISSUE THREAD

**Issue by FredericoVieira** [DataViva/dataviva-site#1530]
O menu "Gráfico de Barras" conterá  a descrição e o link dos dois tipos de gráficos de barras.

**Comment by sauloantuness** [comment]
Os links dos gráficos nas descrições da página **Ajuda - Tipos de Gráfico** levam para a página de **Construa gráficos** onde a utilização da nova API não está disponível.
