### ISSUE TITLE
Atualizar "Ajuda - Glossário" com termos relativos ao Datasus

### ISSUE THREAD

**Issue by FredericoVieira** [DataViva/dataviva-site#1531]

**Comment by Yasminef** [comment]
[Fonte de dados - DATASUS.docx](https://github.com/DataViva/dataviva-site/files/1029726/Fonte.de.dados.-.DATASUS.docx)

**Comment by eltonfreitas** [comment]
Quantidade Existente (Equipamentos) – Corresponde a quantidade de equipamentos existentes na Localidade

Quantidade em Uso (Equipamentos) – Corresponde a quantidade de equipamentos existentes que estão em uso pela localidade. 

Disponibilidade para o SUS– Indica se o equipamento/ estabelecimento está disponível para o uso do SUS na localidade. 

Nível de Hierarquia – 
01--PAB-PABA--Estabelecimento de Saúde ambulatorial que realiza somente Procedimentos de Atenção Básica –PAB e ou Procedimentos de Atenção Básica Ampliada definidos pela NOAS 
02--Media - M1--Estabelecimento de Saúde ambulatorial que realiza procedimentos de Média Complexidade definidos pela NOAS como de 1ºnível de referência – M1 
03--Media - M2 e M3--Estabelecimento de Saúde ambulatorial que realiza procedimentos de Média Complexidade definidos pela NOAS como de 2º nível de referência - M2.e /ou de 3º nível de referência – M3
04--Alta AMB--Estabelecimento de Saúde ambulatorial capacitado a realizar procedimentos de Alta Complexidade definidos pelo Ministério da Saúde.
05--Baixa - M1 e M2--Estabelecimento de Saúde que realiza além dos procedimentos previstos nos de níveis de hierarquia 01 e 02, efetua primeiro atendimento hospitalar, em pediatria e clínica médica, partos e outros procedimentos hospitalares de menor complexidade em clínica médica, cirúrgica, pediatria e ginecologia/obstetrícia
06--Media - M2 e M3--Estabelecimento de Saúde que realiza procedimentos previstos nos de níveis de hierarquia 02 e 03, além de procedimentos hospitalares de média complexidade. Por definição enquadram-se neste nível os hospitais especializados 
07--Media - M3--Estabelecimento de Saúde que realiza procedimentos hospitalares de média complexidade. Realiza procedimentos previstos nos estabelecimentos de níveis de hierarquia 02 e 03, abrangendo SADT ambulatorial de alta complexidade 
08--Alta HOSP/AMB--Estabelecimento de Saúde que realiza procedimentos de alta complexidade no âmbito hospitalar e ou ambulatorial 
Nível de atenção – Indica se o estabelecimento presta atendimento ambulatorial, atendimento hospitalar ou atendimento ambulatorial e hospitalar

Tipo de Prestador – Tipo de prestador de serviço (público, privado, filantrópico, sindicato).

**Comment by eltonfreitas** [comment]
Existing Quantity (Equipment) - Corresponds to the quantity of existing equipment in the locality.
Quantity in Use (Equipment) - Corresponds to the amount of existing equipment that is in use by the locality.
SUS availability - Indicates if the equipment/establishment is available for SUS use in the locality.
Hierarchy Level –

01 - PAB-PABA – Outpatient Health Establishment that only performs Basic Attention Procedures – PAB and/or Extended Basic Attention Procedures defined by NOAS 
02 - Medium - M1 - Outpatient Health Establishment that performs procedures of Medium Complexity defined by NOAS as level 1 reference - M1 
03 - Medium - M2 and M3 - Ambulatory Health Establishment that performs Medium Complexity procedures defined by NOAS as level 2 reference - M2. and/or level 3 reference - M3
04 - High AMB - Outpatient Health Establishment qualified to perform High Complexity procedures defined by the Ministry of Health.
05 - Low - M1 and M2 - Health Establishment that in addition to the procedures foreseen in hierarchy levels 01 and 02 performs first hospital care in pediatrics and medical clinics, child-birth and other hospital procedures of lesser complexity in medical clinic, surgical, pediatrics and gynecology/obstetrics.
06 - Medium - M2 and M3 - Health Establishment that performs procedures foreseen in hierarchy levels 02 and 03, in addition to hospital procedures of medium complexity. By definition, specialized hospitals are placed in this hierarchy level. 
07 - Medium - M3 - Health Establishment that performs hospital procedures of medium complexity. It performs procedures foreseen in the establishments of hierarchy levels 02 and 03, covering ambulatory SADT of high complexity. 
08 - High HOSP/AMB - Health Establishment that performs procedures of high complexity in hospital or outpatient care.

Level of care - Indicates whether the establishment provides outpatient care, hospital care or outpatient and hospital care.

Provider type - Type of service provider (public, private, philanthropic, trade union).
