### ISSUE TITLE
Atualizar documentação da nova API

### ISSUE THREAD

**Issue by FredericoVieira** [DataViva/dataviva-site#1533]
Atualizar documentação no repositório da nova API, esclarecendo sua forma de uso.
Incluir tabelas de referência para as variáveis que podem ser utilizadas.
Tomar como exemplo a documentação da versão antiga: https://github.com/DataViva/dataviva-site/wiki/Api

**Comment by sauloantuness** [comment]
https://github.com/DataViva/dataviva-api/wiki/documentation
