### ISSUE TITLE
Atualizar "Ajuda - Classificações" com novas tabelas e variáveis

### ISSUE THREAD

**Issue by FredericoVieira** [DataViva/dataviva-site#1534]
Atualizar:
- Localidades Brasileiras:
-- Novo Seletor: Regiões de Saúde

![1](https://cloud.githubusercontent.com/assets/8905198/26419963/b7ae7cac-4097-11e7-92d7-93e01f21ec85.png)

Incluir:
- Informações Demográficas:
-- Seletores: Escolaridade, Etnia, Sexo

- Informações de Estabelecimento:
-- Seletores: Natureza Jurídica, Simples, Tamanho do Estabelecimento

- Porto
-- Não possui seletor

- Datasus
-- Seletores: Tipo de Equipamento, Equipamento, Nível de Atenção, Nível de Hierarquia, Tipo de Estabelecimento, Tipo de Leito, Tipo de Unidade

**Comment by eltonfreitas** [comment]
@sauloantuness alguns nomes estão em inglês quando português está selecionado.
![image](https://user-images.githubusercontent.com/6808970/28081696-7de2ff28-6646-11e7-8276-2827192247de.png)
