### ISSUE TITLE
Incluir Texto na Página Inicial do Dataviva para indicar quais as mudanças que estão sendo incluídas nessa nova versão.

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#1553]
Texto:
**Nova versão - novos dados e novos gráficos**

A nova versão do DataViva traz como principal novidade a inclusão de dados de saúde fornecidos pelo DATASUS. O DataViva apresenta informações anuais dos estabelecimentos de saúde brasileiros, de 2008 a 2015. As principais variáveis são: estabelecimentos de saúde, equipamentos, leitos e profissionais. Você poderá encontrar esses dados navegando nos perfis das Localidades.

Novos dados foram incluídos:
 - Comércio internacional: porto;
 - Emprego formal e estabelecimentos: informações dos trabalhadores (sexo, grau de escolaridade, etnia) e informações das empresas (tamanho, simples e natureza jurídica).

A plataforma conta agora com nova API (**ATENÇÃO LUIS OU SAULO - linkar: https://github.com/DataViva/dataviva-api/wiki/documentation**).

**Comment by PriscillaOmegatel** [comment]
@sauloantuness segue a versão do texto em inglês:

New version - New data and new graphics
The new version of DataViva brings as a main novelty the inclusion of health data provided by DATASUS. DataViva presents annual information from Brazilian health establishments from 2008 to 2015. The main variables are: health facilities/establishments, equipment, beds and professionals. You can find this data by browsing the profiles of the Locations.
 
New data were included:
 
International trade: port;
Formal employment and establishments: workers' information (sex, educational level, ethnicity) and company information (size, simple and legal nature).
The platform now has a new API.

**Comment by luizalages** [comment]
Atualizar o texto em inglês:

New version - New data and graphics

DataViva has a new version. As highlight, health data is now available on the platform, provided by DATASUS. DataViva presents annual infformation from Brazilian health facilities from 2008 to 2015. The main variables are: health facilities, health equipment, hospital beds and health professionals. You can find this data by browsing the locations profiles.

New data was included:
• International trade: port;
• Formal employment and establishments: workers' information (sex, educational level and ethnicity) and company information (size, Simple - a differentiated tax regime - and legal nature).

The platform has a new API.

**Comment by sauloantuness** [comment]
Atualizado.
