### ISSUE TITLE
Informações sobre Educação indisponíveis. Nenhuma visualização é construída.

### ISSUE THREAD

**Issue by leandrocollares** [DataViva/dataviva-site#1564]
Informações sobre Educação não estão disponíveis. Nenhuma visualização é construída.

Para reproduzir o problema, navegue na plataforma conforme indicado:

Explore nossos bancos de dados -> Localidades Brasileiras -> Duque de Caxias -> Educação

Alguns dos erros exibidos pelo console do browser:

`GET http://api.staging.dataviva.info/cnes_equipment/year/?year=2015&municipality=3301702 500 (Internal Server Error)`

`GET http://api.staging.dataviva.info/cnes_professional/year/?year=2015&municipality=3301702 500 (Internal Server Error)`

`GET http://api.staging.dataviva.info/secex/product/?type=export&year=2016&order=value&direction=desc&limit=1&municipality=3301702 500 (Internal Server Error)`

`GET http://api.staging.dataviva.info/secex/product/?type=import&year=2016&order=value&direction=desc&limit=1&municipality=3301702 500 (Internal Server Error)`

![issue6](https://user-images.githubusercontent.com/5790932/34560059-79fc22f2-f12b-11e7-88f4-ee7ee00e93b7.png)
![issue7](https://user-images.githubusercontent.com/5790932/34560060-7a1729bc-f12b-11e7-886d-2a0c8f928157.png)

**Comment by leandrocollares** [comment]
Após limpeza do cache do Redis e carregamento dos metadados, apenas as duas visualizações não são construídas:

- treemap: educação profissional por escola;

- treemap: educação básica por dependência administrativa.

**Comment by litodaldegan** [comment]
Problema corrigido com atualização na API (dataviva-api). O arquivo com os nomes das escolas não estava sendo retornado. Issue relativo ao problema: https://github.com/DataViva/dataviva-api/issues/45
