### ISSUE TITLE
Construa gráficos - api antiga

### ISSUE THREAD

**Issue by luizalages** [DataViva/dataviva-site#1571]
A opção de construir gráficos ainda puxa os dados da API antiga, o que significa que não trabalha com as novas variáveis, com a base de dados de saúde e nem com dados atualizados. Isso gera inconsistências graves em relação a outras áreas de pesquisa do site (números e visualizações destoam).

**Comment by litodaldegan** [comment]
Deve ser desdobrada em novas tarefa com a criação de um componente Vue.js.
