### ISSUE TITLE
Disponibilizar dados do ensino básico para produção

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-site#1586]

**Comment by msbandrade** [comment]
Os dados do ensino básico não está carregando, nem no staging nem no site...

![dados educacao](https://user-images.githubusercontent.com/20859423/41297220-12a8e540-6e35-11e8-9f2f-4b156e367f20.png)

**Comment by litodaldegan** [comment]
Flag que define se os dados devem ser exibida em produção atualizada para todos os registros do ensino básico do ano de 2017 (36.480.908 registros) no Redshift.

Query correspondente da atualização dos dados (Run time: 6m 7.17s):
update "public"."sc" set hidden=false where hidden is NULL and year=2017; 

Em seguida, os dados de cache para ensino básico foram removidas do Redis. Segue o comando que foi utilizado para remover estes dados:
redis-cli -h <redis_host> -n <api_production_db> keys "apidataset:/sc/year/*" | xargs redis-cli -h <redis_host> -n <api_production_db> DEL

Dados de 2017 já estão disponíveis no ambiente de produção:
![ensino_basico](https://user-images.githubusercontent.com/8508808/41675846-312b837c-749a-11e8-96e9-b361cded2582.png)
