### ISSUE TITLE
Disponibilizar dados de ensino superior em produção

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-site#1587]

**Comment by msbandrade** [comment]
Pessoal, chequei os dados no staging e a princípio parece ok, embora o arrendondamento do site está sobre estimando consideravelmente o número de matrículas para todos os anos. Me parece que o arrendondamento no banco da RAIS está melhor. Existe a possibilidade dos critérios de arredondamento serem diferentes para cada base de dados?

**Comment by litodaldegan** [comment]
Flag que define se os dados devem ser exibida em produção atualizada para todos os registros do ensino superior do ano de 2016 (8.048.701 registros) no Redshift.

Query correspondente da atualização dos dados (Run time: 1m 48.99s ):
update hedu set hidden = false where hidden = true and year = 2016;

Em seguida, os dados de cache para ensino superior foram removidas do Redis. Segue o comando que foi utilizado para remover estes dados:
redis-cli -h <redis_host> -n <api_production_db> keys "apidataset:/hedu*" | xargs redis-cli -h <redis_host> -n <api_production_db> DEL

Dados de 2016 já estão disponíveis no ambiente de produção:
![ensino_superior](https://user-images.githubusercontent.com/8508808/41676780-e3640d32-749c-11e8-9f47-360dea571fdd.png)
