### ISSUE TITLE
Definir grupos de segurança para uso de recursos na AWS

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-site#1588]

**Comment by litodaldegan** [comment]
Grupos de segurança criados de acordo com os recursos usados. Seguem os grupos definidos:
MySQL, Redis, Redshfit, Site, API.

**Comment by litodaldegan** [comment]
Refazer os grupos de segurança focando nos ambientes em que os recursos são utilizados.
Importante definir um grupo de segurança separado para o LoadBalance e acesso remotos via SSH.

**Comment by litodaldegan** [comment]
Grupos de segurança alterados para o novo modelo.
Diagrama detalhando os grupos adicionado ao Drive em Documentação/AWS/Grupos de seguranca

**Comment by diogolundberg** [comment]
Queremos manter apenas os grupos:
* default

* load-balance (acesso externo 80 e acesso interno dos grupos abaixo)

* api-production (acesso apenas interno)
* api-staging (acesso apenas interno)
* site (production) (acesso apenas interno e 80)
* site (staging) (acesso apenas interno e 80)

* legacy (mesma coisa)

* mysql (somente o protocolo relactionado)
* redshift (somente o protocolo relactionado)
* ssh (somente o protocolo relactionado)
* rdp (somente o protocolo relactionado)

**Comment by litodaldegan** [comment]
Para o load-balance, quando você diz "grupos abaixo" você se refere aos:

**Comment by diogolundberg** [comment]
Só os de api e site mesmo.

Grupos internos porque estes não deveriam ter nenhum acesso externo liberado.

**Comment by litodaldegan** [comment]
Ótimo, obrigado.
Deste modo, acredito que os grupos de segurança já estão de acordo com o esperado.
Deixei a porta 80 do grupo do site e da api temporariamente abertas para externo até começarmos a fazer uso do load balance.

**Comment by litodaldegan** [comment]
Diagrama detalhando os grupos atualizado, disponível no Drive em _Documentação/AWS/Grupos de seguranca_
