### ISSUE TITLE
Visualização que mostrar os dados ensino básico por dependência administrativa a nível de Brasil apresentando problema para carregar

### ISSUE THREAD

**Issue by rafaelsmedina** [DataViva/dataviva-site#1591]
![image](https://user-images.githubusercontent.com/20420466/41313293-f592e14c-6e5f-11e8-9f98-26e8844e5fc7.png)

**Comment by rafaelsmedina** [comment]
Tanto no staging, quanto no site.

**Comment by litodaldegan** [comment]
Foi identificado que a quantidade de dados necessários para a construção da visualização está causando erro de time-out na API.
A solução do problema se encontra na tarefa DataViva/dataviva-api#90

**Comment by rafaelsmedina** [comment]
Após alterar o timeout da API, é possível baixar dados de requisições muito grandes/demoradas. 

Porém, o gráfico mencionado nesta issue ainda demora bastante para ser construído, chegando a travar a página.

![erro_espera_construcao_visu](https://user-images.githubusercontent.com/20420466/41857792-b35a8320-786e-11e8-8e78-29448730cbd3.png)

A visualização eventualmente abre. Porém, ao tentar trocar a profundidade para escolas, a página acaba dando erro.

![demora_opcoes](https://user-images.githubusercontent.com/20420466/41858166-903d57b8-786f-11e8-8790-49a1444208f2.png)

![crash](https://user-images.githubusercontent.com/20420466/41858184-99ea96cc-786f-11e8-8c25-9eea01bc7a55.png)

Seria interessante repensar essa visualização.
