### ISSUE TITLE
Cidades que não possuem universidades não mostram aba de educação

### ISSUE THREAD

**Issue by rafaelsmedina** [DataViva/dataviva-site#1599]
Mesmo que possuam escolas de ensino básico.

**Comment by rafaelsmedina** [comment]
Ao abrir uma cidade que não possui ensino superior, como Confins - MG (http://dataviva.info/en/location/4mg030004), a aba de educação não aparece, mesmo a cidade possuindo ensino básico.

**Comment by litodaldegan** [comment]
Closed by https://github.com/DataViva/dataviva-site/issues/1596
