### ISSUE TITLE
Remover logos governamentais do DataViva Legacy

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-site#1602]
Assim como na #1601, para que o site _legacy_ esteja de encontro com as normal do período eleitoral, as logos governamentais localizadas no footer da página deverão ser removida.

A alteração deve ser realizada em uma branch alternativa para que possa ser revertida no termino do período.

**Comment by rafaelsmedina** [comment]
O codigo foi modificado na máquina do legacy.
