### ISSUE TITLE
Verificar metadado de atividade econômica Agropecuária

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-site#1603]
Na visualização _Treemap_ para atividade econômica, os dados de Agropecuário estão sendo exibidos com o texto "Confidential". Para reproduzir o problema, basta acessa [Empregos - Brasil](http://dataviva.info/pt/location/all/wages) e mudar o modo de agregação da visualização para "Divisão".
Na legenda os nome está sendo exibido corretamente "Agropecuária".

Segue uma imagem do problema encontrado.
![confidential](https://user-images.githubusercontent.com/8508808/42220232-be7bd916-7ea4-11e8-8134-fdb7809067f2.png)

Este erro está presente em qualquer nível de localidade que tenha dados de atividade econômica.

**Comment by rafaelsmedina** [comment]
O problema estava no metadado envolvido.
