### ISSUE TITLE
Dados errados?

### ISSUE THREAD

**Issue by Falnesio** [DataViva/dataviva-site#1607]
### 2016 tá errado

![image](https://user-images.githubusercontent.com/36005374/42392536-959618d6-8129-11e8-9303-fb6185bb554c.png)

http://www.dataviva.info/pt/build_graph/secex/all/all/all?view=Import%20Origins/Export%20Destinations&graph=stacked

**Comment by msbandrade** [comment]
Prezado Falnesio, 

Primeiramente, obrigado pela mensagem.

Nesta seção do site, os dados para 2016 registram os números somente até março, por isso a quebra tão grande na série. Favor realizar a consulta por meio da página principal. Selecione o banco 'Localidades Brasileiras' -> 'Brasil´ -> 'Comércio Internacional´ e explore os gráficos. Em breve atualizaremos os dados para 2017. 

Abraços. 
Equipe DataViva.
