### ISSUE TITLE
Transferir static files do repositório para o s3

### ISSUE THREAD

**Issue by diogolundberg** [DataViva/dataviva-site#1613]

**Comment by litodaldegan** [comment]
## [Static](https://github.com/DataViva/dataviva-site/tree/staging/dataviva/static)

Após analisar os arquivos estáticos presentes no repositório, o espaço ocupado por eles e as mudanças necessárias de serem realizados no código, foram feitas as seguintes modificações:

Bibliotecas e plugins externos movidos para o S3 (arquivos JS e CSS), diretórios correspondentes:
```
dataviva/static/js/libs
dataviva/static/js/plugins
dataviva/static/css/plugins
dataviva/static/css/libs
```
Os arquivos (JS, CSS) internos do projeto foram mantidos no repositório.

Foram identificados alguns arquivos que não eram usados pela aplicações e por isso foram removidos do repositório, arquivos correspondentes:
```
dataviva/static/help/*
dataviva/static/pdf/*
dataviva/static/crosswalks/*
dataviva/static/img/help/*
dataviva/static/img/sabrina/*
dataviva/static/img/home/*
dataviva/static/img/computer/*
dataviva/static/img/blog/*
dataviva/static/img/ask/*
dataviva/static/img/news/*
dataviva/static/css/modules/embed/styles.sabrina.css
```
Alguns arquivos estáticos foram mantidos no repositório pelos seguintes motivos:

- _dataviva/static/json_: é interessante que estes dados sejam fornecidos pela API, uma vez que são independentes do site e são dados relativos à construção de visualizações (_rings_, _network_, _map_). Desta forma, é sugerido que a API seja modificada de modo a responder com estes arquivos.

- _dataviva/static/img_: muitas imagens são referenciadas em arquivos CSS o que dificulta o uso de uma URL dinâmica. Mover os arquivos CSS correspondentes para o S3, o que poderia resolver a questão, também não é interessante em questão de controle do código. Também foi avaliado que estes arquivos não representam um uso muito alto de espaço de armazenamento. 

### CORS

Foi necessário a configuração de CORS para o bucket correspondente a cada um dos ambientes de forma a permitir que os arquivos estáticos sejam buscado do S3.
Desta forma, foram realizadas as seguintes configuração para o bucket de cada ambiente:

#### dataviva-site-production
```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>http://dataviva.info</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

#### dataviva-site-staging

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>http://staging.dataviva.info</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
<CORSRule>
    <AllowedOrigin>http://localhost:5000</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

**Comment by litodaldegan** [comment]
@diogolundberg favor verificar se concorda, principalmente em relação ao diretório de imagens (_dataviva/static/img_). Foram removidos alguns vídeos e imagens que não são utilizados. Conteúdo que restou neste diretório, tem no total 6,5MB.
