### ISSUE TITLE
Stacked breaks with HS 084103

### ISSUE THREAD

**Issue by mariohmol** [DataViva/dataviva-site#162]
For some reason when open stack chart with 4103 product it breaks

http://dataviva.info/apps/builder/stacked/secex/mg/084103/all/wld/?sort=color&layout=value&controls=true&depth=wld_2&value_var=val_usd&order=asc

The error message is:
TypeError: a[(i + 1)] is undefined d3plus.js:4082

**Comment by davelandry** [comment]
Confirmed fixed.
