### ISSUE TITLE
Mecanismo de tradução em componente Vue

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-site#1623]
Pesquisar por um solução de tradução de textos e datas para componentes Vue.
Instalar a melhor opção encontrada no projeto e documentar a forma de uso do mecanismo de tradução.
Importante adicionar a biblioteca ao arquivo de dependências.
Também é importante verificar a possibilidade de reutilização dos dados de tradução já presente no front-end do projeto (dados armazenados em dataviva.dictionary).

**Comment by leandrocollares** [comment]
O _plugin_ [vue-i18n.js](https://kazupon.github.io/vue-i18n/) foi avaliado. Ele permite gerar versões em múltiplos idiomas, e também lida com plurais e formatos de números e datas.

O arquivo de idiomas, que contém traduções e formatos de datas e números, pode ter o seguinte formato:

```
en = {
    "message": {
          "hello": "hello world",
	  "apple": "apple | apples",
	  "banana": "no bananas | one banana | {count} bananas"
    },
    "dateTimeFormat": {
          "short": {
             "year": "numeric",
             "month": "short",
             "day": "numeric"
          },
          "long": {
             "year": "numeric",
             "month": "long",
             "day": "numeric",
             "weekday": "short",
             "hour": "numeric",
             "minute": "numeric",
             "hour12": true
          },
    },   
   "numberFormat": {
          "currency": {
             "style": "currency", 
             "currency": "USD",
          },
          "percent": {
             "style": "percent"
          }
    }
}
```

No componente Vue, um seletor de idiomas e exemplos de como formatar dados de acordo com os arquivos de idiomas são mostrados abaixo:

```<template>
  <div>
    Language selector
    <div id="lang">
      <ul class="list-inline">
        <li><button @click="set_lang('en')">English</button></li>
        <li><button @click="set_lang('pt')">Português</button></li>
      </ul>
    </div>
    <p>{{ $t("message.hello") }}</p>
    <p>{{ $d(new Date(), "short") }}</p>
    <p>{{ $d(new Date(), "long") }}</p>
    <p>{{ $n(100, "currency") }}</p>
    <p>{{ $tc("message.apple", 2) }}</p>
    <p>{{ $tc('message.banana', 10, { count: 10 }) }}</p>
  </div>
</template>
```

**Comment by litodaldegan** [comment]
Para gerência o processo de tradução, seria interessante usar algum sistema como o [lokalise](https://lokalise.co), que fornece uma interface bem mais amigável e facilita na organização das _strings_ a serem traduzidas.

Para obter a _strings_ a serem traduzidas a partir do código fonte (automatizar este processo) não foi possível identificar uma biblioteca que seja relacionada ao plugin _vue-i18n_. Deste modo, deve ser avaliado a criação de um _script_ que percorre os arquivos e obtém as _strings_ para tradução.

Também para facilitar o processo de tradução, as mensagens a serem traduzidas devem ser colocadas em arquivo separado das configurações de data e número. Desta forma este arquivo pode ser facilmente importado para programas de controle de tradução. Segue o exemplo de formato que o arquivo de mensagens deve atender:

```
{
          "hello": "hello world",
	  "apple": "apple | apples",
	  "banana": "no bananas | one banana | {count} bananas"
}
```

Obs. de preferência não usar vírgula depois da última linha (evita problema de leitura por alguns programas de tradução) e manter o arquivo sempre ordenado.
