### ISSUE TITLE
Atualizar links de visualizações para 2017

### ISSUE THREAD

**Issue by rafaelsmedina** [DataViva/dataviva-site#1624]

**Comment by litodaldegan** [comment]
Link com ano fixo para visualizações Treemap que fazem uso de dados da SECEX foram atualizado para o ano de 2017 e colocado no ambiente de produção.
![treemap](https://user-images.githubusercontent.com/8508808/44094422-804c6fba-9fac-11e8-9346-8c665b205e03.png)
