### ISSUE TITLE
Usar ID IBGE ao invés do ID atual de localidade

### ISSUE THREAD

**Issue by rafaelsmedina** [DataViva/dataviva-site#1628]
Atualmente no Dataviva é utilizado um id específico para cada localidade. 

Devemos trocar esse valor pelo ID real (vindo do IBGE), que já é utilizado nos modais (visto na figura, IBGE ID), mas ainda não é utilizado nos links, como no link para a [página da cidade de São Paulo](dataviva.info/en/location/4sp090607).

![desenho sem titulo 2](https://user-images.githubusercontent.com/20420466/43963255-2e088d16-9c90-11e8-972b-b14cc7d716bd.png)

**Comment by litodaldegan** [comment]
Alteração abortado por déficit técnico. Foi criada com objetivo de usar os ID corretos no novo modal seletor. Como solução, o modal seletor usar os IDs antigos para navegação.
