### ISSUE TITLE
New App Builder w/ Build Button

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#163]
Atualmente, o usuário precisa fazer vários passos E ESPERAR VÁRIAS VISUALIZAÇÕES CARREGAREM, para chegar onde realmente quer.

Exemplo:
http://dataviva.info/apps/builder/compare/secex/mg_rj/all/aschn/hs/?controls=true&year=2012&value_var=val_usd&depth=hs_2&color_var=color&axes=val_usd&scale=log

Se quero comparar as exportações de São Paulo e Paraná para o Japão, preciso:

1) entrar no Compare
2) ESPERAR CARREGAR
3) alterar a visualização
4) ESPERAR CARREGAR
5) mudar Minas para SP
6) ESPERAR CARREGAR
7) mudar Rio para PR
8) ESPERAR CARREGAR
9) mudar China para Japão
10) ESPERAR CARREGAR

Só então tenho a visualização que queria.

Se criarmos um botão de "Construir", que solicita as variáveis que desejo antes de carregar qualquer coisa, o tempo de acesso ao dado desejado será reduzido em CINCO vezes. Ou seja, ao abrir um aplicativo, o mesmo deveria apresentar inicialmente os Menus necessários ("alterar visualização" e escolher localidade, produto, atividade, etc.) para depois carregar a visualização desejada.

Será que isto facilita para o usuário em termos de saber o que a visualização pode mostrar? Talvez o primeiro carregamento de uma visualização ainda seja importante como exemplo.

**Comment by davelandry** [comment]
Present in the new platform.
