### ISSUE TITLE
Paleta de cores itens modal

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-site#1637]
O modal atual do DataViva apresenta um esquema de cores que define a cor do ícone (quando não é imagem) e uma cor de título do item. Como no exemplo da imagem abaixo:
![ocup](https://user-images.githubusercontent.com/8508808/44526830-8e391180-a6bb-11e8-81b1-aa894200b33e.png)

Para todas as bases de dados esta cor é dada pelo nível de agregação mais alto do dado (no exemplo acima o nível mais alto é "Grande Grupos"). Com exceção dos dados de universidade, por apresentarem somente um nível, a cor e dada de acordo com a propriedade "_school_type_" da seguinte forma:

| Tipo de escola (_school type_) | Cor |
| - | - |
| T | azul claro |
| S | azul escure |
| Q | verdade claro |
| P | verde escure |

Deste modo, para o novo modal sendo criado (que faz uso do metadados retornados pela API), deverá ser definido uma paleta de cores para cada uma das bases de acordo com suas propriedades. Cada cor deverá ter como chave a propriedade do nível de agregação mais alto para que seja facilmente localizada. Esta paleta de cores deverá ser adicionada ao arquivo de configurações do modal.

**Comment by litodaldegan** [comment]
As cores usadas atualmente podem ser encontradas no banco de dados nas tabelas de atributos de cada bases.

**Comment by leandrocollares** [comment]
Questão resolvida via b38d8dd.
