### ISSUE TITLE
Lógica para filtragem de itens do modal

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-site#1639]
Como o novo modal faz uso dos metadados para criar a lista de itens a serem exibidos, alguns dos itens dos metadados são indesejados para serem exibidos na lista de seleção, ex. "Não especificado".
Deste modo, nesta tarefa deverá ser criado uma lógica para filtragem dos itens que não devem ser exibidos para o usuário.
Esta configuração deverá ser feita juntamente com as outras configurações de cada base.
Após a formatação da solução, o modal também deverá ser modificado de forma a filtrar os itens a serem exibidos.

**Comment by leandrocollares** [comment]
Questão resolvida via cfb482041cdaacd14580e3b38020256ff5e72cf4
