### ISSUE TITLE
Incluir Brasil como opçao de pesquisa por Localidade no modal

### ISSUE THREAD

**Issue by msbandrade** [DataViva/dataviva-site#1663]
Estamos sem a opção de pesquisa para o Brasil como todo!

![image](https://user-images.githubusercontent.com/20859423/53038682-18401800-345c-11e9-9179-3c69448dca25.png)

**Comment by msbandrade** [comment]
@litodaldegan

**Comment by litodaldegan** [comment]
@msbandrade favor validar em staging.

**Comment by msbandrade** [comment]
Ei @litodaldegan, beleza?

Identificamos algumas coisas que ainda precisam ser corrigidas. 

1. Ao selecionar uma localidade qualquer e depois trocamos por Brasil, está dando erro na página; 

![staging1](https://user-images.githubusercontent.com/20859423/53096313-9b657a80-34fd-11e9-8624-2e31e9ce4c5f.png)

![image](https://user-images.githubusercontent.com/20859423/53096810-bb496e00-34fe-11e9-8e16-5f71fd3f646a.png)


2. No mesmo sentido, se começamos a navegação por atividade econômica a visualização _default_ é Brasil, ao alterar para outra localidade, funciona ok. Ao trocar para Brasil novamente, dá o mesmo erro mencionado no item 1!

3. O gráfico do Product Space para a localidade Brasil, na aba Oportunidades Econômicas, está carregando como _default_ os dados de 2015, teria que corrigir para 2017. 

Uma observação sobre essa aba é que para as demais localidades está havendo uma divergência entre o stagging e o production, de qualquer maneira, em ambos, as datas, indicadores e visualização deveria ser atualizada para 2017. 

Outra coisa que queríamos ver com você é a possibilidade de eliminar a data no título da seção uma vez que existem oportunidades econômicas baseados nos dados da SECEX (2017) e da RAIS (2014). 

![staging2](https://user-images.githubusercontent.com/20859423/53097196-a3261e80-34ff-11e9-8d15-0f72ea204b5a.png)


Obrigado. 
Marcelo e @josianefaleiro

**Comment by litodaldegan** [comment]
Blza e vocês @msbandrade @josianefaleiro ?,

Perfeitamente... corrigi os casos 1 e 2. Favor validar novamente.

Sobre o item 3, vou abrir uma nova issue para esta alteração.

**Comment by josianefaleiro** [comment]
Tudo bem @litodaldegan  e você?

Com relação ao erro 1, está de fato ok. As trocas de localidades estão sendo feitas corretamente quando se trata da pesquisa feita por localidade.

Mas com relação ao erro 2, ainda estamos tendo alguns problemas:

- Ao realizar a busca por produtos e fazer a troca pra qualquer localidade;

- Ao realizar a busca por ocupação e fazer a troca de localidade e ocupação (nesse caso teve momentos que funcionaram, mas em outros apareceu a mensagem 502 Bad Gateway. Faça a pesquisa por Vendedores e tente fazer a troca por estado, por exemplo, que o problema ocorrerá).

Obrigada!

Josiane e @msbandrade

**Comment by litodaldegan** [comment]
Olá @josianefaleiro e @msbandrade 
Tudo bem também :D...

Dei uma olhada aqui, seguem as respostas:

- página de produtos: tinha um bug que estava presente no código a um certo tempo. Acredito que o cache escondeu este problema até o momento. Já fiz a correção em #1667 

- página de ocupações: problema é que a máquina de staging é um pouco reduzida (t2.nano) e está enchendo a memória para buscar os dados para esta página. Como é um ambiente somente de testes, não vejo problema. Mas caso vocês achem interessante podemos modificar para uma máquina um pouco mais robusta, segue opções:

```
Descrição	vCPU	ECU		Memória			Custo
t2.nano (atual)	1	Variável	0,5 GiB	Somente EBS	0,0058 USD por hora
t2.micro	1	Variável	1 GiB	Somente EBS	0,0116 USD por hora
t2.small	1	Variável	2 GiB	Somente EBS	0,023 USD por hora
t2.medium	2	Variável	4 GiB	Somente EBS	0,0464 USD por hora
```

Caso encontrem outros problemas, por favor me informar.
Grato

**Comment by msbandrade** [comment]
@litodaldegan @josianefaleiro 

Se estiver seguro de que os bugs estão corrigidos podemos passar as correções para o Production e manter a máquina de staging em _nano_ mesmo...
Abs.

**Comment by msbandrade** [comment]
@litodaldegan,  
Se você esta seguro de que o erro está sendo causado devido ao tamanho da máquina, podemos subir a correção para production e verificar. Acho que podemos manter a máquina do staging como _nano_. abs 
@msbandrade e @josianefaleiro

**Comment by litodaldegan** [comment]
Perfeitamente @josianefaleiro e @msbandrade... sim, o problema é causado pela insuficiência de recursos da máquina. Basta usar a mesma URL em produção que podemos ver a página carregar normalmente. Alterações foram colocadas em produção. Qualquer problema me avise. Grato

**Comment by msbandrade** [comment]
Ei @litodaldegan e @josianefaleiro 
Dei uma conferida aqui no site e a opção para o Brasil continua ausente. Será que é por causa do cacheamento da página?
![image](https://user-images.githubusercontent.com/20859423/53411188-9d6b8580-39a4-11e9-88cd-70b3bb106118.png)

**Comment by litodaldegan** [comment]
@msbandrade 

Na verdade foi cache do navegador. Há algumas funcionalidade para forçar atualização nos browsers dos usuários (antes que o browser busque uma nova versão), mas tive que desativar pois estava gerando alguns problemas. Podemos retomar essa funcionalidade.
