### ISSUE TITLE
Alterar o site para buscar os dados mais recentes do Product Space

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-site#1665]
"O gráfico do Product Space para a localidade Brasil, na aba Oportunidades Econômicas, está carregando como _default_ os dados de 2015, teria que corrigir para 2017.

Uma observação sobre essa aba é que para as demais localidades está havendo uma divergência entre o stagging e o production, de qualquer maneira, em ambos, as datas, indicadores e visualização deveria ser atualizada para 2017.

Outra coisa que queríamos ver com você é a possibilidade de eliminar a data no título da seção uma vez que existem oportunidades econômicas baseados nos dados da SECEX (2017) e da RAIS (2014)."

![](https://user-images.githubusercontent.com/20859423/53097196-a3261e80-34ff-11e9-8d15-0f72ea204b5a.png)

Alteração requisitada em #1663

**Comment by litodaldegan** [comment]
@msbandrade 

```
"O gráfico do Product Space para a localidade Brasil, na aba Oportunidades Econômicas, está carregando como default os dados de 2015, teria que corrigir para 2017.
```

Sobre os dados estarem sendo carregado com o ano de 2015, favor verificar novamente. Acredito que foi resolvido em um dos últimos PRs. Qualquer coisa me avise.

```
Uma observação sobre essa aba é que para as demais localidades está havendo uma divergência entre o stagging e o production, de qualquer maneira, em ambos, as datas, indicadores e visualização deveria ser atualizada para 2017.
```
Sobre não buscar o ano de 2017, basicamente para esta parte quando é selecionado uma localidade diferente de Brasil, ele usa sempre um ano anterior do dado mais atualizado (é o comportamento presente no código fonte). Por exemplo, para SP, ele faz a seguinte busca (SQL):

`SELECT max(secex_ymbp.year) AS max_1 
FROM secex_ymbp 
WHERE secex_ymbp.bra_id = '4sp090607' AND secex_ymbp.year < (SELECT max(secex_ymbp.year) AS max_2 
FROM secex_ymbp) limit 1;`

Essa alteração foi feita 2016, veja na issue se você concorda com o comportamento existente: https://github.com/DataViva/dataviva-site/issues/1237 

```
Outra coisa que queríamos ver com você é a possibilidade de eliminar a data no título da seção uma vez que existem oportunidades econômicas baseados nos dados da SECEX (2017) e da RAIS (2014)."
```
Dado a questão anterior, se o dado do box ficar com ano diferente do restante dos dados da tela, acredito que seja melhor deixar explícito essa diferença, o que você acha?

**Comment by msbandrade** [comment]
> @msbandrade
> 
> ```
> "O gráfico do Product Space para a localidade Brasil, na aba Oportunidades Econômicas, está carregando como default os dados de 2015, teria que corrigir para 2017.
> ```
> Sobre os dados estarem sendo carregado com o ano de 2015, favor verificar novamente. Acredito que foi resolvido em um dos últimos PRs. Qualquer coisa me avise.
> OK!
> ```
> Uma observação sobre essa aba é que para as demais localidades está havendo uma divergência entre o stagging e o production, de qualquer maneira, em ambos, as datas, indicadores e visualização deveria ser atualizada para 2017.
> ```
> Sobre não buscar o ano de 2017, basicamente para esta parte quando é selecionado uma localidade diferente de Brasil, ele usa sempre um ano anterior do dado mais atualizado (é o comportamento presente no código fonte). Por exemplo, para SP, ele faz a seguinte busca (SQL):
> 
> `SELECT max(secex_ymbp.year) AS max_1 FROM secex_ymbp WHERE secex_ymbp.bra_id = '4sp090607' AND secex_ymbp.year < (SELECT max(secex_ymbp.year) AS max_2 FROM secex_ymbp) limit 1;`
> 
> Essa alteração foi feita 2016, veja na issue se você concorda com o comportamento existente: #1237
> 
> ```
> Outra coisa que queríamos ver com você é a possibilidade de eliminar a data no título da seção uma vez que existem oportunidades econômicas baseados nos dados da SECEX (2017) e da RAIS (2014)."
> ```
> Dado a questão anterior, se o dado do box ficar com ano diferente do restante dos dados da tela, acredito que seja melhor deixar explícito essa diferença, o que você acha?

@litodaldegan 
como essa questão ja foi discutida anteriormente e as coisas ficaram como estão, deve ter um bom motivo. Vamos deixar assim por enquanto.
