### ISSUE TITLE
Atualizar site para buscar os dados mais recentes para a base SECEX

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-site#1668]

**Comment by msbandrade** [comment]
Ei @litodaldegan e @josianefaleiro,

O que aconteceu foi que que a base de dados original do MDIC veio sem essa variável (PORTO). Inclusive se baixarmos para os anos anteriores também vai estar sem a variável. Vou entrar em contato com o ministério para ver o que aconteceu e a possibilidade de conseguir o banco completo. 

De qualquer maneira, tem um buraco na visualização que vou tentar descobrir a razão dele:

![image](https://user-images.githubusercontent.com/20859423/53911632-c55a8900-4035-11e9-99ce-8ce5015ac416.png)

**Comment by msbandrade** [comment]
> Ei @litodaldegan e @josianefaleiro,
> 
> O que aconteceu foi que que a base de dados original do MDIC veio sem essa variável (PORTO). Inclusive se baixarmos para os anos anteriores também vai estar sem a variável. Vou entrar em contato com o ministério para ver o que aconteceu e a possibilidade de conseguir o banco completo.
> 
> De qualquer maneira, tem um buraco na visualização que vou tentar descobrir a razão dele:
> 
> ![image](https://user-images.githubusercontent.com/20859423/53911632-c55a8900-4035-11e9-99ce-8ce5015ac416.png)

@litodaldegan notei que no staging, por algum motivo, o quadradinho referente ao produto destacado na figura acima (2207 - Álcool etílico > 80% vol) não está sendo reconhecido pela visualização em todos os anos. (abaixo figura do staging para 2015). Vamos  subir para o production e ver se da certo. Com relação ao porto, acho que sua solução foi boa de manter como default 2017. Ainda não consegui descobrir porque o MDIC não esta mais divulgando esta variável. Abs. 

![exportacoes_de_sao_paulo_ 2015](https://user-images.githubusercontent.com/20859423/54031529-c8688d00-418d-11e9-8c88-ff53a21371b8.png)
  
@josianefaleiro

**Comment by litodaldegan** [comment]
Olá @msbandrade e @josianefaleiro,

Me lembro desse problema na visualização (buraco no treemap). Chegamos a encontrar o padrão de quando ocorre esse erro, mas não tivemos tempo de investigar a fundo a origem. Quando colocarmos em produção, vai acontecer a mesma coisa. 

Sobre os dados da SECEX, acredito que não devemos ter tempo hábil para calcular tudo de novo. O que vocês acham de colocarmos em produção as mudanças, mantendo o ano de 2017 para as visualizações que fazem uso de dados de porto?

Caso queriam fazer assim, teríamos que fazer somente uma alteração para a visualização de barra passar o parâmetro corretamente para a API (evitando no ano de 2018). A forma como passa atualmente, ainda está no modelo da API antiga (dados MySQL). Mas é uma alteração até rápida de ser feita. Hoje essa visualização está com problema, pela falta do dado:

http://staging.dataviva.info/pt/bar/secex/value,kg/port?type=export&options=month,percentage,singlecolor&id_ibge=3550308&subtitle=exporting_municipality

**Comment by msbandrade** [comment]
> Olá @msbandrade e @josianefaleiro,
> 
> Me lembro desse problema na visualização (buraco no treemap). Chegamos a encontrar o padrão de quando ocorre esse erro, mas não tivemos tempo de investigar a fundo a origem. Quando colocarmos em produção, vai acontecer a mesma coisa.
> Sério que vai ficar o buraco? Temos que dar um jeito de subir para produção sem essa falha, até porque é um produto relevante na pauta de exportação..  
> Sobre os dados da SECEX, acredito que não devemos ter tempo hábil para calcular tudo de novo. O que vocês acham de colocarmos em produção as mudanças, mantendo o ano de 2017 para as visualizações que fazem uso de dados de porto?

Ei @litodaldegan, podemos fazer dessa forma sim.  
> 
> Caso queriam fazer assim, teríamos que fazer somente uma alteração para a visualização de barra passar o parâmetro corretamente para a API (evitando no ano de 2018). A forma como passa atualmente, ainda está no modelo da API antiga (dados MySQL). Mas é uma alteração até rápida de ser feita. Hoje essa visualização está com problema, pela falta do dado:
> 
> http://staging.dataviva.info/pt/bar/secex/value,kg/port?type=export&options=month,percentage,singlecolor&id_ibge=3550308&subtitle=exporting_municipality

**Comment by litodaldegan** [comment]
> > Olá @msbandrade e @josianefaleiro,
> > Me lembro desse problema na visualização (buraco no treemap). Chegamos a encontrar o padrão de quando ocorre esse erro, mas não tivemos tempo de investigar a fundo a origem. Quando colocarmos em produção, vai acontecer a mesma coisa.
> 
> Sério que vai ficar o buraco? Temos que dar um jeito de subir para produção sem essa falha, até porque é um produto relevante na pauta de exportação..

Caso julguem relevantes, posso investir um tempo tentando resolver o problema.

> 
> > Sobre os dados da SECEX, acredito que não devemos ter tempo hábil para calcular tudo de novo. O que vocês acham de colocarmos em produção as mudanças, mantendo o ano de 2017 para as visualizações que fazem uso de dados de porto?
> 
> Ei @litodaldegan, podemos fazer dessa forma sim.

Ótimo, vou fazer essa alteração.

> 
> > Caso queriam fazer assim, teríamos que fazer somente uma alteração para a visualização de barra passar o parâmetro corretamente para a API (evitando no ano de 2018). A forma como passa atualmente, ainda está no modelo da API antiga (dados MySQL). Mas é uma alteração até rápida de ser feita. Hoje essa visualização está com problema, pela falta do dado:
> > http://staging.dataviva.info/pt/bar/secex/value,kg/port?type=export&options=month,percentage,singlecolor&id_ibge=3550308&subtitle=exporting_municipality

**Comment by litodaldegan** [comment]
Vide #1672

**Comment by litodaldegan** [comment]
@josianefaleiro e @msbandrade, em produção.
