### ISSUE TITLE
Atualizar site para buscar os dados mais recentes para a base Educação Superior

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-site#1670]

**Comment by litodaldegan** [comment]
@josianefaleiro  e @msbandrade
Alterações em ambiente de staging... Vale ressaltar que o modal também foi atualizado para buscar os dados mais recentes. Qualquer problema por favor me avise.

Obrigado

**Comment by msbandrade** [comment]
@litodaldegan,

Dei uma corrida de olho e parece que está ok. Vamos aguardar o ok da @josianefaleiro e podemos subir para produção.

**Comment by josianefaleiro** [comment]
@litodaldegan @msbandrade 

Bom dia!

Não encontrei problemas na parte da educação superior do staging.

**Comment by litodaldegan** [comment]
Deste modo, alterações em ambiente de produção.

@msbandrade e @josianefaleiro
