### ISSUE TITLE
Adicionar opção de QueryParam para filtrar dados na API

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-site#1672]

**Comment by litodaldegan** [comment]
@msbandrade e @josianefaleiro, alteração em staging.
Visualizações do tipo barra, foram alteradas para não buscar dados de 2018 em visualizações que usando dados de porto. Vale ressaltar, que as visualizações treemap foram deixadas com o ano padrão 2017 pelo mesmo motivo (fato de não haver dados de porto para 2018).

**Comment by msbandrade** [comment]
> @msbandrade e @josianefaleiro, alteração em staging.
> Visualizações do tipo barra, foram alteradas para não buscar dados de 2018 em visualizações que usando dados de porto. Vale ressaltar, que as visualizações treemap foram deixadas com o ano padrão 2017 pelo mesmo motivo (fato de não haver dados de porto para 2018).

Ei @litodaldegan e @josianefaleiro 

Gostaria que o treemap mantivesse como _default_ os dados mais atualizados, no caso 2018. O ideal seria os treemaps e demais gráficos o mais atualizado e as visualizações que utilizam PORTO, manter para o ano 2017. Caso não seja possível manter as visualizações que utilizam a variável PORTO para 2017, pode deixar 2018 mesmo. Acho que a informação de PORTO é complementar. A informação mais importante são as exportações. Obrigado.

**Comment by josianefaleiro** [comment]
Olá @litodaldegan e @msbandrade! Tudo bem?

Conferi essa alteração no staging e não encontrei problemas.

Obrigada!

**Comment by litodaldegan** [comment]
Obrigado @josianefaleiro, deste modo, em produção.
