### ISSUE TITLE
Verificar erro ao renderizar elemento no treemap

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-site#1673]
> Ei @litodaldegan e @josianefaleiro,
> 
> O que aconteceu foi que que a base de dados original do MDIC veio sem essa variável (PORTO). Inclusive se baixarmos para os anos anteriores também vai estar sem a variável. Vou entrar em contato com o ministério para ver o que aconteceu e a possibilidade de conseguir o banco completo. 
> 
> De qualquer maneira, tem um buraco na visualização que vou tentar descobrir a razão dele:
> 
> ![image](https://user-images.githubusercontent.com/20859423/53911632-c55a8900-4035-11e9-99ce-8ce5015ac416.png)
> 
> _Originally posted by @msbandrade in https://github.com/DataViva/dataviva-site/issues/1668#issuecomment-470265136_

**Comment by litodaldegan** [comment]
Problema decorrente ao fato da visualização não diferencias os nomes dos produtos: "Álcool etílico > 80% vol" e "Álcool etílico < 80% vol". Como estão sendo entendidos como o mesmo item, só é renderizado uma vez. Dado a falta de tempo para resolver o problema de forma ideal, foi realizada uma solução temporária, para os nome que possuem um simbolo ">" foi adicionado um espaço no final (sendo suficiente para diferenciar palavras que a única diferença é o simbolo de _maior_ e _menor_). Em _staging_ para validação. @josianefaleiro e @msbandrade

**Comment by msbandrade** [comment]
> Problema decorrente ao fato da visualização não diferencias os nomes dos produtos: "Álcool etílico > 80% vol" e "Álcool etílico < 80% vol". Como estão sendo entendidos como o mesmo item, só é renderizado uma vez. Dado a falta de tempo para resolver o problema de forma ideal, foi realizada uma solução temporária, para os nome que possuem um simbolo ">" foi adicionado um espaço no final (sendo suficiente para diferenciar palavras que a única diferença é o simbolo de _maior_ e _menor_). Em _staging_ para validação. @josianefaleiro e @msbandrade

Parece que deu certo @litodaldegan! Acho que para o momento pode ser a solução. Por mim, pode subir pra produção! o que voce acha @josianefaleiro ?

**Comment by josianefaleiro** [comment]
Olá @litodaldegan , bom dia!

Testei na minha máquina e na da Thaísa e em algumas pesquisas o espaço em branco para o "Álcool etílico < 80% vol" ainda aparece no staging, conforme exemplo na imagem anexa. Mas, as mesmas pesquisas não apresentaram erro na máquina do @msbandrade. Não sei o motivo do problema.

![Uploading Alcool etílico.PNG…]()

**Comment by litodaldegan** [comment]
Oi @josianefaleiro,

Só problema de cache do navegador. Eventualmente o próprio navegador apaga os arquivos de cache, mas caso queria forçar essa  limpeza, vide em:
https://www.hostnet.com.br/info/como-limpar-o-cache-do-navegador/

**Comment by josianefaleiro** [comment]
Oi @litodaldegan , boa tarde!

Limpei as memórias de cache do navegador, tentei no explorer, firefoz e chrome, mas mesmo assim no meu computador o problema permanece. Contudo, fiz o teste pelo celular e funcionou corretamente. Não sei qual o problema do meu PC, mas mesmo assim acredito que pode subir para produção.

Obrigada!

**Comment by litodaldegan** [comment]
Oi @josianefaleiro,

Beleza, tentei reproduzir em outros navegadores e não obtive o problema.
Vou colocar em produção, e verificamos se o problema vai persistir na sua máquina. 

Grato
