### ISSUE TITLE
Exibir dados de educação básica para municípios que não tem dados de educação superior

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-site#1676]
Quando uma região não apresenta dados de educação superior, a aba de dados de educação é ocultada. Desta forma, não é possível visualizar os dados de educação básica destas regiões.
Desta forma, esta tarefa consiste em alterar este comportamento de forma que a aba seja exibida e somente os dados de educação superior sejam ocultados.

**Comment by litodaldegan** [comment]
@msbandrade alterações realizadas em staging para validação:

http://staging.dataviva.info/pt/location/4mg010009/basic-education

**Comment by msbandrade** [comment]
@litodaldegan 
Dei fiz alguns testes aqui e parece que está ok. Pode subir para produção.
obrigado.

**Comment by litodaldegan** [comment]
Em produção.
