### ISSUE TITLE
Problemas para carregar a visualização de comércio internacional entre Estados e Continentes

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-site#1678]
Ao tentar acessar a base de parceiro comercial entre o continente Ásia e o estado Minas
Gerais está gerando erro na aplicação que impede o carregamento dos gráficos. Esta tarefa
consiste em investigar os possíveis problemas para retornar os dados da página e fazer as
correções necessárias. Também deve ser verificado se o problema ocorre também para outras
localidades.
Estimativa: 8 horas

**Comment by litodaldegan** [comment]
@msbandrade 
Foi constado que o problema se encontrava na URL da visualização mapa.
O problema existia para todas as combinações: continente/país e regiões do Brasil.
Em staging para validação, favor atentar aos gráficos do tipo mapa importação e exportação.

**Comment by msbandrade** [comment]
@litodaldegan 
Ainda continua com um problema quando trocamos o país dentro da visualização. Vou te mandar um video no zap pra voce avaliar.

**Comment by litodaldegan** [comment]
@msbandrade dá uma olhada em staging por favor.
Gentileza limpar o cache para o domínio de staging.

**Comment by msbandrade** [comment]
@litodaldegan 
Está funcionando corretamente.
