### ISSUE TITLE
A funcionalidade de download de imagens para a visualização de variáveis demográficas não está funcionando.

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-site#1680]
Corrigir problema para fazer download de imagem correspondente as visualizações que envolvem informações demográficas.

**Comment by litodaldegan** [comment]
@msbandrade foi encontrado um problema para fazer o download de imagens correspondente aos gráficos de barras. Este problema foi corrigido, e contempla muitos dos gráficos relacionados à informações demográficas. Correção já foi colocado em produção por que não tem risco de gerar efeito colateral e se tratava de um erro no código. Favor verificar se contemplou os casos esperados para esta tarefa.
Dei uma navegada geral na plataforma e não pude encontrar problema para baixar imagem de outras visualizações.

**Comment by msbandrade** [comment]
@litodaldegan 
Não consegui fazer o download de nenhuma imagem das varáveis demográficas.

**Comment by litodaldegan** [comment]
@msbandrade fiz uma alteração, tente novamente por gentileza.

**Comment by msbandrade** [comment]
@litodaldegan testei e está funcionando bem!
