### ISSUE TITLE
Corrigir cálculo de renda média no treemap para atividade econômica

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-site#1686]
Como foi relatado por @msbandrade, o cálculo da renda média para seção e divisão está incorreto.
Deverá ser corrigido a forma como agregação destes dado é feita.

**Comment by msbandrade** [comment]
Obrigado @litodaldegan .

Se tiver qualquer dúvida quanto a essa issue, entre em contato. 
Abs.

**Comment by litodaldegan** [comment]
@msbandrade blza, obrigado.

Basicamente seria alterar a forma de agregação dos dados para fazer
```
total wage / total jobs
```
?

Se sim, coloquei um versão em staging, mais tarde vou dar um confere melhor nos cálculos.

**Comment by msbandrade** [comment]
@litodaldegan, 

Dei um conferida por aqui e parece estar tudo certo. Pode subir.
Obrigado.

**Comment by litodaldegan** [comment]
Obrigado @msbandrade, em prod.
