### ISSUE TITLE
Errors in Growth Rates

### ISSUE THREAD

**Issue by mariohmol** [DataViva/dataviva-site#177]
We did a work here checking all values and indicators in Dataviva.

We found some errors and all are listed here:
* https://github.com/DataViva/datavivaetl/wiki/Exportacao-Check#report-2
* https://github.com/DataViva/datavivaetl/wiki/Emprego-Check#erros-to-fix

One issue that is causing a problem is Growth Rate, some users entered in contact with us and reported about it.

So our ideia is to take out all Growth values and toggles from apps, until we get Dataviva 2 finished.

**Comment by jspeis** [comment]
I ran [some tests](https://gist.github.com/jspeis/beb959dd19bf76c34d69#file-gistfile1-sql) on the new RAIS data and it seems like this is no longer an issue. Closing this issue for now as we start new homologation process.
