### ISSUE TITLE
Add Recommended App to Navigation when Loaded

### ISSUE THREAD

**Issue by gustavolbc** [DataViva/dataviva-site#178]
On the front page, when I click to check [What Are the Export Opportunities for Brazil?], I'm directed to a Guide page. There is a bug: click on the left tab [Exports of Brazil by State (2013)] using the Geo Map visualization (the last one) > choose any state > on the right box that appear go to Related Apps > click Exports of that state (2013). Now the Exports of Brazil by State (2013) using the map visualization disappears, It's replaced by the new app. 

The solution: instead of replace that visualization, the new visualization should be added below the other visualizations on the left tab. Doing that I could have a customized page with the visualizations that I want. It could be nice to have an option to close this new custom visualizations. This kind of solution can be used on the Dataviva 2.0 profiles.

![image](https://cloud.githubusercontent.com/assets/8738728/4238691/ec346dd6-39da-11e4-8797-c5215a91bf19.png)

As you can see the map visualization disappear.
![image](https://cloud.githubusercontent.com/assets/8738728/4238701/163739ba-39db-11e4-9295-0b4d5e1b46c5.png)

**Comment by davelandry** [comment]
Closing this issue, as this is not applicable/possible with the new site design.
