### ISSUE TITLE
Unstar an App from User Profile

### ISSUE THREAD

**Issue by gustavolbc** [DataViva/dataviva-site#182]
When I favourite an app, I could be able to, using less clicks, delete it from my profile page instead of launching the app again and unfavourite it.
We can use this solution in the Dataviva 2.0.

Solution:
![favouriteapp](https://cloud.githubusercontent.com/assets/8738728/4239961/afc4f8f6-39e5-11e4-9f46-6b294c199f76.png)

**Comment by Gilmardealcantara** [comment]
Vinculada a #191.
