### ISSUE TITLE
User Profile page

### ISSUE THREAD

**Issue by gustavolbc** [DataViva/dataviva-site#191]
Every registered user will have a personal profile page where they can view their favourite visualizations, notifications about their activity in the DataViva Forum and have the option to customize their home page.  
![mockup_dv2_profile](https://cloud.githubusercontent.com/assets/8738728/4826511/18d1316a-5f71-11e4-9eaa-735da35c4b69.jpg)

**Comment by Gilmardealcantara** [comment]
Nova página de profile será projetada.
