### ISSUE TITLE
Home Page Design

### ISSUE THREAD

**Issue by gustavolbc** [DataViva/dataviva-site#194]
Hi guys, we are very glad to see your work on the DataViva design.
Although, after analysing the home page design that uses Netflix layout, we think that this layout isn't delivering the real message to the user about what DataViva really is. The Netflix reels are really cool, but we believe that something is missing, like a more direct way to get to the information. We have to reduce the number of clicks to get to a specific information. The netflix suggestions will only give access to a limited amount of information. To get a specific one the user will have to go to the search or visualize tool. I tried to merge all this possibilities into home page. 
This is our design suggestion:

![dv2_home0](https://cloud.githubusercontent.com/assets/8738728/4976804/ffcdbbf8-68cf-11e4-9d07-487d558fa67d.jpg)
![dv2_home1](https://cloud.githubusercontent.com/assets/8738728/4976807/05f565c6-68d0-11e4-8a98-6d9da9a33d6e.jpg)
![dv2_home2](https://cloud.githubusercontent.com/assets/8738728/4976810/12bfc38c-68d0-11e4-8dd0-30924aa642d3.jpg)
![dv2_home3](https://cloud.githubusercontent.com/assets/8738728/4976812/154d55ba-68d0-11e4-87a2-0f5bc98f62d7.jpg)

Tell me what you think.

**Comment by davelandry** [comment]
The google/netflix homepage is now implemented in the new testing site.
