### ISSUE TITLE
Profile Images

### ISSUE THREAD

**Issue by gustavolbc** [DataViva/dataviva-site#196]
Guys, I saw the list of images you put in that google spreadsheet. It's huge and almost impossible to complete it using creative commons images. Elton and I decided to rethink the usage of these images and made a more aggregated list.

**Occupations** - 27 pictures
Use only the first 9 levels of aggregation (we can use 3 images for each occupation) 

**Locality** - 81 pictures
Use only pictures of state capitals (we can use 3 images for each city) 
Obs: if we decided to view a mesoregion we can randomize all the capital pictures of the mesoregion.

**Industries** - 261 pictures
Let's use just the 2 first CNAE digits to illustrate with pictures  (we can use 3 images for each industry) 
Obs: if we decided to view a 1 or 5 digit CNAE we can randomize the pictures related to that category.

**Technical Education** - 39 pictures
Use only the first 13 levels of aggregation (we can use 3 images for each)

**High Education** - 24 pictures
Use only the first 8 levels of aggregation (we can use 3 images for each) 

**Products** - - 63 pictures
Use only the first 21 levels of aggregation (we can use 3 images for each) 

It is a lot of images! If gets hard to find these images, we can just find one for each item instead of three.

**Comment by davelandry** [comment]
We will no longer be using images in profile pages.
