### ISSUE TITLE
Profile Button Design

### ISSUE THREAD

**Issue by gustavolbc** [DataViva/dataviva-site#198]
Another thing that I want to discuss is the layout of the profile boxes in the reel. That model that you sent us, the user will have 4 levels of information in one box. According to the level of importance that is showed, we have:

![spice1](https://cloud.githubusercontent.com/assets/8738728/5013363/47f667ae-6a74-11e4-9a8d-091e9c946f91.jpg)

1st - the image itself
2nd - the text describing the profile
3rd - the icon
4th - the colour

I believe that the information hierarchy today is not the best, we can make it better.

My considerations about it:

**TEXT**
Nowadays the text is secondary compared with the relevance of the image, so we should induce the user to focus on the text, since the raw information about what his looking for is there. It should be the first level of information.

**IMAGES**
As I said in the issue #196 we have to be very careful and wise to pick good images that links that context with the text, so the combination of these two will produce a single piece information, reducing the levels of information available.

**ICON**
I think we can find better icons to illustrate some categories.
I use a lot this icon bank (www.thenounproject.com)

**COLOUR**
That's the biggest challenge we have here, the colour is so sutile that the user sometimes doesn't notice it and doesn't link it to the icon or category. We have to bring this information up.

My suggestion:

![spice2](https://cloud.githubusercontent.com/assets/8738728/5013368/4bfd6564-6a74-11e4-9d32-539d086fc7e5.jpg)

In this layout I decided to merge the colour and image information, giving more space to the colour information. I also made the image more squared, so we can use better the usual picture ratio (3:2). The icon and the text (more visible using a bold weight) are in the same box, producing a single amount of information and connecting both. So now we have 2 big blocks of information, the image-colour and the icon-text. I believe this solution will reduce the visual complexity to the user.
We can use a responsive design to determine the font size according to the number of characters.

**Comment by davelandry** [comment]
Closing this issue, as it was in regards to the unused new layout.
