### ISSUE TITLE
Profile Page App Preview

### ISSUE THREAD

**Issue by gustavolbc** [DataViva/dataviva-site#199]
Guys I was analysing the UX in the profile page and I found some possible problems with the visualizations embedded on it.

**THE PROBLEM**
When the user pass the mouse arrow on the app preview, it starts to interact with the user showing some info. He can even click in a group and the visualization isolate that group. That is nice, however it can be a serious problem. If the user interact with the **preview** he might understand that the app is the preview and never launch the full app. The icon to enlarge it and enter in the complete app with all functionalities is very small (almost hidden) and it is not intuitive to click on it, the layout does not instigate the user to open the app in a proper way.

![2](https://cloud.githubusercontent.com/assets/8738728/5074872/ced30f48-6e75-11e4-949f-87e94401ed0a.png)

**SUGGESTION**
To solve this UX issue I thought about the use of a static image of the app and as soon as the user pass his mouse arrow on it, an overlay image would appear inviting him to enter in the app.

![3](https://cloud.githubusercontent.com/assets/8738728/5074924/3bf61368-6e76-11e4-89e3-781a884c7afa.png)

What do you think guys? This solution was just an idea, let's discuss more about this.

**Comment by davelandry** [comment]
Closing this issue, as it was in regards to the unused new layout.
