### ISSUE TITLE
FAQ Layout

### ISSUE THREAD

**Issue by gustavolbc** [DataViva/dataviva-site#202]
I was checking the FAQ layout (I don't know if it's the final layout) and I found some issues.
Firstly we don't need to have that "Most Active" and "Most Recent" buttons since it will be a static FAQ.

![0](https://cloud.githubusercontent.com/assets/8738728/5109682/179e3bbe-6ffa-11e4-9e85-b06d45f64115.png)

Secondly I didn't like the way you highlighted the search field when it is active, we can do it in a more cleaner and elegant way. That's my suggestion:

INACTIVE FIELD
![1](https://cloud.githubusercontent.com/assets/8738728/5109689/2eef0b9a-6ffa-11e4-9a21-e593f4230445.png)

ACTIVE FIELD
![2](https://cloud.githubusercontent.com/assets/8738728/5109692/33e186b4-6ffa-11e4-8b85-92b496e6ae1d.png)

PS: the grey color for the questions is to light, can you add a little black to it?

**Comment by davelandry** [comment]
Closing this issue, as it was in regards to the unused new layout.
