### ISSUE TITLE
Ways to change variables

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#203]
Guys, this "enlarged" visualization will have boxes that will allow the user change the city he's studing or the app among others, right?
![image](https://cloud.githubusercontent.com/assets/7582295/5142856/1fc88dcc-7170-11e4-838c-5a7b5b883bb3.png)
Cause it is important to have an easy way for the user to see the info he want as fast as possible. If he needs to go back to the visualize again it will require a longer path and it will affect negatively the plan we have to facilitate the navigation and cut the number of clicks the user need to surf between content.

**Comment by davelandry** [comment]
Closing this issue, as it was in regards to the unused new layout.
