### ISSUE TITLE
Remove Boxes from the Layout

### ISSUE THREAD

**Issue by gustavolbc** [DataViva/dataviva-site#204]
Guys I think we should remove all boxes in DataViva, they are from the previous version and they confuse the user when they have to select some button.
This new version is cleaner and the use of boxes doen's fit to it.

Here are some exemples that I found:
![box2](https://cloud.githubusercontent.com/assets/8738728/5144296/4d98bbf4-7180-11e4-8662-d38839415c6f.png)

![box1](https://cloud.githubusercontent.com/assets/8738728/5144298/4dad5bb8-7180-11e4-8c99-543250c1001e.png)

I made a model to show you how cleaner it will be without boxes.

BOXES
![screen shot 2014-11-21 at 11 30 44](https://cloud.githubusercontent.com/assets/8738728/5144353/e282acf2-7180-11e4-9cbd-62643cc2b403.png)

![box3](https://cloud.githubusercontent.com/assets/8738728/5144297/4da4cae8-7180-11e4-932f-e4600060ac48.png)

WITHOUT BOXES
![demographics](https://cloud.githubusercontent.com/assets/8738728/5144360/f07d8d5e-7180-11e4-99a7-25e9f39329d1.png)

![nbox1](https://cloud.githubusercontent.com/assets/8738728/5145862/cc2deaa4-718d-11e4-8c0d-6cdfeca5ff72.png)

**Comment by davelandry** [comment]
Closing this issue, as it was in regards to the unused new layout.
