### ISSUE TITLE
Bug in treemap when showing bananas info

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#206]
When you choose to see municipalitys that export bananas in Minas Gerais the site cracks and shows wrong data.
http://dataviva.info/apps/builder/tree_map/secex/mg/020803/all/bra/?controls=true&year=2013&value_var=val_usd&depth=bra_8&color_var=color
![image](https://cloud.githubusercontent.com/assets/7582295/5738817/0372b890-9bd8-11e4-998b-225a1c8144dd.png)
When you change the agraggation twice it changes the city name and the bug is still there
![image](https://cloud.githubusercontent.com/assets/7582295/5738837/3e414c66-9bd8-11e4-97c5-7c67f0948b38.png)

**Comment by davelandry** [comment]
Good catch, it seems to be happening when there's only 1 entry (and should display 100%).

I've been working on putting the new D3plus into the site, and it fixes this issue automatically :smirk:
