### ISSUE TITLE
Missing colour scale in tree maps

### ISSUE THREAD

**Issue by gustavolbc** [DataViva/dataviva-site#207]
When you change the colour visualization of the tree map, the colour scale is missing. The user is not informed what the shades of red and green means.

![image](https://cloud.githubusercontent.com/assets/8738728/5739137/93045564-9bdc-11e4-96ec-3e2d18ba2d82.png)

**Comment by davelandry** [comment]
I just realized this as well, as I was incorporating the new d3plus.

We're going to be using the built-in color scale of the new d3plus for this. Here's a screenshot of my working environment to show what it will look like (I already got it hooked up!):
![screen shot 2015-01-14 at 1 44 15 pm](https://cloud.githubusercontent.com/assets/1847581/5745155/a69a56e2-9bf4-11e4-8d46-ce362f02545e.png)
