### ISSUE TITLE
Confusing text in the Change Output box

### ISSUE THREAD

**Issue by gustavolbc** [DataViva/dataviva-site#208]
The text in the change output box is not very clear. When the user reads the default text "Export Destinations of Cars from Minas Gerais (2013)", if they are not interested on it, they will never click on it. The idea here is to lead them to a section where they can see exports destinations of a specific product from a specific location. 
The text should be: "Export Destination of a Product from a Location"
This example is applicable to all options in the Change Output box.

![image](https://cloud.githubusercontent.com/assets/8738728/5739213/99117f58-9bdd-11e4-9bcf-ed2f718c092b.png)

**Comment by davelandry** [comment]
Agreed, good idea.

I'll need to figure out a way to have it trigger a product selection box when you select the app, because the next step would then be filling in that product.

I'll report back here after I've tried a few things.

**Comment by davelandry** [comment]
This is resolved with the new builder.
