### ISSUE TITLE
Profile in the main menu

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#210]
As we already have all the profiles options in the front page we think that it may be unnecessary to have it also in the main menu in the upper part of the site, what do you guys think about it?

**Comment by davelandry** [comment]
We definitely should keep the Profile button in the main menu. 

Without it, it requires users to go back to the homepage to get to a profile from elsewhere on the site. It also would remove the option of selecting a specific profile unless they are already on an existing profile.

**Comment by guilhermesganserla** [comment]
About the user need to come back to the front page he will need as many click as he needs now i since he has to open the profile page and then open a profile.
About the option to select a specific profile I can understand why this would happen can you explain me? I'm talking about just the button in the top menu.

**Comment by davelandry** [comment]
Even if it is the same number of clicks, from a usability standpoint there needs to be a navigational element to direct users to the Profile from other pages on the site.
