### ISSUE TITLE
Trade balance in the line plot

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#211]
In the new line plot visualization we have the total amount of exports and imports of a certain locality but we don't have the balance of trade that represents the result of all operations to show what was the  deficit or gain. To show that we suggest a filter which would allow the user to see just the lines that respresent imports and exports or to see just the line if the balance of trade of the locality.

**Comment by davelandry** [comment]
Absolutely agree. We'll get this in there ASAP.
