### ISSUE TITLE
Responsive site design 

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#212]
Today the site is not responsible to the screen size what makes it lose space in some cases, as the front page that does not use a big part of the screen in which we could show more exemples in the carousel  
![image](https://cloud.githubusercontent.com/assets/7582295/6024866/a441d3c2-abb5-11e4-8421-4e000dd40742.png)
When you turn a visualization smaller the site does not adapt to the size of the screen either
![image](https://cloud.githubusercontent.com/assets/7582295/6024922/e8621576-abb5-11e4-95a8-6b8d9e51418d.png)
So we think we would really improve the user experience by having a responsible site that uses better the avalable space.

**Comment by davelandry** [comment]
A full responsive site design is a great idea, but unfortunately is out of the scope of what we are trying to accomplish with this update.

That being said, the Builder, Embed, Profile, Data, and Rankings were all designed to be responsive, but it looks like that behavior is broken on Profile Pages. I've created a separate issue to track that bug: #223

**Comment by davelandry** [comment]
I'm closing this issue, as most pages (other than the profile page #223) respect the full screen width.

Additionally, there is a separate issue discussing specifically mobile site design (#106).
