### ISSUE TITLE
Translations 

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#213]
Guys are you already using in the site the translated lists we have shared with you? Cause it would be better to have then in the developing site so by navegating we can check if everything is right.

**Comment by alexandersimoes** [comment]
We are planning to send over all of the translations at once when they are ready. This way, as we're changing some of the text we won't duplicate effort.

That being said all of the translations from v1.0 are still active and you are free to send over any suggestions for translations that are incorrect.

**Comment by davelandry** [comment]
I have sent all of the necessary files to @eltonfreitas. When he has made his corrections, this issue can be re-assigned to myself for implementation.

**Comment by dgomes2004** [comment]
I will take this one.

**Comment by davelandry** [comment]
@dgomes2004, did @eltonfreitas forward you the files I had sent him?

**Comment by dgomes2004** [comment]
Yes. I´m working on "title_builder" now. Some of the issues I posted came from this. Once I done with a file I will send it to you, ok?

**Comment by davelandry** [comment]
Sounds good!

**Comment by dgomes2004** [comment]
@davelandry could you send me the most recent translations files? I believe the ones I have here are not updated. I will try to tackle it tomorrow. (Already saw some problems on dv2)

**Comment by davelandry** [comment]
@dgomes2004, you do already have the most recent translation files. What you are seeing here is a bug with D3plus where it's not catching "Box Plot". I've created a new issue for that.

If you see any additional translations that are in the files you've edited but aren't being translated on the live site, please create new GitHub issues for each instance.

**Comment by dgomes2004** [comment]
Ok, will do.
