### ISSUE TITLE
Confusing Search Phrase

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#214]
When we open the site the search bar has the frase "Products exported by 
Minas Gerais" 
![image](https://cloud.githubusercontent.com/assets/7582295/6025160/74c73252-abb7-11e4-945a-64739a883574.png)
But the search tool we have today can't find this kind of search. 
We think that the user being able to find visualitions by using words like the example is a great advance, are you guys planning to do that or we will continue with the same tool?

**Comment by alexandersimoes** [comment]
We are not planning to have this type of search available for launch, I've updated this placeholder text appropriately.
