### ISSUE TITLE
Locality and Depth Attributes and color filter

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#215]
We know you guys are still working on the site but just to let you guys know we have tried to change the Locality and Depth and the color filter in many apps and most of then are not working.

**Comment by davelandry** [comment]
@guilhermesganserla, can you post specific apps that you are you seeing this issue with?

**Comment by guilhermesganserla** [comment]
I have tested again and it is working now. It was not working in Tree Map and in the Line Plot.

**Comment by davelandry** [comment]
:+1:
