### ISSUE TITLE
Home page layout

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#217]
The strong colours used in the carousels images and the colour of the letters makes then confusing and in some cases difficult to read. 

And other cases the font makes the name too big for the boxes so it goes through the image like that

![image](https://cloud.githubusercontent.com/assets/7582295/6026604/385b61e2-abc3-11e4-8b21-9862de6762e3.png)

We thought that it would be interesting to use a cleaner layout and as Gustavo is not working with us anymore we can't give you a more detailed feedback but we believe that the one he have proposed and it's the estructural base of what have today may be a good reference for the new layout.

https://github.com/DataViva/dataviva-site/issues/194

**Comment by guilhermesganserla** [comment]
I saw that now the names of the Industries, Localities and so on are no longer inside the boxes, it is now much better! I think we are in the right way to have a clean and nice home page.

**Comment by guilhermesganserla** [comment]
One more thing, are you guys thinking about using the photos?

**Comment by davelandry** [comment]
No, the photos do not fit in with the original design of DataViva.
