### ISSUE TITLE
Nest universities by "ownership" (public/private)

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#218]
The universities visualization in tree map has at his bottom a filter that makes it possible to show just one university as below 
![image](https://cloud.githubusercontent.com/assets/7582295/6026823/e709b3f0-abc4-11e4-978e-ee69d12bc7f4.png)
We think it would be more interesting to show aggregations in a similar mode as we have for the other databases and a suggestion is for the type of couses (medical courses, business, etc) and its "ownership" (public or private).

**Comment by davelandry** [comment]
We can't nest by courses, as the current API doesn't support showing all universities AND all courses at the same time.

Nesting by "ownership" is a great idea though, and I will implement that.
