### ISSUE TITLE
Missing universities in higher education dataset

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#219]
The universities ranking doesn't have all of them listed and we don't have the option to see the entire name of the university. It would be nice to have a way to enlarge a cell If necessary, what do you think guys?
![image](https://cloud.githubusercontent.com/assets/7582295/6026987/18b840dc-abc6-11e4-8632-ed0232b769e8.png)

**Comment by davelandry** [comment]
Good catch, I've made the University Name column wider. Custom cell width is a little more complicated and we won't be able to do it for this release. I've created a separate issue for tracking it in the futures: #224

@jspeis figured out why certain Universities were not being shown, and he's fixing the database as we speak. He will update this issue when it is fixed.

**Comment by jspeis** [comment]
It seems like the higher education tables had not been completely uploaded to the database. I've re-uploaded the tables to the database and it appears to contain a complete list now.
