### ISSUE TITLE
Remove line plot for course enrollment

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#220]
Guys, we think that the Line Plot for enrolment is too messy cause it has too many values and the Scatter shows it in a better way so maybe we could have this info just in the Scatter, what is your opinion about that?

![image](https://cloud.githubusercontent.com/assets/7582295/6027162/73d28148-abc7-11e4-9d79-5c06a1368ac7.png)
![image](https://cloud.githubusercontent.com/assets/7582295/6027168/78b1e956-abc7-11e4-8839-bbfd7dfacdd8.png)

**Comment by davelandry** [comment]
We agree that in most cases the Stacked is much better at displaying this data, but we do not think it is wise to not let the user create this Line Plot. We won't be including it in any Profile pages, but it should still exists in the Builder for advanced users to create whatever they want.
