### ISSUE TITLE
Bug in the geo map app

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#222]
In some visualizations the map of Minas Gerais is not in the right position

http://dataviva.info/apps/builder/geo_map/rais/mg/r9000/all/bra/?value_var=num_emp&controls=true&year=2012

![image](https://cloud.githubusercontent.com/assets/7582295/6044916/a55e3502-ac7d-11e4-9746-cd8b3db2f6fc.png)

**Comment by davelandry** [comment]
This issue does not exist on the new site.
