### ISSUE TITLE
Mid levels

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#229]
We still  have to add the microrregions and macrorregions levels of aggregation in the apps.

**Comment by davelandry** [comment]
What do you mean by "macrorregions"? Are you referring to regions or mesoregions?

**Comment by davelandry** [comment]
@guilhermesganserla, can we get clarification on this?

**Comment by guilhermesganserla** [comment]
I'm referring to regions, cause we use both in Portuguese for the same thing (Northeast, southeast, etc).

**Comment by davelandry** [comment]
Microregions and Regions are now available in search, profiles, and as depth selections in visualizations.
