### ISSUE TITLE
EI Tooltip Values

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#231]
We saw that now we have in the Tree Map the value of the EI and its a great deal! 

Analysing the data we saw that you guys put the transportation cost and we are not sure if this is a good info to show. That's because the data itself is not reliable and because for it to make sense we would have to show the distance and product that composes this value, so maybe it will be better not to show it or find a different way to do that. 

![image](https://cloud.githubusercontent.com/assets/7582295/6132722/a8c7cf1a-b13b-11e4-8d00-efd1df1e2a6a.png)

**Comment by davelandry** [comment]
Sure, we can remove it from the tooltip.

Here are the values we are storing in the database:
* tax
* icms_tax
* transportation_cost
* purchase_value
* transfer_value
* devolution_value
* icms_credit_value
* remit_value

Which ones would you like to show in the tooltips?

**Comment by guilhermesganserla** [comment]
We should let as a filter to form the app as the size: 
purchase_value
transfer_value

the others variables are not as important, probably won't use it for this version.
