### ISSUE TITLE
Line Plot/Stacked Timeline Improvements

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#233]
First of all the Line Plot looks great now that we have it by month!

There are three suggestion we want to make:

1. Give the option for the user to see the info by month or by year: we just need to have a filter that allows the user to see the sum of each month in a year (by year) or let then see like it is now, by month.

2. The user should be able to see just a period of time: as a example we can do smth similar to DataMinas that Elton has shown us made in a Hackaton http://dataminas.info/dados/arrecadacao/
 as discussed in #101
 
3. We should let the user see the historical series for a specific month: in economics is really common to compare the results of a  certain month so it would be possible to see the results of just January for example. (January 2000, January 2001, January 2002, January 2003 and so on).

**Comment by guilhermesganserla** [comment]
We could make all this impovements for the Stacked too!

**Comment by alexandersimoes** [comment]
As for # 3 on your list we did specifically say we weren't going to to implement this behavior in the phone call we had with Eber at the beginning of this year.

**Comment by davelandry** [comment]
I'll implement the first 2 points. #2 should be especially easy:
- [ ] Year/Month Toggle
- [ ] Range Timeline
