### ISSUE TITLE
App footer for new datasets

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#236]
Just a little detail, when we are displaying info about education it's written "Dados fornecidos por SECEX" but the data is from MEC.
![image](https://cloud.githubusercontent.com/assets/7582295/6133733/3bdcb778-b143-11e4-96f7-f9a82a3b93ec.png)

**Comment by davelandry** [comment]
Good catch. Can you tell me what the footer should say for the following datasets?
* Higher Education
* School Census
* EI

**Comment by guilhermesganserla** [comment]
We can use INEP/MEC for High Education and School Census and SEF/MG for the EI
