### ISSUE TITLE
Scatter Bug

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#237]
The Scatter is not working for the Internationl RCA Scope, it says there is no data avaiable.

![image](https://cloud.githubusercontent.com/assets/7582295/6133908/914ce858-b144-11e4-87cf-614eb19923e2.png)

**Comment by davelandry** [comment]
@alexandersimoes, I believe this has to do with the missing PCI values for 2013 and 2014.

**Comment by davelandry** [comment]
Seems to be working for every year except 2014. @alexandersimoes, I've confirmed that the database does not have 2014 "distance_wld" values for states (only municipalities). I have not checked some of the other calculations.

**Comment by alexandersimoes** [comment]
This is resolved and will be live on Thursday's update.
