### ISSUE TITLE
bottom time line selection

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#242]
The bottom time line selection is great, but we need a better solution for the text (maybe not show all months names, or like Pantheon where the date is on the title).

![image](https://cloud.githubusercontent.com/assets/6808970/6596206/cd03afec-c7d0-11e4-88ea-3f770ce37380.png)

**Comment by davelandry** [comment]
New solution has already been developed inside of D3plus and will be present in Thursday's update, here's a preview:

![screen shot 2015-03-11 at 11 28 15 am](https://cloud.githubusercontent.com/assets/1847581/6599722/cacd8980-c7e1-11e4-932f-e449ddd28c5d.png)

**Comment by eltonfreitas** [comment]
Ow, I think is great!!!
