### ISSUE TITLE
Too much color, hard to read and see the icons

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#243]
![image](https://cloud.githubusercontent.com/assets/6808970/6596239/15777bd2-c7d1-11e4-82bd-f593c2818290.png)

**Comment by davelandry** [comment]
You're right, I think the red stacked areas on the bottom really conflict with the red quick links.

Can you help us find a different visualization that looks aesthetically pleasing and would fit on the home page? The only requirement is that it is dark and full color to support having white text in front of it.

**Comment by eltonfreitas** [comment]
Then, I like the network visualization too much, but maybe not attend to conditon dark and full color. I will see and let you know if I find something.

**Comment by dgomes2004** [comment]
We will take a look. It would be nice to have the text (title) and image (viz) matching.

**Comment by dgomes2004** [comment]
![image](https://cloud.githubusercontent.com/assets/6068338/6602746/6aae5eb0-c7fc-11e4-9b85-0fb485f107bd.png)

This one, for instance, would be better if the text was: where are people getting hired in MG?

Since we are showing a map view, right?

**Comment by davelandry** [comment]
Good point @dgomes2004! I'll make that change right now.

**Comment by davelandry** [comment]
Today's update will resolve the issue with the conflicting red colors on the bottom of the image:

![screen shot 2015-03-26 at 3 57 03 pm](https://cloud.githubusercontent.com/assets/1847581/6855704/ff0610fa-d3d0-11e4-8c3c-423b087949d4.png)

Additionally, we've added an image for the Higher Education dataset:

![screen shot 2015-03-26 at 3 56 59 pm](https://cloud.githubusercontent.com/assets/1847581/6855712/10040c7c-d3d1-11e4-9659-95b166bb927e.png)
