### ISSUE TITLE
Basic education level profile page

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#245]
In the profiles (http://dv2.datawheel.us/profiles/) I see Vocational Courses, but where are the basic education levels?

**Comment by davelandry** [comment]
Basic education levels do not have data on courses, so we could only show locations in Brazil by enrollment in that education level.

Is this something that needs it's own Profile page? The Box Plot in a location profile seems to show the most informative slice of the basic education data.

**Comment by davelandry** [comment]
@dgomes2004, what visualizations would you suggest we put on a profile page for a basic education level?

**Comment by dgomes2004** [comment]
We sure need a profile entry, so the users know the data is there, right? The visualizations can be the same we have now, but with some kind of filter for the level/grade. Like now I can see all students in MG by municipality, but I just want to know how many are there for the first grade. Same goes for the basic data visualizations (stacked and geomap). That´s because I´m supposing the app bellow is showing students in basic education for MG:

http://dv2.datawheel.us/apps/builder/tree_map/sc/4mg/all/all/bra/?controls=true&year=2012&size=enrolled&depth=bra_9&color=color

But, since the title says "School Census", I´m not sure if this is just for basic education or for basic + vocational.

**Comment by dgomes2004** [comment]
Considering #258 , the filter should be for dependecy, so we may need a selector for grade, just as we have a selector for the vocational courses.

@davelandry  Do I make sense here or am just making it more confusing?

Seems to me we need to think about the data first, them the visualizations.

**Comment by dgomes2004** [comment]
From translations: School Census (This is the dataset name, we should use a term for the info being showed, like in “Enrollment by Municipality”).

Just to show that we problem here is about the data/info that we are showing. Enrollment in the School Census for Brazil, ie, would be the total number of kids at school. But we have a division between regular school (and its grades) and vocational school.

DV2 is showing numbers for vocational school, and its courses. And just a total number students by location that we just don´t know what it means (http://dv2.datawheel.us/apps/builder/tree_map/sc/4mg/all/all/bra/?controls=true&year=2012&size=enrolled&depth=bra_9&color=color).

Should we have a Skype talk to sort it all out?

**Comment by davelandry** [comment]
We understand what you mean by separating them out. We are looking into what implications that has on the database and API structure. We will probably come up with a front-end solution that doesn't effect the database structure.

For this particular issue, all we need to figure out is what visualizations to show for a specific basic education level. For example, if someone selects "2nd Year High School", we could show:
 * Locations in Brazil with students enrolled in 2nd year high school (geo map, tree map, stacked)
 * Schools in Brazil with students enrolled in 2nd year high school (tree map, stacked, line)

Are there any other visualizations we could show?

**Comment by dgomes2004** [comment]
Great, enrollment by location works fine.
@eltonfreitas can you check if there is any other visualizations for this data?

**Comment by eltonfreitas** [comment]
I think is great. One question, is possible show students enrolled by education level? 
I thought in 4 types of visualization:

1. Locations with Students enrolled
2. Locations with Students enrolled by education level (here, select a specific education level, like you showed)
3. Students enrolled by education level (here, select a specific location, where we can show 2 diferents types of agreggation of education level, ie, education_level_new and education, see https://github.com/DataViva/datavivaetl/blob/master/docs/classificacao/Education_Level.xlsx)
4. Schools with Students enrolled (here, select a specific location, you can show this like you made in High Education, using diferent color by Adm_dependency).



Adm_Dependency

**Comment by davelandry** [comment]
@eltonfreitas, yes, 3 and 4 on your list are also possible, but would appear in the profile for a location. I've created a new issue for that here: #282

**Comment by davelandry** [comment]
Thursday's update will have basic education levels as Profiles.
