### ISSUE TITLE
New datasets in /apps/ landing page

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#249]
http://dv2.datawheel.us/apps/

As it is now, we only have exports, industries and occupations on the treemap menu, for example. We should have at least on main option for each dataset.

**Comment by dgomes2004** [comment]
![image](https://cloud.githubusercontent.com/assets/6068338/6603012/19e40dd4-c7fe-11e4-8cea-92852d9652f4.png)

Could be the five main options we have when you click and get to the first treemap:
http://dv2.datawheel.us/apps/builder/tree_map/secex/4mg/all/all/hs/?controls=true&year=2014&size=export_val&depth=hs_6&color=color

**Comment by davelandry** [comment]
We don't want to crowd too many links into the box for each visualization type, but I think it's a good idea to include some of the new datasets instead of the old ones.
