### ISSUE TITLE
Strategic indicators for Brazil

### ISSUE THREAD

**Issue by davelandry** [DataViva/dataviva-site#250]
[This app](http://dv2.datawheel.us/apps/embed/scatter/secex/all/all/all/hs/?rca_scope=bra_rca&color=color&controls=true&depth=hs_2&year=2014&y=pci&x=distance&size=export_val) for the Scatterplot of Brazil shows no data, because we have only calculated the strategic indicators (distance, opportunity gain, etc) for the geographies inside of Brazil.

@alexandersimoes, should we take this data from the OEC for Brazil and put it into the secex_ymp table? Obviously it would only be yearly and not monthly, but for the sake of this visualization it would work.

**Comment by dgomes2004** [comment]
Nice place to add another link to the OEC as the source of the information.

**Comment by alexandersimoes** [comment]
We don't have distance or opp gain calculated on the OEC currently. This would be a nice wishlist item once we do have that on the OEC.
