### ISSUE TITLE
Major profile bug?

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#251]
http://dv2.datawheel.us/profiles/course_hedu/345A01/?app=1

![image](https://cloud.githubusercontent.com/assets/6068338/6644252/2b64348c-c991-11e4-9499-f1fe6f1d8665.png)

**Comment by dgomes2004** [comment]
Cannot change to University also.

**Comment by davelandry** [comment]
We caught this one this morning. Should be fixed now.
