### ISSUE TITLE
"Download this Visualization" not working

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#253]

**Comment by davelandry** [comment]
@jspeis, I've uploaded the new build of D3plus with your CSV fix. Let me know if that fixes this.

**Comment by dgomes2004** [comment]
Guys,

csv download not working, others are ok.

![image](https://cloud.githubusercontent.com/assets/6068338/6853543/91d9ee3a-d3ca-11e4-8fc2-74c674445bdf.png)

**Comment by jspeis** [comment]
I'm going to close this issue because I fixed this in our code, it just hasn't been pulled on the server yet. If it still doesn't work after the update, feel free to re-open.

**Comment by dgomes2004** [comment]
Ok.
