### ISSUE TITLE
Tooltip disappears on mouseover

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#254]
![image](https://cloud.githubusercontent.com/assets/6808970/6644326/b27e722a-c991-11e4-86e2-fb5dc2c326fc.png)

**Comment by davelandry** [comment]
I'm having trouble reproducing this issue. @eltonfreitas can you tell me if you are still seeing this issue, and if you are, what version of Windows you are using and what browsers it happens in?

**Comment by eltonfreitas** [comment]
@davelandry the versions are *Windows 7 Home Premium* e *Chrome Version 41.0.2272.101 m*. In Fapemig, the windows version is *Professional*.

**Comment by eltonfreitas** [comment]
@davelandry see this video I tested when Tooltip disappears on mouseover
https://www.dropbox.com/s/qee9d4i725yqlrx/test.mp4?dl=0

**Comment by davelandry** [comment]
This will be fixed in Thursday's update.
