### ISSUE TITLE
"Major" and "Courses" inconsistency

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#255]
By period (Enrollment Periods for a University) you mean time of day, right?

![image](https://cloud.githubusercontent.com/assets/6068338/6644404/3e09bc0a-c992-11e4-81f7-7142a6a0cee8.png)

http://dv2.datawheel.us/profiles/university/00298/?app=5

**Comment by dgomes2004** [comment]
Looks like you are using "Majors" (homepage icon, for example) and "Courses" for high education. There is a reason for this? Would it be better to use just one term?

**Comment by davelandry** [comment]
You're right, it's inconsistent. "Major" is the more common English term for University enrollment, should I change all of the "Course" text to "Major" for Higher Education?

**Comment by davelandry** [comment]
I've changed all English instances of "Courses" in higher education to "Majors"
