### ISSUE TITLE
Show/hide filters in legend

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#257]
![image](https://cloud.githubusercontent.com/assets/6808970/6644501/1e948e3a-c993-11e4-8829-265789c6b49b.png)

**Comment by davelandry** [comment]
This was something that we lost in the transition to the public release of D3plus. This feature will be added back in once it gets added back into D3plus.

**Comment by eltonfreitas** [comment]
@davelandry and @alexandersimoes, I received emails stating that the filters are not working. 

![image](https://cloud.githubusercontent.com/assets/6808970/7369363/f3825998-ed87-11e4-8564-ec06007566c6.png)

http://dataviva.info/apps/builder/tree_map/secex/4mg/all/all/hs/

In fact, when I click on the option to filter categories, no longer appears. People claimed that this was the way to add categories in the same view, for example, to see a TreeMap only export Transport and Chemical Products.

**Comment by davelandry** [comment]
This has now been implmented in D3plus (https://github.com/alexandersimoes/d3plus/issues/261) and will be available in the next site update.
