### ISSUE TITLE
Education level builds

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#258]
Do we have only information about vocational courses? And about Education Levels (High school and elementary education)?
![image](https://cloud.githubusercontent.com/assets/6808970/6644532/81a4e682-c993-11e4-9614-82dbe1d7abe8.png)

**Comment by davelandry** [comment]
What information would you like to show here?

**Comment by eltonfreitas** [comment]
It already had before. We can show number of studants by educations levels (Elementary School 1, Elementary Education 2, High school) and por administrative dependecy (Federal Public, State Public, Local Public and Private).

**Comment by dgomes2004** [comment]
related to #245

**Comment by dgomes2004** [comment]
Considering the structure:

![image](https://cloud.githubusercontent.com/assets/6068338/6786001/23018388-d168-11e4-97bf-1ea83a573949.png)

Seems to me we could have one section for vocational courses and another for basic education.
