### ISSUE TITLE
Enrollment status visualization tweaks

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#259]
We have only 3 types (better call status) for university enrolments: entrants, enrolled and graduated.

![image](https://cloud.githubusercontent.com/assets/6068338/6644936/d38da224-c996-11e4-9990-492c55197926.png)

http://dv2.datawheel.us/profiles/university/00316/?app=4

**Comment by davelandry** [comment]
I will remove the "Students" line and rename the visualization to "Enrollment Status"
