### ISSUE TITLE
Only show location nesting deeper than selected location

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#260]
Stacked - Enrollment in Minas Gerais by Municipality not show municipalities

![image](https://cloud.githubusercontent.com/assets/6808970/6645203/3a244482-c999-11e4-8305-e4268c6faade.png)

http://dv2.datawheel.us/apps/builder/stacked/hedu/4mg/all/all/bra/?controls=true&year=2009_2012&layout=value&y=enrolled

**Comment by davelandry** [comment]
Make sure you clear your browser cache. This should be working.

**Comment by eltonfreitas** [comment]
Working now, but yet not show municipalities.

![image](https://cloud.githubusercontent.com/assets/6808970/6646111/b1978798-c9a0-11e4-8788-3a844054cc21.png)

http://dv2.datawheel.us/apps/builder/stacked/hedu/4mg/all/all/bra/?y=enrolled&layout=value&controls=true&year=2009_2012

**Comment by davelandry** [comment]
On the stacked area charts, you click to zoom into areas.

**Comment by eltonfreitas** [comment]
But the Title say "by municipality". Maybe this is a case of having a filter regions?

**Comment by davelandry** [comment]
I think, in this case, the user should not see any aggregation above their currently selected location. When selected on Minas, the visualization should only show mesoregions and below.

Additionally, the title should be updating to reflect the current depth.
