### ISSUE TITLE
Grey shapes when switching visualizations in builder

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#261]
Stacked - Vocational Courses in Minas Gerais - doesn't display courses
![image](https://cloud.githubusercontent.com/assets/6808970/6645224/6aaba848-c999-11e4-959b-75614539770f.png)

http://dv2.datawheel.us/apps/builder/stacked/sc/4mg/all/all/course_sc/?controls=true&year=2009_2012&layout=share&y=enrolled

**Comment by davelandry** [comment]
This seems to be related to browser caching. Please clear your cache and refresh the page.

**Comment by davelandry** [comment]
Related to #260 

I'm re-opening this, as I've discovered the bug. It only occurs when you switch between visualizations. I have seen it on Tree Maps as well as Stackeds.

**Comment by davelandry** [comment]
Found it, simple fix.
