### ISSUE TITLE
Multiple years on treemap?

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#263]
Guys, for the sake of our sanity and the users understanding, I think we should not have the possibility to select more then an year on treemap. Must people just won´t see this is happening and misuse the info. (Happens if I was on stacked and build a treemap:)

![image](https://cloud.githubusercontent.com/assets/6068338/6645312/2d5e65f6-c99a-11e4-859e-3e0655fde6b3.png)

http://dv2.datawheel.us/apps/builder/tree_map/rais/4mg/all/all/cnae/?controls=true&year=2002_2013&size=num_emp&depth=cnae_6&color=color

**Comment by dgomes2004** [comment]
Don´t get me wrong here, I love this new feature, but I think it should be only for viz where we have a time series.

**Comment by davelandry** [comment]
We just discussed this issue, and feel that it is important to keep this functionality in the site. The time range being visualized is displayed in both the timeline and in the large title on the top of the visualization. We would be doing our users a disservice by not providing this feature.
