### ISSUE TITLE
Planning region error in selector box

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#264]
When I came back to Brazil in Selector Box, its no show the Regions, it show planning regions of MG.

![image](https://cloud.githubusercontent.com/assets/6808970/6645313/30b30a2c-c99a-11e4-9c60-e24098c7c5c9.png)

http://dv2.datawheel.us/apps/builder/geo_map/rais/4mgplr02/all/all/bra/?controls=true&year=2013&color=num_emp

**Comment by davelandry** [comment]
Fixed!
