### ISSUE TITLE
Some location similarities are the same as themselves

### ISSUE THREAD

**Issue by davelandry** [DataViva/dataviva-site#265]
For example, "c30415" for "4mg" in 2013 has a similar location list of ["4mg"].

Should this be possible? How did this happen?

**Comment by dgomes2004** [comment]
Did you guys redo the calculations for cnae? And for 2013? Please see my comment in #14 , the numbers are not making sense.

**Comment by alexandersimoes** [comment]
@davelandry - yes this is possible if that location is successful aka has RCA in that industry thus adding it to the sample set of locations to be used.

@dgomes2004 - yes we did rerun the calculation for CNAE.
