### ISSUE TITLE
Show original IDs on data page (IBGE, etc)

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#266]
BRA_ID not show IBGE_ID. Here, we need to show all originals ID and names of attributes whether regions, ocupations, industries, courses, universities, etc.

![image](https://cloud.githubusercontent.com/assets/6808970/6667106/aa3dfb2e-cbc8-11e4-8668-9bf4369cb195.png)

http://dv2.datawheel.us/data/

Another thing, the arrangement of elements in the check box looks messy.

**Comment by davelandry** [comment]
What do you mean by your last comments? What elements in what check box?

**Comment by dgomes2004** [comment]
What @eltonfreitas wants to say is that the selection menu should be better organized. Our suggestion is that each filter should be a line, and the users selecitions should be under the filter, like:

New Filter
Location:
Minas Gerais
Occupation:
All
Industry:
Call Centers

**Comment by dgomes2004** [comment]
Also important to add coluns with the names and original codes for the attributes.
