### ISSUE TITLE
Additional Box Plot visualizations

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#268]
![image](https://cloud.githubusercontent.com/assets/6808970/6668187/d794f634-cbcf-11e4-84b3-01fe1919dc31.png)

http://dv2.datawheel.us/apps/builder/box/sc/4mg/all/all/age/?controls=true&year=2007_2012&depth=school_id

**Comment by davelandry** [comment]
Good catch, I just fixed this and it will be updated on Thursday.

**Comment by dgomes2004** [comment]
Still not working here...

**Comment by davelandry** [comment]
What is not making sense?

**Comment by eltonfreitas** [comment]
What information is that? Average Monthly Wage of each employee or average of occupations or average of industries?
![boxplot](https://cloud.githubusercontent.com/assets/6808970/6825749/6ce0bac2-d2db-11e4-94c8-eb6d49574e23.JPG)

**Comment by eltonfreitas** [comment]
Same case, what we have here? Average age of each student or a of other levels?
![boxplot](https://cloud.githubusercontent.com/assets/6808970/6826038/926d7602-d2dd-11e4-8263-845571416033.JPG)

We expect a little more detail here as well. Here, it is important to show at least how is this difference between public and private schools. That is, Average age of a location by Administrative Dependency (Federal Public, State Public, Local Public, Private).

**Comment by davelandry** [comment]
I've added 2 additional RAIS box plots, filtering by an industry or an occupation.

I've also added a toggle to the Age Distribution box plots to filter the data by a school's Administrative Dependency.
