### ISSUE TITLE
Unclassified locations?

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#273]
http://dv2.datawheel.us/apps/builder/network/rais/0xx000006/all/all/cnae/?controls=true&year=2013&size=wage&color=color

**Comment by davelandry** [comment]
I'm seeing a bug where the network is zoomed in too far, is that what you are reporting?

**Comment by dgomes2004** [comment]
![image](https://cloud.githubusercontent.com/assets/6068338/6687753/9ef7593a-cc8c-11e4-84d8-dc6c841d26db.png)

All those unclassified locations should not be shown.

**Comment by davelandry** [comment]
No problem, we'll remove those from the selector.

However, they will still appear in the visualizations. For example, "Locations in Brazil that Export Beans" will have this unclassified section listed, as it makes up a portion of the overall total and would be inaccurate without it.
