### ISSUE TITLE
Titles need to change with selections of infos

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#276]
For example, if I build a viz for domestic trade, I can change the size between Purchase and Transfer Value, but the titel of the viz does not change. So if I select Transfer, the title does not match the info I have on the viz.

http://dv2.datawheel.us/apps/builder/tree_map/ei/4mg030000/all/all/bra_r/?depth=bra_9&size=transfer_value&controls=true&year=2013-1

**Comment by davelandry** [comment]
@dgomes2004, would you have the title change to "Municipalities that Transfer Products from Belo Horizonte"?

**Comment by dgomes2004** [comment]
Exactly.

**Comment by dgomes2004** [comment]
@davelandry still not working here. another two things here (maybe needs another issue): a icon solution for the regions - just colors now; and the filter is not working - to isolate just one region.

**Comment by davelandry** [comment]
This has been coded, and will be part of today's update.

Please create a new issue for region icons.

There is already an issue for the filters: #257
