### ISSUE TITLE
Dataset dropdown positioning in Portuguese

### ISSUE THREAD

**Issue by alexandersimoes** [DataViva/dataviva-site#278]
![screen shot 2015-03-23 at 4 15 07 pm](https://cloud.githubusercontent.com/assets/252276/6789622/07024608-d178-11e4-940c-d70bed5167c3.png)

related to #277

**Comment by dgomes2004** [comment]
@davelandry  Best thing here is to let the user see all options he/she has. If scrolling is needed, he/she may not notice it and not see the options available.

**Comment by dgomes2004** [comment]
@alexandersimoes still can´t select or see 2013 and 2014:

![image](https://cloud.githubusercontent.com/assets/6068338/6853618/0c72adb2-d3cb-11e4-9f8d-bb1c12883f50.png)

**Comment by dgomes2004** [comment]
If I use the keybord it does show up:
![image](https://cloud.githubusercontent.com/assets/6068338/6853664/3f4a5eec-d3cb-11e4-93b3-f5c8b3e8aa51.png)

**Comment by alexandersimoes** [comment]
@dgomes2004 we'll be sending out an email later this evening as part of our weekly thursday updates that addresses many of these issues. Our workflow is that we test things locally before pushing live and close issues accordingly. If you were to run a local copy of the site with the most recent updates you would see this issue resolved.

**Comment by dgomes2004** [comment]
Ok, good to know.

**Comment by eltonfreitas** [comment]
![image](https://cloud.githubusercontent.com/assets/6808970/6872031/5ddb4672-d485-11e4-87dc-469e1b609f33.png)
@alexandersimoes look this

**Comment by davelandry** [comment]
Changing the label from "Database" to "Source" fixes this issue.

![screen shot 2015-04-02 at 1 58 34 pm](https://cloud.githubusercontent.com/assets/1847581/6969957/6754a2e2-d940-11e4-8f50-b83761e69621.png)
