### ISSUE TITLE
Learn More text for new visualizations

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#280]
Guys, we have two new visualizations on 2.0 (line and box plot). For the 1.0 visualizations, we had a tutorial (question mark on top right) and explanations (learn more). Do you think we should create these for the new visualizations?

Considering our experience with our users, none of them have being effective. Do you have any suggestion to make this kind of help more useful for users?

**Comment by dgomes2004** [comment]
For now, a simple text as we have for the other viz will do.

**Comment by davelandry** [comment]
I will be writing this text.
