### ISSUE TITLE
Selector depth improvements

### ISSUE THREAD

**Issue by davelandry** [DataViva/dataviva-site#281]
The current selector currently requires a lot of clicks to find what you need. For example, when wanting a municipality, if you're not searching, you must click through Regions, States, Mesoregions, and Microregions, and you must know the nestings! Here is a mockup of what it would look like if we created a global depth selector that effects the list being shown.

![selector_bra](https://cloud.githubusercontent.com/assets/1847581/6811754/902a20cc-d240-11e4-9533-81a34147f667.png)

Additionally, each list item would get small links for each level inside of itself. Clicking on "Planning Regions" in the Minas box would yield this:

![selector_4mg](https://cloud.githubusercontent.com/assets/1847581/6811767/add88fdc-d240-11e4-84eb-65935de468a4.png)

Any objections to making this change?

**Comment by eltonfreitas** [comment]
Ow, that looks really cool !!
