### ISSUE TITLE
Mouse over edge highlight not working in Rings

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#283]
The connections of a first level node used to light up when you place the mouse over it. It´s not happening in DV2. Is this on purpose or a bug?

http://dv2.datawheel.us/apps/builder/rings/secex/4mg/052601/all/hs/?controls=true&year=2014&rca_scope=bra_rca&color=color

http://dataviva.info/apps/builder/rings/secex/mg/178703/all/hs/?controls=true&year=2013&color_var=color&rca_scope=wld_rca

**Comment by eltonfreitas** [comment]
See this too:
DV2:
![image](https://cloud.githubusercontent.com/assets/6808970/6833475/1ad6b354-d30c-11e4-9877-9e0f64788b8a.png)

DV1:
![image](https://cloud.githubusercontent.com/assets/6808970/6833507/5f8206ca-d30c-11e4-9491-2e2c48831876.png)

**Comment by davelandry** [comment]
@eltonfreitas, please create separate issues for each individual bug. I've created a new issue for the sizing here: #285
