### ISSUE TITLE
Learn More text for new datasets

### ISSUE THREAD

**Issue by davelandry** [DataViva/dataviva-site#286]
The site needs descriptive text for the new education datasets. The SECEX text might also need to be updated to talk about monthly resolutions and imports.

![screen shot 2015-03-26 at 1 58 35 pm](https://cloud.githubusercontent.com/assets/1847581/6853369/3688c65e-d3c1-11e4-9352-2d38b4c69e37.png)

**Comment by dgomes2004** [comment]
@eltonfreitas will send me in pt and I will send you guys in pt and en.

**Comment by dgomes2004** [comment]
done, sent by email to @davelandry
