### ISSUE TITLE
Location similar not shown for municipalities

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#290]
![image](https://cloud.githubusercontent.com/assets/6808970/6872144/f1ada0e8-d485-11e4-8a31-3d95b193e537.png)

http://dv2.datawheel.us/apps/builder/occugrid/rais/4mg030000/c22226/all/cbo/?controls=true&year=2013&size=required&order=name

**Comment by davelandry** [comment]
Will be fixed with today's update.
