### ISSUE TITLE
Occupations names not shown in Occugrid

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#291]
![image](https://cloud.githubusercontent.com/assets/6808970/6872203/75e45262-d486-11e4-9c01-3d2a5cf7e90d.png)

http://dv2.datawheel.us/apps/builder/occugrid/rais/4mg/c14126/all/cbo/?controls=true&year=2013&size=required&order=name

**Comment by davelandry** [comment]
This is now fixed and will be in next week's update.
