### ISSUE TITLE
Add download function to crosswalk tables

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#293]
http://dv2.datawheel.us/about/crosswalk/hs/cnae/

**Comment by dgomes2004** [comment]
It is also important to have the classification codes on the csv file (even better if you could show them on the table view).

**Comment by davelandry** [comment]
IDs and Downloads have been added to the crosswalk tables. It will be available in the next site update.

![screen shot 2015-05-19 at 1 12 48 pm](https://cloud.githubusercontent.com/assets/1847581/7709129/ddbdaa70-fe28-11e4-9f2a-799bddced9c1.png)
