### ISSUE TITLE
Remove mid-level product rankings

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#295]
Not loading for chapters:

http://dv2.datawheel.us/rankings/2012/hs/4/?order=export_val.desc

**Comment by davelandry** [comment]
This option was listed in error, as we do not store any data for this level.

**Comment by dgomes2004** [comment]
@davelandry : We should have data for this level, as discussed on #37 and #111. And on #308 I meant Chapter = 4-digit HS2, my mistake. As commented there, we were thinking this level was already in, that´s why I opened both issues.

I understand this would be a major data add, montly data, and we should have catched this before, but it would be really important to have this level in order to be consistent with the other depths and because Chapters is the most important level for analyses.

I´m reopening this one for consideration, ok?

**Comment by dgomes2004** [comment]
Closing again.
