### ISSUE TITLE
Missing translation for "students", "entrants" and "graduates"

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#300]
http://dv2.datawheel.us/apps/builder/tree_map/hedu/4mg/all/all/bra/?controls=true&year=2012&size=students&depth=bra_9&color=color

![image](https://cloud.githubusercontent.com/assets/6068338/7137718/1a60ef12-e292-11e4-8861-064b643f7970.png)

**Comment by davelandry** [comment]
Students is no longer being shown (#297). @dgomes2004, can you tell me the correct translations for the following 2 names:
* Entrants
* Graduates

**Comment by dgomes2004** [comment]
Entrantes
Formandos
