### ISSUE TITLE
Missing translation for "stats" and "top municipality"

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#301]
![image](https://cloud.githubusercontent.com/assets/6068338/7146335/3a396a62-e2c9-11e4-8fc0-aa362677f56b.png)

**Comment by davelandry** [comment]
@dgomes2004, please write in this issue what the translations should be.

**Comment by dgomes2004** [comment]
Stats = Estatísticas
Top Municipality by Enrollment = Principal Município por Matrículas

**Comment by davelandry** [comment]
This will be fixed in today's update.
