### ISSUE TITLE
Weird date format on csv download

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#306]
Sun Jan 01 2006 00:00:00 GMT-0200 (HorÃ¡rio brasileiro de verÃ£o)

CSV download of:
http://dv2.datawheel.us/profiles/cnae/f42910/?app=1

Do you guys need this because of the monthly data? Just the year would be a lot easier for the users.

**Comment by davelandry** [comment]
This will be fixed with #329
