### ISSUE TITLE
"employees" to "employment" translation change

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#307]
@davelandry could you take a look at all entries for "employees" and change them to "employment"? Translation would always be "empregos", not "empregados".

As we discussed a long time ago, the data is always for employment (jobs positions), but I thinks we (or just myself) didn´t payed attetion to this during translations.

If I do it on the po file I have here and send it to you again, would be better?

**Comment by davelandry** [comment]
I just e-mailed you the newest translation file. Please make any changes you need to make in there and send it back to me! :beers:

**Comment by dgomes2004** [comment]
done on PO file.
