### ISSUE TITLE
Filter unclassified attributes from similar profiles list

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#311]
![image](https://cloud.githubusercontent.com/assets/6068338/7201788/aeb8a6f4-e4e1-11e4-9b82-3889ce3944a5.png)

http://dv2.datawheel.us/profiles/bra/4mg/?app=57

**Comment by davelandry** [comment]
Fixed for all classifications that have "Unclassified" entries. Will be live with our next update.
