### ISSUE TITLE
Fix bar charts for parent categories

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#312]
![image](https://cloud.githubusercontent.com/assets/6068338/7206541/eadb7446-e508-11e4-8465-3447568b5fdf.png)

http://dv2.datawheel.us/apps/builder/bar/rais/all/c/all/cnae/?controls=true&year=2013

**Comment by dgomes2004** [comment]
also for:

http://dv2.datawheel.us/apps/builder/bar/rais/all/all/3/cbo/?controls=true&year=2013

**Comment by davelandry** [comment]
This is an issue with the data call for parent level categories. I've just coded the fix and am testing it locally, will be ready soon.

**Comment by dgomes2004** [comment]
Great.
