### ISSUE TITLE
Add CSS ellipsis to long profile slugs

### ISSUE THREAD

**Issue by davelandry** [DataViva/dataviva-site#315]
Seen in this page, when a visualization group has a long title it interferes with the layout of the square visualization buttons floating on the right (http://dv2.datawheel.us/profiles/course_hedu/311P02/?app=10):

![screen shot 2015-04-17 at 2 17 51 pm](https://cloud.githubusercontent.com/assets/1847581/7208187/d23f7776-e50c-11e4-8670-f2da84ecfc9d.png)

@alexandersimoes is the king of CSS ellipsis, so I think he should add automatic ellipsis to these longer titles :smirk:

**Comment by alexandersimoes** [comment]
Should now add <title="blah blah blah"> to html for mouseover

**Comment by alexandersimoes** [comment]
ALSO done
