### ISSUE TITLE
Change the capitalization for Coos and Ceos

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#318]
![image](https://cloud.githubusercontent.com/assets/6068338/7319139/77ff27a4-ea69-11e4-880c-27add90fc407.png)

On this print, we also have a bunch of Coos. Thought it isn´t wrong, it looks weird, could we translate it to "Diretores de Operações" or it would become too long?

**Comment by davelandry** [comment]
I think a better solution would be to change the capitalization, so that they all say "COOs" instead of "Coos".

**Comment by dgomes2004** [comment]
@davelandry 
That helps. Also for Ceos (CEOs).
