### ISSUE TITLE
Build visualization not working in PT

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#323]
I tested some visualizations and they all presented this problem, the build bottom is not active in PT, but works if I change the language to EN.

**Comment by alexandersimoes** [comment]
I assume this is in the advanced builder? What is the workflow that breaks? What type of viz and what combos of data are you trying to look at?

**Comment by davelandry** [comment]
I will be looking into this today.

**Comment by davelandry** [comment]
We have fixed this locally, it will be working on the live site by the end of the day.
