### ISSUE TITLE
Missing CBO translations

### ISSUE THREAD

**Issue by alexandersimoes** [DataViva/dataviva-site#324]
@dgomes2004 - Need some help with a few missing Portuguese occupation names:

CBO 5142 - Garbagemen
CBO 7156 - Electrical Workers
CBO 5132 - Cooks
CBO 4141 - Stockmen
CBO 7832 - Movers
CBO 8483 - Bakers
CBO 2521 - Administrators

**Comment by dgomes2004** [comment]
@alexandersimoes 

CBO 5142 - Garbagemen / Lixeiros
CBO 7156 - Electrical Workers / Eletricistas
CBO 5132 - Cooks / Cozinheiros
CBO 4141 - Stockmen / Almoxarifes
CBO 7832 - Movers / Carregadores
CBO 8483 - Bakers / Padeiros
CBO 2521 - Administrators / Administradores
