### ISSUE TITLE
Stacked - Enrollment by Municipality not working

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#326]
Here shows Enrollment by Municipality but the viz shows State:
![image](https://cloud.githubusercontent.com/assets/6808970/7390446/c7f7f63a-ee4e-11e4-92f8-3343c5e661a8.png)
![image](https://cloud.githubusercontent.com/assets/6808970/7390559/e6fff504-ee4f-11e4-89bf-901c2f2ad293.png)
http://pt.dataviva.info/apps/builder/stacked/hedu/4mg030000/all/all/bra/?y=enrolled&layout=value&order=color&controls=true&year=2009_2013

In EN, the title show **Enrollment in Belo Horizonte by State**, but It should not be so, 
![image](https://cloud.githubusercontent.com/assets/6808970/7390497/48aa97ec-ee4f-11e4-9aee-4321bf41067b.png)
http://en.dataviva.info/apps/builder/stacked/hedu/4mg030000/all/all/bra/?y=enrolled&layout=value&order=color&controls=true&year=2009_2013

**Comment by eltonfreitas** [comment]
Same case in SC:
![image](https://cloud.githubusercontent.com/assets/6808970/7390770/897883e0-ee51-11e4-8040-bb07172790ec.png)
http://en.dataviva.info/apps/builder/stacked/sc/4mg080609/all/all/bra/?y=enrolled&layout=share&order=color&controls=true&year=2007_2014

**Comment by rafamape** [comment]
Sugestão: alterar o menu para "Matrículas por Localidade", considerando que o gráfico é dinâmico e a cada clique ele mostra uma regionalização diferente.

Essa mesma alteração deve ser realizada para todos os bancos de dados disponíveis nessa visualização (salários, emprego, e comércio internacional).
