### ISSUE TITLE
Filter university selector by location in advanced builder

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#328]
If I select one location, for example, State of Minas Gerais, When I try select a University, appear all University, how I will know which are of Minas Gerais? Is possible a filter when I select one location and show only universities that there are in this location?
![image](https://cloud.githubusercontent.com/assets/6808970/7390647/a46e25b6-ee50-11e4-9a2a-7fb4aa50f752.png)

![image](https://cloud.githubusercontent.com/assets/6808970/7390679/f3c82418-ee50-11e4-9f3f-5590f95f0103.png)

http://en.dataviva.info/apps/builder/stacked/hedu/4mg080609/00322/all/time/?y=students&layout=share&order=color&controls=true&year=2009_2013

**Comment by eltonfreitas** [comment]
Same case:

![image](https://cloud.githubusercontent.com/assets/6808970/7390728/44bde042-ee51-11e4-8ace-9e149755b5a4.png)
http://en.dataviva.info/apps/builder/stacked/hedu/4mg080609/00322/380D01/time/?y=students&layout=share&order=color&controls=true&year=2009_2013

**Comment by davelandry** [comment]
Currently not possible. The visualizations will work if you remove the location filter by selecting Brazil.

**Comment by Gilmardealcantara** [comment]
Relationship between univesities and location is unavaliable.

**Comment by eltonfreitas** [comment]
Acho que essa é uma funcionalidade importante de ser criada! Fica como proposta para melhoria!

**Comment by Gilmardealcantara** [comment]
Limitar a escolha dos demais filtros dado um filtro no Construa Seu Gráfico.

Exemplos: 
- Ao selecionar uma localidade o filtro de universidade deve mostrar somente as universidades daquela localidade.
- Ao selecionar uma localidade o filtro de ocupação deve mostrar somente as ocupações presentes naquela localidade.

http://dataviva.info/pt/build_graph/hedu/4rj020212/00322/all?view=OUrz18lsuM&graph=line
