### ISSUE TITLE
CSV downloads do not show all information

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#329]
http://pt.dataviva.info/apps/builder/network/rais/4mg0300/all/all/cnae/?color=color&controls=true&year=2013&spotlight=true&size=wage

When I download the CSV file for this visualization, the only info it has is: Classe,Ano,Renda Mensal Total,Nome (Class, Year, Total Wages, Name). This is not the info necessary to build the visualization, right? And not useful for the user looking for indicators, etc.

**Comment by davelandry** [comment]
I am going to be changing this CSV so that it shows all of the information loaded from the database, the full raw data call.
