### ISSUE TITLE
PT/EN problems

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#330]
If I try to change to EN from here (http://pt.dataviva.info/apps/builder/network/rais/4mg0300/all/all/cnae/?color=color&controls=true&year=2013&spotlight=true&size=wage), for example, that´s what I get:

![image](https://cloud.githubusercontent.com/assets/6068338/7392689/c1932c72-ee5f-11e4-8dee-501c6146fc85.png)

**Comment by dgomes2004** [comment]
If I try to go back to PT, same thing, it freezes.

**Comment by davelandry** [comment]
Fixed locally, will be fixed the next time we pull on the live site.
