### ISSUE TITLE
Trade Balance for China does not work

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#331]
Since we don´t show this info (although we have it), we should remove this viz from the profiles:

![image](https://cloud.githubusercontent.com/assets/6068338/7392744/23f4e766-ee60-11e4-8b4f-7ef5b9a09dcb.png)

**Comment by davelandry** [comment]
This is actually a problem specifically with China that we are looking into. It works for most other countries:

![screen shot 2015-04-29 at 11 39 10 am](https://cloud.githubusercontent.com/assets/1847581/7394887/7238e784-ee64-11e4-8167-4444d0ce204e.png)

**Comment by davelandry** [comment]
We just updated the live site, fixing some data caching issues. This is fixed for us, so I will mark this as closed.

@dgomes2004, if you are still seeing this as broken, please re-open this issue.

**Comment by dgomes2004** [comment]
Working great!
