### ISSUE TITLE
"Top Campuses" Translation

### ISSUE THREAD

**Issue by alexandersimoes** [DataViva/dataviva-site#332]
We are adding the top locations of campuses for a university in the stats panel (see below). So we need a translation for: "Top Campuses"

![screen shot 2015-04-29 at 11 28 02 pm](https://cloud.githubusercontent.com/assets/252276/7405922/fa2a8a72-eec7-11e4-8e81-ab844f5718f3.png)

**Comment by dgomes2004** [comment]
Top Campuses = Principais Campi
