### ISSUE TITLE
Product complexity carousel link

### ISSUE THREAD

**Issue by davelandry** [DataViva/dataviva-site#333]
@dgomes2004, we think it would be cool if the product complexity carousel had a link to the glossary explaining PCI, like this:

![screen shot 2015-04-30 at 10 48 34 am](https://cloud.githubusercontent.com/assets/1847581/7415412/b29b3b20-ef26-11e4-80c3-7275c1d64e7a.png)

If we all agree, can you translate this sub-title for us?
***"Click here for more information on product complexity."***

**Comment by dgomes2004** [comment]
Great idea!

Click here for more information on product complexity.
Clique aqui para entender melhor a complexidade de produtos.
