### ISSUE TITLE
Partners and Data Source logos/section

### ISSUE THREAD

**Issue by davelandry** [DataViva/dataviva-site#334]
When we were in Belo, we discussed having the footer logos more prominent in the top of the about page, along with including an Amazon logo. Here's a mockup of what that would look like:

![screen shot 2015-04-30 at 11 08 01 am](https://cloud.githubusercontent.com/assets/1847581/7415852/5ffe20be-ef29-11e4-869d-0c01a10d3e6b.png)

@dgomes2004, should there by any text to accompany these logos?

Additionally, I have added the AWS logo into the footer:

![screen shot 2015-04-30 at 11 07 47 am](https://cloud.githubusercontent.com/assets/1847581/7415869/6fd46674-ef29-11e4-8f2c-5037c8d511be.png)

**Comment by dgomes2004** [comment]
@davelandry we should hold this one for now. The idea is to have logos from the data source also, and some partners inside and outside the government. So, we will have more, and hopefully, many more logos to add. Considering this, we will need to figure out where and how to add them, once we define which ones will be used and if we will categorize them. Let´s leave the footer as it is for now, ok?

**Comment by davelandry** [comment]
No problem, we'll leave everything as-is until you guys are ready.
