### ISSUE TITLE
Site Down - 500 Error

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#335]
![image](https://cloud.githubusercontent.com/assets/6808970/7472423/e6e1d3ea-f308-11e4-8658-9702db93c71f.png)

http://en.dataviva.info/apps/builder/occugrid/rais/4mg/c14126/all/cbo/?controls=true&year=2013&size=required&order=name

**Comment by davelandry** [comment]
Seems to be an issue with AWS, @mariohmol and I are working on a solution.

**Comment by davelandry** [comment]
Everything is back up and running now. The site was pointing to a database instance that @mariohmol deleted Monday night, so errors were appearing only for pages that had not been cached yet.

We switched the site to point to the correct database, but it wasn't until @alexandersimoes restarted the entire AWS instance that the changes went into effect. We will be monitoring the site very closely the next few days to make sure nothing else is broken.
