### ISSUE TITLE
Change "Exportações a <bra>" to "Exportações de <bra>" in PT

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#338]
![image](https://cloud.githubusercontent.com/assets/6808970/7632650/8fc5a20c-fa25-11e4-8c8a-822b261b2fe5.png)

http://pt.dataviva.info/apps/builder/tree_map/secex/4mg/all/all/hs/?color=color&depth=hs_6&size=export_val&controls=true&year=2014

**Comment by davelandry** [comment]
Good catch Elton. This was a weird little javascript bug. I've fixed it in the code and it will be fixed in the next server update.
