### ISSUE TITLE
Occugrid occupation names should wrap onto 2 lines

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#339]
![image](https://cloud.githubusercontent.com/assets/6808970/7638282/0e5673b6-fa4a-11e4-83fc-ea6b3211797f.png)

http://pt.dataviva.info/apps/builder/occugrid/rais/4mg08/a01512/all/cbo/?grouping=false&year=2013&order=color&controls=true&size=wage_avg

Furthermore, translations of occupations name appear wrong, see the print below:
![image](https://cloud.githubusercontent.com/assets/6808970/7638383/ad063334-fa4a-11e4-8669-b4d4ba2b1493.png)

**Comment by davelandry** [comment]
@eltonfreitas, what exactly do you mean by "Occupations names not appear complete"? Are you suggesting that we should allow the text to go onto 2 lines so that it does not get cut off with an ellipsis?

I'm also going to create a new bug (#340) for the incorrect translations, as these are 2 separate issues.

**Comment by eltonfreitas** [comment]
@davelandry, it's exactly what you say. When I make a download this viz, the occupation name don't appear, cut some letters. Do you think that allow the text to go onto 2 lines is better solution? I agree with you. Maybe if we use 2 lines can be fix this problem.

**Comment by davelandry** [comment]
Occupation names in the occugrid now resize given the space.

Names that are very very long will probably still be truncated, but there's nothing that can be done about that. The names are restricted to a limited amount of space, especially in Occugrids with a lot of occupations.

Every occupation name is visible, in full, in the tooltip.
