### ISSUE TITLE
Incorrect occupation translations

### ISSUE THREAD

**Issue by davelandry** [DataViva/dataviva-site#340]
As noted by @eltonfreitas in #339:

> http://pt.dataviva.info/apps/builder/occugrid/rais/4mg08/a01512/all/cbo/?grouping=false&year=2013&order=color&controls=true&size=wage_avg

> Furthermore, translations of occupations name appear wrong, see the print below:
> ![](https://cloud.githubusercontent.com/assets/6808970/7638383/ad063334-fa4a-11e4-8669-b4d4ba2b1493.png)

**Comment by davelandry** [comment]
@eltonfreitas, the name you see on the site for "Grandes Trabalhadores plantel de gado" is correct. The name your see in that spreadsheet is the original long name for that occupation, "Trabalhadores na pecuária de animais de grande porte"

When we first launched the site, we had you guys create shorter names for all of the occupations. Columns B and C in that spreadsheet are the short and long English names for that occupation. We only use the shortened names on the site.

Is the Portuguese short name for CBO ID 6231 incorrect?

**Comment by eltonfreitas** [comment]
@davelandry, then, in fact is better use short name for long names, but some short name isn`t cool. You know who made this short name here? Can you send the table to review this short names? I didn`t find this table here.

**Comment by davelandry** [comment]
@eltonfreitas, I'm not sure who originally translated/shortened these names. I believe Escritorio might have hired someone to do all the original translations.

I just sent you an e-mail with a dump of the names direct from the database. You can send me back that list, updated, and I will put it on the site.

**Comment by eltonfreitas** [comment]
Thanks Dave, I'll update.

**Comment by davelandry** [comment]
Fixed today!
