### ISSUE TITLE
GeoMap - colored regions without data

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#345]
A lot of regions are colored, but these regions not exports. See Soybeans example:
![image](https://cloud.githubusercontent.com/assets/6808970/10453921/dbe0f6b8-7186-11e5-9d07-b552b1189d9f.png)

http://en.dataviva.info/apps/builder/geo_map/secex/5sc/021201/all/bra/?color=export_val&controls=true&year=2014

**Comment by eltonfreitas** [comment]
@Gilmardealcantara , fechou essa issue pq?
O problema ainda persiste!
http://dataviva.info/en/build_graph/secex/5sc/021201/all?view=0oq3WjaPZ1&graph=geo_map

**Comment by FredericoVieira** [comment]
@eltonfreitas, esse problema será tratado em uma nova issue #1223.
