### ISSUE TITLE
Error replicate dataviva installation

### ISSUE THREAD

**Issue by poliveiraIPB** [DataViva/dataviva-site#346]
Hi, i´m triyng to install the platform locally., and after following all the readme instructions. When I try to start the server using the command "python run.py runserver", i receive the error:

"2015-10-27 14:55:38,250 INFO sqlalchemy.engine.base.Engine SELECT DATABASE()
2015-10-27 14:55:38,250 INFO sqlalchemy.engine.base.Engine ()
2015-10-27 14:55:38,253 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'character_set%%'
2015-10-27 14:55:38,253 INFO sqlalchemy.engine.base.Engine ()
2015-10-27 14:55:38,254 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'sql_mode'
2015-10-27 14:55:38,254 INFO sqlalchemy.engine.base.Engine ()
2015-10-27 14:55:38,255 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2015-10-27 14:55:38,256 INFO sqlalchemy.engine.base.Engine SELECT ei_yms.year AS ei_yms_year 
FROM ei_yms ORDER BY ei_yms.year DESC 
 LIMIT %s
2015-10-27 14:55:38,256 INFO sqlalchemy.engine.base.Engine (1,)
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from dataviva import app
  File "/home/cipweb/dataviva/dataviva/__init__.py", line 65, in <module>
    __year_range__ = get_or_set_years(view_cache, "general:data_years")
  File "/home/cipweb/dataviva/dataviva/stats/util.py", line 73, in get_or_set_years
    val = compute_table_years(['ei', 'hedu', 'sc', 'secex', 'rais', 'population', 'stats'])
  File "/home/cipweb/dataviva/dataviva/stats/util.py", line 60, in compute_table_years
    max_year = str(get_year(tables[dataset], mode='max'))
  File "/home/cipweb/dataviva/dataviva/stats/util.py", line 38, in get_year
    return table.query.with_entities(table.year).order_by(year_col).first().year
AttributeError: 'NoneType' object has no attribute 'year'"

I unnderstand this error is because the ei tables of the database are empty. But the dump in the readme file don´t have these tables. I create the tables using the script present in "dataviva-scripts/scripts/ei/ei_create_tables.sql".

But how I populate these tables with data, so i can start the server ?

**Comment by jspeis** [comment]
@poliveiraIPB I would recommend importing the [database dump](https://s3-sa-east-1.amazonaws.com/datavivadb/dv2015_db.tar.gz) (note that we recently updated this link) and following the associated instructions from the [README](https://github.com/DataViva/dataviva-site). The data dump has two folders which both need to be imported: one folder is just the schema of the table and the other is the content folder which has the actual data (seems like maybe this one was not imported?). After you decompress the dv2015_db.tar.gz file you should be able to follow the steps from the README to import both the schema and content.

**Comment by poliveiraIPB** [comment]
Yes, i imported the dump, following the associated instructions from the README. And i have imported the two folders. But the problem is that the dump only have information about (ATTRS, HEDU, RAIS,SC and SECEX). And the information about EI tables, is missing, so i create the EI tables  using the script present in "dataviva-scripts/scripts/ei/ei_create_tables.sql". But I unnderstand this error is because the ei tables of the database are empty.

**Comment by jspeis** [comment]
Ah, the issue is with the EI dataset. We were hoping to be able to show that data but in the end we were not able to, so there were vestiges of references to that data in the API, which were just removed in c081b2124cbfec6128e267c20cf3fa07f0cb2d8f. If you pull and try again, you should no longer have that error.

**Comment by poliveiraIPB** [comment]
Hi jspeis, thank you, i could run dataviva locally. But in some links i get sqlachademy erros because, the missing of apps_build table. 
That table isn´t in the dump, but is present in the code at dataviva/apps/models.py. 
It´s another bug ?
Or i really need that table, and how can i get him ?

**Comment by jspeis** [comment]
The app build tables and account tables had not been included with the database bundle -- (they should be and we will update this). In the mean time, here are the links to the missing tables:

* https://s3-sa-east-1.amazonaws.com/datavivadb/apps_build.sql.gz (schema+content)
* https://s3-sa-east-1.amazonaws.com/datavivadb/account_tables.sql  (schema only ;-)

**Comment by poliveiraIPB** [comment]
Ok, thanks one more time.
Now when using the site, i find some more details, like the unknow gini column from several tables.
And the table apps_ui is also missing.
Can you please get me the script for that.

Errors:
Unknown column 'rais_yo.gini' in 'field list'
(1054, "Unknown column 'rais_yb.gini' in 'field list'")
"Table 'apps_ui' doesn't exist")

**Comment by jspeis** [comment]
Looks like we need a new snapshot of the DB. Again for your convenience I am uploading those tables to try and get you setup (you can drop rais_yo and rais_yb). 

https://s3-sa-east-1.amazonaws.com/datavivadb/addtl_tables.sql.gz
