### ISSUE TITLE
Criar dicionário de variáveis

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#355]
O nome do campo não é auto explicativo. Devemos ter um nome de fácil entendimento e além disso um dicionário dos campos das bases de dados do DV.
![image](https://cloud.githubusercontent.com/assets/6808970/11072793/bad701a2-87ce-11e5-8840-aa459e17e36e.png)

**Comment by wartog** [comment]
O dicionário de variáveis já existe dentro do código. Ele esta escrito dentro do pacote translations, não há necessidade de termos isso documentado em outro lugar. Basta aculturar os desenvolvedores a manterem este pacote.

https://github.com/DataViva/dataviva-site/tree/master/dataviva/translations
