### ISSUE TITLE
Gráfico de Barras - Download do gráfico em PNG apresenta problemas

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#356]
![image](https://cloud.githubusercontent.com/assets/6808970/11072907/39ed43e8-87cf-11e5-8968-b0ff6e3c5221.png)

http://pt.dataviva.info/apps/builder/bar/rais/4mg/all/all/bra/?controls=true&year=2013

**Comment by eltonfreitas** [comment]
Mesmo para o TreeMap:

![image](https://cloud.githubusercontent.com/assets/6808970/11072953/739a7ae8-87cf-11e5-9b23-165cad72f675.png)

**Comment by Gilmardealcantara** [comment]
Ao baixar imagens em png o nome do eixo e a escala se sobrepõem.

**Comment by eltonfreitas** [comment]
Good job guys!! Testei o download de todos os gráficos no staging!! Funcionou perfeitamente!! Ah, testei só png.
