### ISSUE TITLE
Disponibilizar mais cruzamentos de dados no Gráfico de Barras

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#365]
Vejam que existe apenas 3 opções de cruzamento de dados:
![image](https://cloud.githubusercontent.com/assets/6808970/11368429/e23c9ee6-92a0-11e5-9454-8c5305e86889.png)
http://pt.dataviva.info/apps/builder/bar/rais/4mg/all/all/bra/?controls=true&year=2013

Precisamos adicionar mais 3:
Distribuição de salários de uma ocupação em uma localidade 
Distribuição de salários de uma industria em uma localidade 
Distribuição de salários de uma industria e uma ocupação em uma localidade

**Comment by Gilmardealcantara** [comment]
Issue incluída no novo plano de conteúdo.
