### ISSUE TITLE
Problema no Zoom do Mapa de Exportações e Importações por Município - Perfil do Estado Rio Grande do Sul

### ISSUE THREAD

**Issue by rafamape** [DataViva/dataviva-site#366]
![image](https://cloud.githubusercontent.com/assets/13002836/11851147/3b9e1cfc-a418-11e5-80d4-f8d2355538a7.png)

http://pt.dataviva.info/profiles/bra/5rs/?app=8

![image](https://cloud.githubusercontent.com/assets/13002836/11851203/8da5beb0-a418-11e5-90c6-2c87b1fe2014.png)

http://pt.dataviva.info/profiles/bra/5rs/?app=17

**Comment by Gilmardealcantara** [comment]
Link da nova versão:
http://dataviva.info/en/build_graph/secex/5rs/all/all?view=XvW2NFa2/n&graph=geo_map
