### ISSUE TITLE
change stacked area chart to line chart

### ISSUE THREAD

**Issue by davelandry** [DataViva/dataviva-site#394]
talked with @cesifoti and he thinks that [this visualization](http://en.dataviva.info/profiles/hs/178703/?app=7) should be a line plot.

It's been a while, but I think the "id" in [this line](https://github.com/DataViva/dataviva-site/blob/master/dataviva/profiles/models.py#L255) would just need to change to `137`.

**Comment by eltonfreitas** [comment]
Good idea, we review it in the new layout (DV3)!!
