### ISSUE TITLE
Planning Region - Wrong numbers?

### ISSUE THREAD

**Issue by mariohmol** [DataViva/dataviva-site#49]
We did some analysis about RCA in different kinds of region: Municipality, Meso, Planning Regions and States.

We could see that for Municipality, Meso and States the numbers looks good, but for Planning Regions looks like that is a problem.

If we take the example of Rio Doce Planning Region x Vale Rio Doce Mesoregion its a good way to check cause these two has the same municipalities. 
![meso](https://cloud.githubusercontent.com/assets/5495763/2635511/5f38a50c-be86-11e3-9096-b1303a3dcd09.png)
![pr](https://cloud.githubusercontent.com/assets/5495763/2635512/5f402a02-be86-11e3-8696-aa49a2a81578.png)

We attached 2 files, one for Planning and other for Meso and is possible to see that the numbers are different, but should be the same. 

Other thing is that the products shown in Planning is less than for Meso, take a look at HS 052507, it can be found at Meso but not at Planning. Maybe this is a tip showing where the bug can be..

**Comment by alexandersimoes** [comment]
The problem with all of the calculations for planning regions (rca, rcd, distance, opportunity gain etc) is that the denominator for the RCA calculation is the total for Minas and NOT all of Brazil which is the case for all of the other geographic nestings e.g. states, meso regions, municipalities etc.. The reason for this is that we only have planning regions for Minas and not the other states.

**Comment by davelandry** [comment]
I am closing this issue, as this cannot be changed unless we have planning regions for every state.
