### ISSUE TITLE
Justificar os textos dos perfis de usuários

### ISSUE THREAD

**Issue by mpinho** [DataViva/dataviva-site#558]
Justificar os textos de explicação dos perfis.

Atual:
![image](https://cloud.githubusercontent.com/assets/15732270/13811779/a033ec2a-eb56-11e5-89f0-e792292c6982.png)

Proposta:
![image](https://cloud.githubusercontent.com/assets/15732270/13811836/017bb30a-eb57-11e5-97ca-c58c67f99ec0.png)

**Comment by eltonfreitas** [comment]
Ajustar o texto para ficar a direita da imagem, como indicado na proposta.

**Comment by AnaCarolinaFDias** [comment]
Isso vai ser feito com a Designer.

**Comment by AnaCarolinaFDias** [comment]
@diogolundberg Não esquece de passar isso para a Nathália.
