### ISSUE TITLE
Comtrade Updates

### ISSUE THREAD

**Issue by mariohmol** [DataViva/dataviva-site#63]
We sent Comtrade 2011 and we have Comtrade 2012 as well.

Have you used new data for comtrade to test calc new indicators?

Can you tell if this comtrade data have enought data to make new calcs? 
Because we know that the countries takes a while to send all data.. like.. is at least the same amount from the year before (2011) ? is that enought to make all the calcs from 2012 based in this comtrade?

Are we planning to use those data in Dataviva?

**Comment by alexandersimoes** [comment]
We are now using COMTRADE/Baci cleaned data from 2012 and earlier.
