### ISSUE TITLE
Not show unreported categories

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#672]
![image](https://cloud.githubusercontent.com/assets/6808970/14474067/85318a82-00d1-11e6-9171-378ee2ef9032.png)

![image](https://cloud.githubusercontent.com/assets/6808970/14474091/a2e4a3b6-00d1-11e6-81ff-68c1cde96119.png)

**Comment by diogolundberg** [comment]
Related to #478

**Comment by eltonfreitas** [comment]
Ocupações: Ocultar escolha de Não Declarada
![image](https://cloud.githubusercontent.com/assets/6808970/14886569/c5b4aeb0-0d27-11e6-861f-158f633e066c.png)
![image](https://cloud.githubusercontent.com/assets/6808970/14886596/eb51f7cc-0d27-11e6-9456-98e7a3545bae.png)


Produtos: Ocultar escolha de Não Especificado
![image](https://cloud.githubusercontent.com/assets/6808970/14886612/058b07aa-0d28-11e6-9683-1ce013fba390.png)
![image](https://cloud.githubusercontent.com/assets/6808970/14886628/1e9aaf2a-0d28-11e6-8a73-c1c1333a7526.png)


Parceiros Comerciais:
![image](https://cloud.githubusercontent.com/assets/6808970/14886647/3d11950e-0d28-11e6-8be7-8d57a2a8ccf4.png)

Ensino Superior:
![image](https://cloud.githubusercontent.com/assets/6808970/14886679/738629c4-0d28-11e6-8cf2-e87d66d26b00.png)
