### ISSUE TITLE
Data Section not showing all info

### ISSUE THREAD

**Issue by mariohmol** [DataViva/dataviva-site#70]
Some filters in data section shows all the information, for example:

If you filter by SECEX and HS by position, you will see info for distance, RCA and others.
http://dataviva.info/data/secex/2012/rs041005.show.8/show.6/all/

But if you make the same filter and changing just the HS by section, it do not show. Is possible to see that it shows only numbers that have exports:
http://dataviva.info/data/secex/2012/rs041005.show.8/show.2/all/

The same occurs if you filter by Municipality or State:
If you filter by State it not shows:
* http://dataviva.info/data/secex/2012/show.2/021205.show.6/all/

But if you change to Municipality it shows:
http://dataviva.info/data/secex/2012/show.8/021205.show.6/all/

The ideia is to have showing data at all times, so necessary to make some analysis if it can occurs in others filters examples.

In some case there is no Export Value for certaind product in a local, but even so should show other values as distance, complexity...

**Comment by alexandersimoes** [comment]
Hey guys, I was unable to reproduce this bug, if it pops up again feel free to re-open this but for now I believe it was taken care of when we reran the new scripts with monthly secex data.
