### ISSUE TITLE
Rankings: which option is selected?

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#700]
Let better which option was selected!!
![image](https://cloud.githubusercontent.com/assets/6808970/14613343/56fe3c5a-0572-11e6-8394-799fc09c4711.png)

**Comment by eltonfreitas** [comment]
Same case to:
![image](https://cloud.githubusercontent.com/assets/6808970/14614248/a1a6216a-0576-11e6-8e59-72b7c7cb83ac.png)

**Comment by VictorDMor** [comment]
Corrigido.

**Comment by eltonfreitas** [comment]
http://develop.dataviva.info/en/#
<img width="1206" alt="screen shot 2016-04-22 at 09 56 55" src="https://cloud.githubusercontent.com/assets/6808970/14742059/a993d988-0870-11e6-8c3d-e98c9136a649.png">

Apenas nos Rankings isso está corrigido.
<img width="1221" alt="screen shot 2016-04-22 at 09 59 31" src="https://cloud.githubusercontent.com/assets/6808970/14742134/f630aa6e-0870-11e6-9580-91da5c99faad.png">

**Comment by VictorDMor** [comment]
O selector foi reformulado e já contempla a modificação.

**Comment by eltonfreitas** [comment]
@lauradebella a bola está com vc?!
