### ISSUE TITLE
50/50 "Unclassified" product error

### ISSUE THREAD

**Issue by mariohmol** [DataViva/dataviva-site#71]
In some cases there is exports for a city but not showing for States.

So when this happens it makes this chart showing weird visualisations. 

http://dataviva.info/apps/builder/tree_map/secex/all/021109/all/bra/?depth=bra_8&value_var=val_usd&color_var=color&controls=true&year=2012

Maybe is related to #49 

Here is some products that gives that error:
21109, 21205, 115306,178605,189005, 189108 

![citiesdata](https://cloud.githubusercontent.com/assets/5495763/2959741/f3514e92-dab5-11e3-8907-3d7a08ce1a12.png)

Here is a example that shows a value for municipality and other for state that doesnt show

![giruatem](https://cloud.githubusercontent.com/assets/5495763/2960955/7ad986bc-dac1-11e3-8ae5-0446179908e3.png)

![rgsnaotem](https://cloud.githubusercontent.com/assets/5495763/2960961/832162f4-dac1-11e3-900b-9db373173997.png)

**Comment by davelandry** [comment]
Confirmed fixed.
