### ISSUE TITLE
Acrescentar um botão voltar após selecionar uma opção em inicie uma pesquisa > por público > “opção escolhida”?

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#711]
Há apenas 2 opções Avançar e Cancelar. Voltar é importante para ir à opção anterior.
Além disso, melhorar a indicação de que o item escolhido está selecionado, está gerando dúvidas se a opção foi selecionada ao clicar.
![image](https://cloud.githubusercontent.com/assets/6808970/14642227/0ebc7a48-0620-11e6-9e26-55450fbf8076.png)
http://staging.dataviva.info/pt/inicie-uma-pesquisa/

**Comment by AnaCarolinaFDias** [comment]
Relacionada #907
