### ISSUE TITLE
"Mais detalhes" não funciona

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#713]
Se a pessoa clica em “mais detalhes” em http://staging.dataviva.info/pt/industry/a?bra_id=1 (não apenas na id=1 mas em todas as ids) não exibe a visualização e nem indica que Salário e Emprego está marcado.
“mais detalhes” e “salário e emprego” deveriam abrir a mesma coisa?
![image](https://cloud.githubusercontent.com/assets/6808970/14642342/78e995ea-0620-11e6-8676-63761eee3f34.png)

**Comment by VictorDMor** [comment]
Corrigido.
