### ISSUE TITLE
USD em números absolutos

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#717]
Na descrição de salário e emprego o símbolo USD em “Ocupação com maior número de empregos” e “ Município com maior número de empregos” não deveria aparecer, já que se trata de números absolutos.
![image](https://cloud.githubusercontent.com/assets/6808970/14643256/14181cf0-0624-11e6-9091-b56f4fdb4538.png)
http://staging.dataviva.info/pt/industry/b?bra_id=3

**Comment by VictorDMor** [comment]
Corrigido. Foi retirada a cifra de dólares dos valores absolutos, já foi feito o push no branch develop.

**Comment by eltonfreitas** [comment]
@VictorDMor o problema ainda está na vesão develop:
http://develop.dataviva.info/pt/industry/b?bra_id=3

**Comment by eltonfreitas** [comment]
#789
