### ISSUE TITLE
Busca feita em português, mas resultado exibido em Inglês

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#729]
Faço a busca em Português e no segundo e terceiro passo (escolha um setor industrial / escolha uma região)  e o resultado sai em inglês. 
![image](https://cloud.githubusercontent.com/assets/6808970/14683629/1819e14c-0702-11e6-832f-43ab2b73a67b.png)
Link:  http://staging.dataviva.info/pt/
![image](https://cloud.githubusercontent.com/assets/6808970/14683636/2234f5e0-0702-11e6-9348-d5ad1a4ef48a.png)

**Comment by eltonfreitas** [comment]
No caminho inverso, quando faço a pesquisa em inglês, nos próximos passos, as perguntas estão em português.
Link: http://staging.dataviva.info/en/
![image](https://cloud.githubusercontent.com/assets/6808970/14683830/34e2a6d2-0703-11e6-962b-730b883f5aec.png)

**Comment by AnaCarolinaFDias** [comment]
Para o caso da pesquisa em inglês a tradução esta no arquivo do redmine: http://redmine.is2codes.com/issues/392.  Pagina 4.
