### ISSUE TITLE
Missing Value for Exports Should Show $0,00

### ISSUE THREAD

**Issue by mariohmol** [DataViva/dataviva-site#73]
In some cases there isnt a value for a indicator, like for the Exports.

It means that the export in that case is $ 0,00 and not N/A.

The concept for Not Available fits in the case of Distance, Complexity, RCA, Opp Gain and others.. but in case of exports should show $ 0,00.

Related to the issue #52 

Some cases it shows number 0,00  (showing distances as well) but others no. 

Not showing:
![state](https://cloud.githubusercontent.com/assets/5495763/2960813/ce69d3ba-dabf-11e3-86bf-2ad2988ab93b.png)

Showing part of the data:
![statedata](https://cloud.githubusercontent.com/assets/5495763/2960820/d5b39d22-dabf-11e3-8371-812228a522f6.png)

Here showing all data:
![moredata](https://cloud.githubusercontent.com/assets/5495763/2960824/e2ce6fb4-dabf-11e3-9ba7-7cba45f74d6c.png)

**Comment by davelandry** [comment]
The visualizations on the new platform now fill in zero values for exports.
