### ISSUE TITLE
Trocar Bandeira dos Estado por Imagem (mapa) de cada Estado

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#730]
Sugestão de layout: embora visualmente tenha ficado bonito o Estado ser representado pela bandeira, na busca por município, microrregião e mesorregião, achei que não ficou muito intuitivo para alguém que queira buscar textualmente um destes dados.
![image](https://cloud.githubusercontent.com/assets/6808970/14683866/658b230e-0703-11e6-846a-ef379e8e4344.png)

**Comment by eltonfreitas** [comment]
Na tela abaixo, fica demostrada a ausência da sigla do Estado. Nos anos 2012 a 2014, há duas cidades de Bom Jesus (cada uma tem um código do IBGE). Mas para você saber de qual “bom Jesus” se trata, será preciso procurar no site do IBGE pelo código.
Link: http://staging.dataviva.info/pt/rankings/
![image](https://cloud.githubusercontent.com/assets/6808970/14690578/1c4318ee-0723-11e6-9188-cb911bcc6d03.png)

**Comment by Gilmardealcantara** [comment]
As siglas serão adicionadas para municípios mesorregião e microrregião  ou somente municípios ?

**Comment by AnaCarolinaFDias** [comment]
@eltonfreitas Elton, nesse caso não mudamos a imagem como sugerido no Titulo, apenas colocamos a sigla do Estado na frente, como você tinha me falado.

**Comment by eltonfreitas** [comment]
Aqui não foi colocado?
![image](https://cloud.githubusercontent.com/assets/6808970/14926940/4812bbe2-0e25-11e6-9f46-46839c0f3a11.png)

**Comment by eltonfreitas** [comment]
@Gilmardealcantara Siglas em tudo com bra_id_len maior que 3!!
