### ISSUE TITLE
Mais problemas com padrão de texto e números

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#736]
Link para verificarem o problema: http://develop.dataviva.info/pt/occupation/1223

a. No texto “a renda mensal média é de 8889.23”, deveria ser “R$ 8.889,23”.

b. Principal município por empregos e principal atividade por empregos está em USD, deveria ser um número absoluto.

c. Sugiro que toda a menção a municípios, como na tela abaixo “Nossa Senhora do Socorro”, venha acompanhado da sigla do Estado “Nossa Senhora do Socorro/SE”, posto que é impossível para alguém saber em que estado ficam cada município brasileiro, o que o obriga a consultar este dado no Google e também porque há municípios com mesmo nome em Estados diferentes, conforme se vê na reportagem http://g1.globo.com/brasil/noticia/2014/04/uma-em-cada-11-cidades-do-pais-tem-uma-homonima.html

![image](https://cloud.githubusercontent.com/assets/6808970/14684635/5487100a-0707-11e6-9dd5-ea82a577dc49.png)

**Comment by VictorDMor** [comment]
Elton, sobre o item c, a sigla só vai vir acompanhada se for município mesmo? Pra mesorregião, microrregião não se aplica?
