### ISSUE TITLE
USD, Número incorreto e falta de unidade de Medida

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#742]
MG tem 853 municípios e não 854, como diz a tela abaixo.
Qual a unidade de medida de “principal atividade econômica”? 696 o que?
A Unidade de medida de total de empregos, em USD, está incorreta.
Link: http://staging.dataviva.info/pt/location/4mg010001
![image](https://cloud.githubusercontent.com/assets/6808970/14685224/21e74716-070a-11e6-812b-59f2c5451334.png)

**Comment by eltonfreitas** [comment]
Ver issue #789 para ajustar as unidades de medidas.

**Comment by AnaCarolinaFDias** [comment]
Elton vou fechar essa Issue com base no perfil localidades. Convém ainda conferir as unidades de medidas de forma mais precisa como a gente conversou e colocar numa Issue indicando onde deve ser corrigido.
