### ISSUE TITLE
Erros no texto

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#753]
http://staging.dataviva.info/pt/help/

O que é o DataViva?
O DataViva é uma ferramenta de visualização que disponibiliza dados oficiais sobre exportações, atividades econômicas, localidades e ocupações de todo o Brasil, em onze **visualizações**  (substituir por "gráficos") e mais de 100 milhões de **visualizações**.

Por meio de suas visualizações, o DataViva fornece informações valiosas para a promoção das exportações, para decisões de investimentos e formulação de políticas públicas. Além disto, ao fornecer **fatos** (substituir por dados) sobre o desenvolvimento econômico e educação, localidades e suas respectivas oportunidades, o DataViva ajuda a criar uma base sólida para o diálogo entre o setor público e o privado, fundamentada por dados empíricos.

**Comment by eltonfreitas** [comment]
@Gilmardealcantara mais uma vez, quando a issue é fecha significa que além de corrigido já está no online para teste? Pois não está:
<img width="1191" alt="screen shot 2016-04-22 at 08 44 26" src="https://cloud.githubusercontent.com/assets/6808970/14740591/805ed4b4-0866-11e6-8618-e439b8254dd0.png">

**Comment by VictorDMor** [comment]
Corrigido.

**Comment by eltonfreitas** [comment]
Poh galera, mais atenção!! A gente não pode ficar fechando e reabrindo issue assim.
A Issue indica trocar Visualizações por Gráficos e Fatos por Dados. Mas somente um foi trocado!! Essa Issue foi fechada 3 vezes sem ser resolvida. Vamos ter mais atenção.

**Comment by AnaCarolinaFDias** [comment]
A alteração que o Elton solicitou em visualizações (substituir por "gráficos"), a palavra gráfico esta sem acento na hora que terminarem de fazer o que falta que está descrito abaixo por favor corrijam isso  também. 

Nessa Issue falta apenas substituir fatos por dados em:

Por meio de suas visualizações, o DataViva fornece informações valiosas para a promoção das exportações, para decisões de investimentos e formulação de políticas públicas. Além disto, ao fornecer **fatos (substituir por dados)** sobre o desenvolvimento econômico e educação, localidades e suas respectivas oportunidades, o DataViva ajuda a criar uma base sólida para o diálogo entre o setor público e o privado, fundamentada por dados empíricos.
