### ISSUE TITLE
O item cinza é um número “3135295”

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#755]
O item cinza é um número “3135295”
Link: http://staging.dataviva.info/pt/location/4mg
![image](https://cloud.githubusercontent.com/assets/6808970/14690970/25ade768-0725-11e6-8baa-3de68af755b8.png)

**Comment by sauloantuness** [comment]
Falta icones na legenda: [Universidade -> TreeMap](http://dataviva.info/pt/location/4mg/education?menu=higher-education-university-tree_map&url=tree_map%2Fhedu%2F4mg%2Fall%2Fall%2Funiversity%2F%3Fcolor%3Dcolor%26depth%3Duniversity_5%26size%3Denrolled)
