### ISSUE TITLE
Atualizar logomarca dos parceiros, conforme ordem abaixo e figuras tratadas e enviadas pelo Felipe.

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#758]
•	BigData Corp.
•	MIT Media Lab
•	SIMI
![image](https://cloud.githubusercontent.com/assets/6808970/14691077/a108f7c2-0725-11e6-812b-7bcad7679adb.png)

**Comment by VictorDMor** [comment]
Corrigido.
