### ISSUE TITLE
Refazer o link para o site da FAPEMIG, que foi remodelado

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#761]
Refazer o link para o site da FAPEMIG, que foi remodelado (enviarei o link correto assim que estiver disponível) e retirar os links de teste.
![image](https://cloud.githubusercontent.com/assets/6808970/14691159/0c9ca89e-0726-11e6-9d73-15b82a004dd0.png)

**Comment by AnaCarolinaFDias** [comment]
Elton favor o link correto para que essa Issue seja feita.

**Comment by eltonfreitas** [comment]
@rafamape pode passar esse link para @AnaCarolinaFDias ?

**Comment by rafamape** [comment]
O link no novo site da FAPEMIG ainda não foi restabelecido. Vou verificar isso e quando estiver no ar eu encaminho.

**Comment by rafamape** [comment]
http://www.fapemig.br/pt-br/arquivos/site/chamadas/resultado/resultado-do-julgamento-das-propostas.pdf

**Comment by AnaCarolinaFDias** [comment]
Obrigada @rafamape
