### ISSUE TITLE
Inserir link para Deliberação do Conselho sobre Parceria ou fazer Upload do arquivo

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#762]
http://www.fapemig.br/pt-br/visualizar/ler/39/92-de-01-12-15-parcerias-dataviva

**Comment by AnaCarolinaFDias** [comment]
@eltonfreitas eu preciso saber se é para colocar o link ou fazer o upload do arquivo, e aonde colocar isso vai ser nessa página? http://develop.dataviva.info/pt/partners/

**Comment by eltonfreitas** [comment]
Carol, "linka" esse endereço que passei no trecho que está destacado:
![image](https://cloud.githubusercontent.com/assets/6808970/14885071/9dc53dd2-0d1f-11e6-99a4-b01673000ca0.png)
