### ISSUE TITLE
Traduzir os textos - Be a partner

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#764]
http://staging.dataviva.info/en/partners/be-a-partner
![image](https://cloud.githubusercontent.com/assets/6808970/14691207/5e107386-0726-11e6-99d8-68dcaa483001.png)

**Comment by diogolundberg** [comment]
No documento fornecido pela Tino não tem esse conteúdo em inglês. @AnaCarolinaFDias favor providenciar com a Tino ou Fapemig (Lucas).
