### ISSUE TITLE
Ajustes no Sobre

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#765]
http://staging.dataviva.info/pt/about/
1) Justificar textos
2) Retirar a vírgula do texto lateral (estava no texto aprovado, estamos corrigindo agora): DataViva é uma plataforma aberta de pesquisa, que permite ao usuário acessar mais de 1 bilhão de visualizações com dados socioeconômicos dos mais de 5 mil municípios brasileiros.
![image](https://cloud.githubusercontent.com/assets/6808970/14691237/83d0b2fc-0726-11e6-9f21-2623b8ea9abd.png)

**Comment by VictorDMor** [comment]
O texto foi justificado. A vírgula precisa de ser passada pela tradução já que o texto original do HTML está em inglês.

**Comment by rafamape** [comment]
Não ficou evidente no print enviado, mas é necessário justificar o texto abaixo do vídeo também.

**Comment by AnaCarolinaFDias** [comment]
@VictorDMor  pode refazer esse por favor?
