### ISSUE TITLE
Substituir no texto “Ministério do Trabalho e Emprego” por “Ministério do Trabalho e Previdência Social” –

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#766]
Houve uma reforma ministerial entre a aprovação dos textos e hoje.
![image](https://cloud.githubusercontent.com/assets/6808970/14691267/ae10a59a-0726-11e6-9620-7c45ff581a01.png)

**Comment by VictorDMor** [comment]
Resolvido. Já foi feito o push

**Comment by eltonfreitas** [comment]
@VictorDMor quando vc diz: "já foi feito o push", isso significa que já está atualizado no staging ou no develop?
Develop:
<img width="843" alt="screen shot 2016-04-22 at 08 37 07" src="https://cloud.githubusercontent.com/assets/6808970/14740457/8b68beca-0865-11e6-9898-f7f69be04984.png">
Staging:
<img width="815" alt="screen shot 2016-04-22 at 08 38 43" src="https://cloud.githubusercontent.com/assets/6808970/14740480/ae695e70-0865-11e6-92bc-ad452a4716a1.png">

**Comment by eltonfreitas** [comment]
Rever:
http://develop.dataviva.info/pt/about/

**Comment by VictorDMor** [comment]
Na versão em inglês já está funcionando, porém em português persiste o nome errado. É preciso alterar a tradução para efetuar a mudança no portal em PT.

**Comment by eltonfreitas** [comment]
@lauradebella a bola está com vc!?

**Comment by eltonfreitas** [comment]
Pô galera, atenção aí
