### ISSUE TITLE
Unidades de Medida que devem ser utilizadas

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#789]
•	**PIB**: medido em **R$ **
•	**Esperança de vida ao nascer**: medido em **anos**
•	**População (Censo 2010)**: medido em **habitantes**
•	**PIB per capta**: medida em **R$**
•	**IDHM**: não precisa de unidade de medida
•	**Índice de Complexidade Econômica**: não precisa de unidade de medida
•	**Renda Média Mensal**: medido em **R$**
•	**Massa Salarial**: medido em **R$**
•	**Total de Empregos**: não precisa de unidade de medida
•	**Total de Estabelecimentos**: não precisa de unidade de medida
•	**Total de Empregos**: não precisa de unidade de medida
•	**Total de Estabelecimentos**: não precisa de unidade de medida
•	**RCA doméstico**: não precisa de unidade de medida
•	**Distância**: não precisa de unidade de medida
•	**Ganho de Oportunidade**: não precisa de unidade de medida
•	**Saldo da Balança Comercial**: medido em **US$**
•	**Valor Total Exportado**: medido em US$
•	**Preço Médio Exportado (US$/Kg)**: medido em **US$/Kg**
•	**Valor Total Importado**: medido em **US$**
•	**Preço Médio Importado (US$/Kg)**: medido em US$/Kg
•	**Índice de Complexidade do Produto**: não precisa de unidade de medida 
•	**RCA internacional**: não precisa de unidade de medida
•	**Distância internacional**: não precisa de unidade de medida
•	**Ganho de Oportunidade internacional**: não precisa de unidade de medida
•	**Número de Matrículas**: medido em **alunos**
•	**Número de Ingressantes**: medido em **alunos**
•	**Número de Concluintes**: medido em **alunos**
•	**Número de Turmas**: não precisa de unidade de medida
•	**Número de Escolas**: não precisa de unidade de medida
•	**Tamanho Médio das Turmas**: medido em **alunos**
•	**Idade Média**: medido em **anos**

**Comment by AnaCarolinaFDias** [comment]
@eltonfreitas Instruções desse tipo, favor colocar na Wiki. 
É melhor ficar lá, ai você fecha essa issue por favor.
