### ISSUE TITLE
D3 -Trocar nomes dos indicadores RELAÇÃO PESO LÍQUIDO / VALOR TOTAL

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#791]
Onde aparecer esses indicadores, trocar o nome como indicado abaixo:

RELAÇÃO PESO LÍQUIDO / VALOR TOTAL EXPORTADO -> Preço Médio Exportado (US$/Kg)
RELAÇÃO PESO LÍQUIDO / VALOR TOTAL IMPORTADO -> Preço Médio Importado (US$/Kg)

ATENÇÃO: garantir que o indicador que está aparecendo mostra a divisão US$ / Kg e não o contrário (Kg / US$).

**Comment by eltonfreitas** [comment]
Fazer o mesmo nesse casos, onde aparecer Exportações por Peso ou Importações por Peso:
![image](https://cloud.githubusercontent.com/assets/6808970/14884798/b51341ca-0d1d-11e6-996f-f44814e0787b.png)

**Comment by AnaCarolinaFDias** [comment]
Essa Issue inclui modificação no gráfico, é preciso mexer no D3. Deixaremos para depois.
