### ISSUE TITLE
Visualizações do Perfil Localidade

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#794]
Todos os Exemplos de links consideram MG como escolha.
**1. Comércio Internacional**:

- Balança Comercial
 - Exibir um gráfico de Linhas com (http://goo.gl/uyRncA):
   - [x] Escala: Linear
    - [x] Agregação: Exportações/Importações
    - [x] Resolução Temporal: Ano.

- Exportações por 
 - **Produto**
   - TreeMap com (http://goo.gl/mv1DmK):
    - [ ] Retirar tamanho como opção de escolha, exibir somente Exportações;
     - [x] Agregação: Posição;
     - [x] Cor: Setor;
     - [x] Ano: Mais recente disponível.
    - Evolução com (http://goo.gl/yC6KgX):
     - [ ] Retirar Eixo Y como opção de escolha, exibir somente Exportações;
     - [x] Ordem: Setor;
     - [x] Cor: Setor;
     - [x] Layout: Valor;
     - [x] Resolução Temporal: Ano.
 - **Destino**
   - TreeMap com (http://goo.gl/0MftHX):
    - [ ] Retirar tamanho como opção de escolha, exibir somente Exportações;
     - [x] Agregação: País;
     - [x] Ano: Mais recente disponível.
    - Evolução com (http://goo.gl/57PPlK):
     - [ ] Retirar Eixo Y como opção de escolha, exibir somente Exportações;
     - [x] Ordem: Setor;
     - [x] Cor: Setor;
     - [x] Layout: Valor;
     - [x] Resolução Temporal: Ano.
 - **Municípios** (SOMENTE QUANDO FOR ESCOLHIDA UMA REGIÃO DIFERENTE DE MUNICÍPIO)
   - TreeMap com (http://goo.gl/W5J40i):
    - [ ] Retirar tamanho como opção de escolha, exibir somente Exportações;
     - [x] Agregação: Município;
     - [x] Ano: Mais recente disponível.
    - Evolução com (http://goo.gl/mNxA9M):
     - [ ] Retirar Eixo Y como opção de escolha, exibir somente Exportações;
     - [x] Ordem: Setor;
     - [x] Cor: Setor;
     - [x] Layout: Valor;
     - [x] Resolução Temporal: Ano.

- Importações por 
 - **Produto**
   - TreeMap com (http://goo.gl/2nx8BT):
    - [ ] Retirar tamanho como opção de escolha, exibir somente Importações;
     - [x] Agregação: Posição;
     - [x] Cor: Setor;
     - [x] Ano: Mais recente disponível.
    - Evolução com (http://goo.gl/C0gjtk):
     - [ ] Retirar Eixo Y como opção de escolha, exibir somente Importações;
     - [x] Ordem: Setor;
     - [x] Cor: Setor;
     - [x] Layout: Valor;
     - [x] Resolução Temporal: Ano.
 - **Origem**
   - TreeMap com (http://goo.gl/dtMgd0):
    - [ ] Retirar tamanho como opção de escolha, exibir somente Importações;
     - [x] Agregação: País;
     - [x] Ano: Mais recente disponível.
    - Evolução com (http://goo.gl/nyFuZ4):
     - [ ] Retirar Eixo Y como opção de escolha, exibir somente Importações;
     - [x] Ordem: Setor;
     - [x] Cor: Setor;
     - [x] Layout: Valor;
     - [x] Resolução Temporal: Ano.
 - **Municípios** (SOMENTE QUANDO FOR ESCOLHIDA UMA REGIÃO DIFERENTE DE MUNICÍPIO)
   - TreeMap com (http://goo.gl/IkXQlU):
    - [ ] Retirar tamanho como opção de escolha, exibir somente Importações;
     - [x] Agregação: Município;
     - [x] Ano: Mais recente disponível.
    - Evolução com (http://goo.gl/R2Jbk4):
     - [ ] Retirar Eixo Y como opção de escolha, exibir somente Importações;
     - [x] Ordem: Setor;
     - [x] Cor: Setor;
     - [x] Layout: Valor;
     - [x] Resolução Temporal: Ano.

**Comment by eltonfreitas** [comment]
2. Salário e Emprego:

- Emprego por 
 - **Atividade Econômica**
   - TreeMap com:
    - [ ] Tamanho: Total de Empregos;
     - [ ] Agregação: Classe;
     - [ ] Cor: Setor;
     - [ ] Ano: Mais recente disponível.
    - Evolução com:
     - [ ] Eixo Y: Total de Empregos;
     - [ ] Ordem: Setor;
     - [ ] Cor: Setor;
     - [ ] Layout: Valor;
 - **Ocupação**
   - TreeMap com:
    - [ ] Tamanho: Total de Empregos;
     - [ ] Agregação: Família;
     - [ ] Cor: Setor;
     - [ ] Ano: Mais recente disponível.
    - Evolução com:
     - [ ] Eixo Y: Total de Empregos;
     - [ ] Ordem: Setor;
     - [ ] Cor: Setor;
     - [ ] Layout: Valor;


- Massa Salarial por 
 - **Atividade Econômica**
   - TreeMap com:
    - [ ] Tamanho: Renda Mensal Total;
     - [ ] Agregação: Classe;
     - [ ] Cor: Setor;
     - [ ] Ano: Mais recente disponível.
    - Evolução com:
     - [ ] Eixo Y: Renda Mensal Total;
     - [ ] Ordem: Setor;
     - [ ] Cor: Setor;
     - [ ] Layout: Valor;
 - **Ocupação**
   - TreeMap com:
    - [ ] Tamanho: Renda Mensal Total;
     - [ ] Agregação: Família;
     - [ ] Cor: Setor;
     - [ ] Ano: Mais recente disponível.
    - Evolução com:
     - [ ] Eixo Y: Renda Mensal Total;
     - [ ] Ordem: Setor;
     - [ ] Cor: Setor;
     - [ ] Layout: Valor;

**Comment by eltonfreitas** [comment]
**3. Oportunidades Econômicas**:

- **Espaço de Produtos** 
   - Rede com:
    - [ ] Tamanho: Exportações;
     - [ ] Realçar RCA: Liga;
     - [ ] Escopo RCA: Internacional;
     - [ ] Cor: Setor;
     - [ ] Ano: Mais recente disponível.
    - Dispersão com:
    - [ ] Tamanho: Exportações;
     - [ ] Esconder RCA: Desliga;
     - [ ] Escopo RCA: Internacional;
     - [ ] Agregação: Seção;
     - [ ] Cor: Setor;
     - [ ] Eixo Y: Complexidade do Produto;
     - [ ] Eixo X: Distância;
     - [ ] Ano: Mais recente disponível.

- **Espaço de Atividades** 
   - Rede com:
    - [ ] Tamanho: Total de Empregos;
     - [ ] Realçar RCA: Liga;
     - [ ] Cor: Setor;
     - [ ] Ano: Mais recente disponível.
    - Dispersão com:
    - [ ] Tamanho: Total de Empregos;
     - [ ] Esconder RCA: Desliga;
     - [ ] Agregação: Seção;
     - [ ] Cor: Setor;
     - [ ] Eixo Y: Diversidade Efetiva de Ocupações;
     - [ ] Eixo X: Distância;
     - [ ] Ano: Mais recente disponível.

**Comment by eltonfreitas** [comment]
**4. Educação**:

- Ensino Superior por 
 - **Universidades**
   - TreeMap com:
    - [ ] Tamanho: Matrículas;
     - [ ] Cor: Setor;
     - [ ] Ano: Mais recente disponível.
 - **Cursos**
   - TreeMap com:
    - [ ] Tamanho: Matrículas;
     - [ ] Agregação: Curso;
     - [ ] Cor: Setor;
     - [ ] Ano: Mais recente disponível.

- Educação Profissional por 
 - **Escolas**
    - [ ] Tamanho: Matrículas;
     - [ ] Cor: Setor;
     - [ ] Ano: Mais recente disponível.
 - **Cursos**
   - TreeMap com:
    - [ ] Tamanho: Matrículas;
     - [ ] Agregação: Curso;
     - [ ] Cor: Setor;
     - [ ] Ano: Mais recente disponível.

- Educação Básica por 
 - **Dependência Administrativa**
    - [ ] Tamanho: Matrículas;
     - [ ] Cor: Setor;
     - [ ] Ano: Mais recente disponível.
 - **Nível de Ensino**
   - TreeMap com:
    - [ ] Tamanho: Matrículas;
     - [ ] Cor: Setor;
     - [ ] Ano: Mais recente disponível.

**Comment by AnaCarolinaFDias** [comment]
Issues relacionadas a Visualização Perfil Localidade - Mostrando municípios quando deveria mostrar países. #740 
O item cinza é um número “3135295” #755
Tela mistura português com inglês. #743
USD, Número incorreto e falta de unidade de Medida #742
Mostrando origem quando deveria mostrar destinos. #739 
Exportações por destinos (evolução), título indica Bom Despacho mas exibe Minas #738

**Comment by AnaCarolinaFDias** [comment]
Distinguir opções de Gráfico em perfis #756
