### ISSUE TITLE
Qual view está marcada?

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#800]
No perfil quando selecionamos as opções para ver os gráficos já abre um gráfico de cara, no entanto, não há indicação na caixa lateral a esquerda qual view é mostrada.
<img width="1216" alt="screen shot 2016-04-22 at 12 55 07" src="https://cloud.githubusercontent.com/assets/6808970/14747238/8413ee32-0889-11e6-9b2a-93d5e6c8f2ad.png">

**Comment by FredericoVieira** [comment]
js:
if ($('.list-group div').first().hasClass('collapse')){
    $('.list-group div').first().removeClass('collapse').addClass('collapse in').attr('aria-expanded', 'true').removeAttr('style');
    $('.list-group div a').first().toggleClass("active");
    $('.list-group-item').click(function(){
       $('.list-group div a').first().removeClass('active');
   });
}
else {
    $('.list-group a').first().toggleClass("active");
    $('.list-group-item').click(function(){
       $('.list-group a').first().removeClass('active');
   });
}

css:
.category .list-group-item.active{
 background: #5a9dc4 ;
 color: #FFF;
}
