### ISSUE TITLE
Perfil Localidade p/ Brasil

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#836]
**Indicadores Header:**
•	PIB;
select sum(stat_val) from attrs_ybs where year = 2010 and length(bra_id) = 1 and stat_id='gdp'; 
•	População (Censo 2010);
select sum(population) from attrs_yb where year = 2010 and length(bra_id) = 1; 
•	PIB per capta; 
Dividir PIB pela População
•	Índice de Complexidade Econômica
Puxar do Atlas: http://atlas.media.mit.edu/en/profile/country/bra/

**Texto:**
O Brasil é a 7ª maior economia mundial e 56ª economia mais complexa de acordo com o Índice de Complexidade Econômico (ICE). Em 2015, o Brasil exportou US$ XXXX e importou US$ XXXX, resultando em um saldo comercial (**positivo ou negativo**) de US$ XXXX. Em 2014, o Brasil tinha XXXX empregados formais. O PIB do Brasil em 2010 foi de XXXX e seu PIB per capita foi de XXXX.

**Indicadores Gerais:**
Comércio Internacional: os mesmos de região
Salário e Emprego: os mesmos de região
Educação:  os mesmos de região

Quanto as Visualizações:
As mesmas indicadas na issue #794.

**Comment by lucasdiasas** [comment]
Brazil is the 7th largest world economy and the 56th most complex according to the Economic Complexity Index (ECI). In 2015, Brasil has exported XXXUSD and imported XXXXUSD, resulting in a **positive/negative** commercial rate of XXXUSD. In 2014 Brasil had XXXX formal employees. The Brazilian GDP in 2010 was of XXXX USD and its GDP _per capita_ was of XXXX USD.
