### ISSUE TITLE
Ranking: cor para diferenciar cabeçalho da tabela

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#848]
![image](https://cloud.githubusercontent.com/assets/6808970/14787158/9e0b6f8a-0ad8-11e6-937f-87b7eccbf993.png)

**Comment by diogolundberg** [comment]
Tem um exemplo? No caso é colorir o cabeçalho todo mesmo?

**Comment by eltonfreitas** [comment]
Isso, pode colorir todo o cabeçalho, usa esse verdinho padrão da nova versão.
