### ISSUE TITLE
Ranking: Alinhamento da tabela

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#852]
Números alinhados  a direita.
Textos alinhado a esquerda.
Cabeçalho por centralizado.

![image](https://cloud.githubusercontent.com/assets/6808970/14787549/426454ba-0ada-11e6-8d3c-36f10b96b6ba.png)

**Comment by diogolundberg** [comment]
O título alinhado no meio vai comprometer o ícone da ordenação.
