### ISSUE TITLE
Visualizações do Perfil: Ensino Superior

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#863]
Todos os Exemplos de links consideram Administração como escolha.
**1. Ensino Superior**:

- Matrículas 
 - **Universidades**
    - TreeMap com (http://goo.gl/lJm20e):
     - [x] Tamanho: Matrículas;
     - [x] Agregação: Universidade;
     - [x] Cor: Setor;
     - [x] Ano: Mais recente disponível.
 - **Municípios**
    - Mapa com (http://goo.gl/PFf7hI):
     - [x] Cor: Matrículas;
    - Evolução com (http://goo.gl/661aHL):
     - [x] Eixo Y: Matrículas;
     - [x] Layout: Valor;
     - [x] Ordem: Setor;
    - Treemap com (http://goo.gl/V3qp28):
     - [x] Agregação: Município;
     - [x] Tamanho: Matrículas;
     - [x] Cor: Setor;
 - **Situação dos Estudantes**
    - Linha com (http://goo.gl/RVW6LM):
     - [x] Escala: Linear;
 - **Turno**
    - Evolução com (http://goo.gl/PXHF6D):
     - [x] Ordem: Setor;

**Comment by eltonfreitas** [comment]
Substituir "Matrículas" por "Matrículas por". Para manter o padrão com as demais categorias.
Ajustar Município pro plural: "Municípios"

![image](https://cloud.githubusercontent.com/assets/6808970/14852000/28724aae-0c5a-11e6-810c-baa4345d8d86.png)

**Comment by eltonfreitas** [comment]
Tá em Inglês:
![image](https://cloud.githubusercontent.com/assets/6808970/14870710/733510aa-0cb2-11e6-8eb8-1a6610621a05.png)

**Comment by AnaCarolinaFDias** [comment]
@lauradebella  Você tinha modificado isso e eu cheguei ate a conferir porque ta Inglês de novo?
