### ISSUE TITLE
Substituir Logo da BigData Corp

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#864]
![horpreto](https://cloud.githubusercontent.com/assets/6808970/14817576/8e102eb6-0b8e-11e6-9cc8-78533da3e43e.png)

**Comment by diogolundberg** [comment]
@eltonfreitas, tem como pedir o logo em SVG?

**Comment by diogolundberg** [comment]
Vamos colocar em PNG por enquanto, mas SVG fica melhor a qualidade

**Comment by eltonfreitas** [comment]
@diogolundberg, o @rafamape vai solicitar ao Thoran a logo em formato SVG. Subo aqui quando chegar.

**Comment by diogolundberg** [comment]
O @felipebueno2016 coloca isso em SVG facilmente também.
