### ISSUE TITLE
Ajustar Balança Comercial para que funcione como os outros termos do mesmo nível (ajustar o acordeon)

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#869]
http://develop.dataviva.info/pt/location/4mg
<img width="1239" alt="screen shot 2016-04-26 at 13 50 33" src="https://cloud.githubusercontent.com/assets/6808970/14827218/ae5fe99e-0bb7-11e6-818a-e1bae354aceb.png">

http://develop.dataviva.info/pt/product/052601
<img width="1197" alt="screen shot 2016-04-26 at 13 51 31" src="https://cloud.githubusercontent.com/assets/6808970/14827213/a921ba84-0bb7-11e6-90ea-09e8dc926f26.png">

http://develop.dataviva.info/pt/trade_partner/nausa
<img width="1247" alt="screen shot 2016-04-26 at 14 04 43" src="https://cloud.githubusercontent.com/assets/6808970/14827247/da960d4a-0bb7-11e6-8de4-d0a943b71805.png">

**Comment by AnaCarolinaFDias** [comment]
Elton nesse caso colocamos um subgrupo dentro de Balança Comercial para seguir o padrão dos grupos de baixo, qualquer coisa você me fala que a gente muda.
