### ISSUE TITLE
Alterar a regra de busca das imagens

### ISSUE THREAD

**Issue by diogolundberg** [DataViva/dataviva-site#896]
Cada uma das categorias possui um repositório com as imagens que aparecem em seu cabeçalho.
Exemplo:
Para o continente África de id (af), esta imagem é exibida:
https://dataviva.s3.amazonaws.com/img/trade_partner/trade_partner_af.jpg
a partir da lógica do id **af** ao final do link.

Para os itens mais específicos(no caso do continente, o país), nunca devem ser exibidas as imagens do seu grupo maior.
Exemplo:
Para o país Egito, está sendo exibida a mesma imagem da África
https://dataviva.s3.amazonaws.com/img/trade_partner/trade_partner_af.jpg
como podem ver em 
http://develop.dataviva.info/pt/trade_partner/afegy

Esta regra deve ser mudada, e caso não exista uma imagem específica para o ID do Egito(**afegy**)
https://dataviva.s3.amazonaws.com/img/trade_partner/trade_partner_afegy.jpg

A imagem utilizada deverá ser do id **all**, neste caso:
https://dataviva.s3.amazonaws.com/img/trade_partner/trade_partner_all.jpg

tldr:
Busque a imagem pelo id, sem recorta-lo, caso não exista, exibir a imagem do id **all**

**Comment by AnaCarolinaFDias** [comment]
Segue abaixo o link das imagens para serem usadas como padrão nas categorias na falta de imagens específicas:

LOCALIDADE: https://www.flickr.com/photos/merakoincidencia/4167353829/
PRODUTO: https://www.flickr.com/photos/jeremybrooks/5401494223/
UNIVERSIDADES: https://www.flickr.com/photos/107935765@N04/10720367634/
