### ISSUE TITLE
Visualizações do Perfil: Cursos Básicos

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#897]
Todos os Exemplos de links consideram Ensino Fundamental 6º Ano no Brasil  trocar como escolha.
**1. Curso Básico**:

- Matrículas por
 - **Município**
    - TreeMap com (http://goo.gl/ZmoTKS):
     - [x] Tamanho: Matrículas;
     - [x] Agregação: Município;
     - [x] Cor: Setor;
     - [x] Ano: Mais recente disponível.
    - Mapa com (http://goo.gl/n17WUR):
     - [x] Cor: Matrículas;
    - Evolução com (http://goo.gl/1H3ifc):
     - [x] Eixo Y: Matrículas;
     - [x] Layout: Valor;
     - [x] Ordem: Setor;

**Comment by mpinho** [comment]
Todos os Exemplos de links consideram Ensino Fundamental 6º Ano no Brasil  trocar como escolha.
**1. Curso Básico**:

- Matrículas por
 - **Município**
   - TreeMap com (http://goo.gl/ZmoTKS):
    - [x] Tamanho: Matrículas;
    - [x] Agregação: Município;
    - [x] Cor: Setor;
    - [x] Ano: Mais recente disponível.
    - Mapa com (http://goo.gl/n17WUR):
    - [x] Cor: Matrículas;
    - Evolução com (http://goo.gl/1H3ifc):
    - [x] Eixo Y: Matrículas;
    - [x] Layout: Valor;
    - [x] Ordem: Setor;
 - **Escola**
   - TreeMap com (http://goo.gl/mypWFo):
    - [] Tamanho: Matrículas;
    - [] Agregação: Escola;
    - [] Cor: Setor;
    - [] Ano: Mais recente disponível.

**Comment by mpinho** [comment]
Ajustar conforme especificação acima.
