### ISSUE TITLE
Ocupação com maior número de empregos -  NÃO DECLARADA 

### ISSUE THREAD

**Issue by AnaCarolinaFDias** [DataViva/dataviva-site#924]
Quando entramos no perfil Empreendedores - Qual o número de estabelecimentos na Atividade X, na Localidade Y? - Aba Divisões - Administração Pública - Rio de Janeiro 
A Ocupação com maior número de empregos está como NÃO DECLARADA apesar de ter 96.5 Mil empregos. Isso está correto? 

![image](https://cloud.githubusercontent.com/assets/15165646/14954071/9b284028-1045-11e6-83e3-abba37bf18dd.png)

![image](https://cloud.githubusercontent.com/assets/15165646/14954135/4194cf8a-1046-11e6-99fa-09bbadf771e4.png)

**Comment by AnaCarolinaFDias** [comment]
@eltonfreitas Isso está correto?

**Comment by eltonfreitas** [comment]
Simular a Issue #672, ocultar tudo que for não declaro, não reportado, não especificado, etc
https://github.com/DataViva/dataviva-site/issues/672

**Comment by AnaCarolinaFDias** [comment]
@eltonfreitas  Fecha essa issue por favor, eu abri outra especificando o que fazer.
