### ISSUE TITLE
O ano deve ser especificado para todos Indicadores, é bom lembrar que nem todos vem do mesmo banco

### ISSUE THREAD

**Issue by AnaCarolinaFDias** [DataViva/dataviva-site#925]
Empreendedores – Pergunta-  Quais os produtos mais próximos da estrutura produtiva da localidade  (cidade salvador)

O ano está faltando em todas as localidade. 

**OBS: Ver comentário do Elton abaixo: **
![image](https://cloud.githubusercontent.com/assets/15165646/14954548/975acbe2-1049-11e6-900b-2ae78a95dbd9.png)

![image](https://cloud.githubusercontent.com/assets/15165646/14955484/9f83b048-1050-11e6-8e68-52613b81f2f2.png)

**Comment by eltonfreitas** [comment]
O problema aqui da indicação do ano é que cada banco tem anos diferentes. Exemplo, população é de 2010, do censo, mas ECI é de 2013. Tem que indicar o ano para cada indicador!!!

**Comment by AnaCarolinaFDias** [comment]
@eltonfreitas conversei com o Diogo sobre isso, e de inicío vamos apenar completar com o último ano dos Dados.  Os anos para cada indicador requer uma mudança de Layout e um trabalho maior. Vamos abrir uma issue para isso, modificação de informação e layout ok?

**Comment by eltonfreitas** [comment]
ok

**Comment by AnaCarolinaFDias** [comment]
@eltonfreitas melhor abrir outra, porque vai mudar em todos os perfis e vai mudar Layout.

**Comment by eltonfreitas** [comment]
Então abre outra!!
