### ISSUE TITLE
Informações relevantes -  NÃO DECLARADAS

### ISSUE THREAD

**Issue by AnaCarolinaFDias** [DataViva/dataviva-site#926]
Exemplo : Quando entramos no perfil Empreendedores - Qual o número de estabelecimentos na Atividade X, na Localidade Y? - Aba Divisões - Administração Pública - Rio de Janeiro 
A Ocupação com maior número de empregos está como NÃO DECLARADA. 

Em casos desse tipo devemos pegar a próxima a ocupação com maior número de empregos que foi declarada. 

![image](https://cloud.githubusercontent.com/assets/15165646/14954619/45da7af0-104a-11e6-9170-f9fb5410a556.png)

![image](https://cloud.githubusercontent.com/assets/15165646/14954623/4f758078-104a-11e6-8474-33d3534436ca.png)

**Comment by AnaCarolinaFDias** [comment]
@eltonfreitas

**Comment by eltonfreitas** [comment]
Esse é o mesmo caso da Issue #672. Todas as categorias como Não declarada, não reportada, não classificada, etc, em geral começadas por X ou 9 (tem que checar isso no banco) devem ser ocultas. Nesse exemplo levantado pela @AnaCarolinaFDias o DV tem que mostrar qual a ocupação com mais empregos que não seja "Não Declarada". Isso tem que ser em todos os cantos do site!!

**Comment by AnaCarolinaFDias** [comment]
@eltonfreitas  Tem algum lugar que explica que esses números são os maiores baseados em informações declaradas?
