### ISSUE TITLE
Tela Preta - Perfil Empreendedores 

### ISSUE THREAD

**Issue by AnaCarolinaFDias** [DataViva/dataviva-site#928]
Entrando no perfil Empreendedores - Pergunta: Qual o salário médio da Ocupação Z, na Atividade X, na Localidade Y?

- Escolho a ocupação Lixeiros
- Escolho a Atividade Econômica: Construção de Edifícios
 
A tela fica preta e não me permite escolher a Localidade. 
![image](https://cloud.githubusercontent.com/assets/15165646/14955201/b0221482-104e-11e6-86dd-5cc0e6f93f2b.png)

**Comment by AnaCarolinaFDias** [comment]
Relacionada com #907

**Comment by eltonfreitas** [comment]
A minha gerou, não deu essa tela preta!! No entanto o resultado mostrado redirecionou pra uma página em Inglês!!
![image](https://cloud.githubusercontent.com/assets/6808970/14957387/8519154e-105b-11e6-9598-ac6da000408b.png)

http://develop.dataviva.info/en/occupation/5142?cnae_id=f41204%3Fbra_id=4sp090607

**Comment by AnaCarolinaFDias** [comment]
@eltonfreitas  Nesse caso você só cruzou a ocupação com a Localidade, e a Atividade? 
Você foi pela pergunta que eu especifiquei?
