### ISSUE TITLE
Texto Duplicado - Mesorregiões 

### ISSUE THREAD

**Issue by AnaCarolinaFDias** [DataViva/dataviva-site#930]
No perfil Localidades, na aba Perfil Geral - O texto especificando a Mesorregião encontra-se duplicado. 

![image](https://cloud.githubusercontent.com/assets/15165646/14955624/9b8c9882-1051-11e6-89e3-57c651d197dd.png)

**Comment by AnaCarolinaFDias** [comment]
@eltonfreitas é somente um texto mesmo?

**Comment by eltonfreitas** [comment]
Pelo que vi isso só aparece nos perfis de Mesorregião!
