### ISSUE TITLE
Texto incorreto 

### ISSUE THREAD

**Issue by AnaCarolinaFDias** [DataViva/dataviva-site#931]
No perfil Empreendedores - Pergunta: Quais os principais parceiros comerciais de um Produto P na Localidade Y? 

Produto: Aviões 
Localidade: Município Brasília - DF 

O texto representando Informação de None em cinco anos está incorreto. Provavelmente Esse None deveria ser um valor. 

![image](https://cloud.githubusercontent.com/assets/15165646/14955852/19bab0d0-1053-11e6-895b-c6a5feee0476.png)

**Comment by AnaCarolinaFDias** [comment]
@eltonfreitas O que fazer nesse caso?

**Comment by eltonfreitas** [comment]
Esse é um caso de dados nulos!! O correto é retirar esse trecho do texto quando não tiver dados.
