### ISSUE TITLE
Informações Cruzadas - Internal Server Erro 

### ISSUE THREAD

**Issue by AnaCarolinaFDias** [DataViva/dataviva-site#932]
No perfil Empreendedores, pergunta : Quais os principais parceiros comerciais de um Produto P na Localidade Y? 

Produto: Aviões 
Localidade : Municipio - Salvador - BA

![image](https://cloud.githubusercontent.com/assets/15165646/14956027/ff35337e-1053-11e6-9e6e-f72d78dbc3cc.png)

**Comment by AnaCarolinaFDias** [comment]
Relacionada #907

**Comment by eltonfreitas** [comment]
Falta uma tela de erro, o @diogolundberg já está preparando junto com a designer esta tela!!
