### ISSUE TITLE
Perfil Empreendedores - Pergunta retorna um resultado diferente

### ISSUE THREAD

**Issue by AnaCarolinaFDias** [DataViva/dataviva-site#933]
No perfil Empreendedores - Pergunta: Quais os cursos de nível superior oferecidos na Localidade Y? 
Escolho uma localidade qualquer :
Exemplo Belo Horizonte. 

Ele me retorna as informações da Localidade de Belo Horizonte. 

Nesse caso não deveria ter um cruzamento Mostrando uma lista dos cursos de Nível Superior em BH? Onde está essa informação?

OBS:  O mesmo vale para a pergunta: Quais os cursos de nível técnico oferecidos na Localidade Y?

![image](https://cloud.githubusercontent.com/assets/15165646/14956565/d76a7914-1056-11e6-8698-0c59a6660a86.png)

**Comment by AnaCarolinaFDias** [comment]
@eltonfreitas

**Comment by eltonfreitas** [comment]
Essa é uma solução que ainda não foi aplicada na nova versão do DataViva 3. O perfil está correto, mas não está direcionando para a visualização correta dentro do perfil, isso acontece no DV 2. Exemplo: http://pt.dataviva.info/profiles/bra/4mg030000/?app=32

Esse link por exemplo indica dentro do Perfil de BH qual a visualização responde a pergunta.
Isso ainda não está acontecendo no DV3, o usuárii teria que ir em Educação e lá clicar para ver os cursos.
