### ISSUE TITLE
Perfil AGENTES DE DESENVOLVIMENTO - Resultado da Pergunta 

### ISSUE THREAD

**Issue by AnaCarolinaFDias** [DataViva/dataviva-site#934]
Perfil AGENTES DE DESENVOLVIMENTO
Qual a rede de produtos da Localidade Y? 
Localidade: Estado de Minas Gerais. 

O que eu esperava ver é uma página contendo as redes de produtos. 
Só que essa pergunta me retorna a página Geral do Perfil Localidade Minas Gerais. 

Não deveria abrir direto na aba Oportunidades Econômicas com o gráfico de rede de produtos? Se eu clicasse nessa pergunta era isso que eu esperaria ver. Eu sei que fica em Oportunidades Econômicas porque visitei o site muitas vezes.  

O que ele retorna: 
![image](https://cloud.githubusercontent.com/assets/15165646/14956865/4f953c48-1058-11e6-9ba6-a177dacd9431.png)

O que eu acho que deveria retornar: 
![image](https://cloud.githubusercontent.com/assets/15165646/14956895/85f4c1aa-1058-11e6-9962-cded5d7bf769.png)

**Comment by AnaCarolinaFDias** [comment]
@eltonfreitas

**Comment by eltonfreitas** [comment]
MEsmo caso da Issue #933.
