### ISSUE TITLE
(URGENTE) Perfil do Reino Unido mostrando foto da Torre Eiffel

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#943]
![image](https://cloud.githubusercontent.com/assets/6808970/14965831/d9d97482-1085-11e6-856b-73a389964ad5.png)

![image](https://cloud.githubusercontent.com/assets/6808970/14965874/1d5bc480-1086-11e6-847e-372330108213.png)

Queremos arrumar uma guerra mundial?

**Comment by AnaCarolinaFDias** [comment]
#929
