### ISSUE TITLE
Apagar Visualizações por Municípios no Perfil de Atividades Econômicas

### ISSUE THREAD

**Issue by mpinho** [DataViva/dataviva-site#959]
Quando a localidade selecionada for um município, o site não deve apresentar nenhuma das visualizações por municípios.

Exemplos de visualizações que devem ser retiradas:

![image](https://cloud.githubusercontent.com/assets/15732270/14982850/d324a1fe-110f-11e6-9a86-33df6cb2f9ed.png)

![image](https://cloud.githubusercontent.com/assets/15732270/14982897/34c1d58a-1110-11e6-9ef0-0eb6c4183162.png)

![image](https://cloud.githubusercontent.com/assets/15732270/14982922/5ef1a402-1110-11e6-8523-b2cb3987db96.png)

**Comment by AnaCarolinaFDias** [comment]
@mpinho Limpa o Cache do Navegador e verifica de novo por favor . 
![image](https://cloud.githubusercontent.com/assets/15165646/14983429/b421f4d8-1113-11e6-8858-b0481b700732.png)

**Comment by AnaCarolinaFDias** [comment]
Nos cruzamentos , entre Algum perfil e Localidade Municipio os graficos de Municipio ainda aparecem, corrijam isso por favor.

**Comment by eltonfreitas** [comment]
Ainda mostrando Municípios aqui!! Esse gráfico, conforme a issue #879 não deve ser exibido para municípios
http://develop.dataviva.info/pt/basic_course/xx007?bra_id=4sp090607
![image](https://cloud.githubusercontent.com/assets/6808970/14992058/9ae13804-113a-11e6-967e-87a24d1114c6.png)
