### ISSUE TITLE
Perfil Parceiros Comerciais: Corrigir títulos das visualizações de Importação e Exportação.

### ISSUE THREAD

**Issue by mpinho** [DataViva/dataviva-site#962]
No perfil de Parceiros Comerciais, deve-se corrigir os títulos das visualizações de Exportações por Município, Importações por Produto e por Município. Alguns exemplos a seguir.

Importações da China para o Brasil:
![image](https://cloud.githubusercontent.com/assets/15732270/14983839/f3482234-1115-11e6-9cda-cf9f47f58dc1.png)

Importações da China para o Brasil:
![image](https://cloud.githubusercontent.com/assets/15732270/14983895/46e9d9c8-1116-11e6-9fe3-0e1b16e6faa5.png)

Municípios no Brasil que importam da China:
![image](https://cloud.githubusercontent.com/assets/15732270/14983852/05ab2d90-1116-11e6-90ba-55455625f44f.png)

Municípios no Brasil que importam da China:
![image](https://cloud.githubusercontent.com/assets/15732270/14983958/9aa289de-1116-11e6-8e75-c7d86f2bf4f5.png)

Municípios no Brasil que exportam para a China.
![image](https://cloud.githubusercontent.com/assets/15732270/14984174/be6bc6b8-1117-11e6-93ff-864d982dac83.png)

**Comment by eltonfreitas** [comment]
Acho que precisamos fazer uma revisão geral dos títulos dos gráficos, essas mudanças não ficaram boas.
![image](https://cloud.githubusercontent.com/assets/6808970/19476544/7ffa6fe4-9518-11e6-9ce1-fcd9ab391c85.png)

Vou fechar essa Issue e abrir uma nova com revisão geral de títulos dos gráficos.
