### ISSUE TITLE
Central de Ajuda - Primeiros Passos

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#969]
Incluir as perguntas e respostas para essa sessão formuladas pelo Lucas. 
Um detalhe, nessa sessão não existe a pergunta: O que é o DataViva?

[Primeiros Passos CA_ajustes.docx](https://github.com/DataViva/dataviva-site/files/247073/Primeiros.Passos.CA_ajustes.docx)
[First Steps CA.docx](https://github.com/DataViva/dataviva-site/files/247072/First.Steps.CA.docx)

![image](https://cloud.githubusercontent.com/assets/6808970/14986384/0899787a-1122-11e6-9f89-0ebfdeda0277.png)

**Comment by AnaCarolinaFDias** [comment]
@eltonfreitas a pergunta O que é o DataViva? vai ser excluida, ou vai ser deslocada para outro lugar?

**Comment by eltonfreitas** [comment]
Vai ser excluída!! Já existe o Sobre!!
