### ISSUE TITLE
Central de Ajuda - Dúvidas frequentes

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#971]
Replicar perguntas do DV2 - Essas perguntas devem completar a ABA Dúvidas Frequentes . 

Em português:
http://pt.dataviva.info/about/contact/

Em inglês:
http://en.dataviva.info/about/contact/

**Comment by AnaCarolinaFDias** [comment]
Replicar perguntas, você diz por colocar todas essas Perguntas do Fale conosco? @eltonfreitas
