### ISSUE TITLE
Central de Ajuda - Glossário

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#973]
Disponibilizar link para artigos de referência além do que já está disponibilizado:
http://science.sciencemag.org/content/317/5837/482
http://link.springer.com/article/10.1007/s10887-006-9009-4
http://papers.ssrn.com/sol3/papers.cfm?abstract_id=939646
http://www.pnas.org/content/106/26/10570.short

**Comment by AnaCarolinaFDias** [comment]
@eltonfreitas Podemos criar mais um Título em Glossário com o nome de Artigos de referência ou Outros Artigos de Referencia? Você tem alguma sugestão? 
Desse jeito que eu falei não mudaria nada no Layout e ficaria padronizado,

**Comment by VictorDMor** [comment]
A sugestão da Carol é boa. Assim, só criariamos um texto com o título do link seguido do mesmo e fariamos apenas uma adição ao Banco de Dados.
