### ISSUE TITLE
Ajuda - Fontes de Dados

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#974]
Além do que já nessa área, disponibilizar também o link para as fontes de dados:

RAIS: ftp://ftp.mtps.gov.br/pdet/microdados
SECEX: http://www.mdic.gov.br//sitio/interna/interna.php?area=5&menu=5319
Censo Escolar: http://portal.inep.gov.br/basica-levantamentos-acessar
Censo da Educação Superior: http://portal.inep.gov.br/basica-levantamentos-acessar
Comtrade: http://comtrade.un.org/db/default.aspx

**Comment by VictorDMor** [comment]
Creio que poderá ser o mesmo esquema da #973, certo?

**Comment by AnaCarolinaFDias** [comment]
@VictorDMor  Nesse caso acho melhor colocar o Link para as fontes de dados na aba relacionada ao Dado. E não criar uma nova.
