### ISSUE TITLE
Ajuda - Tipos de Gráficos

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#975]
“Embedar” link para o gráfico abaixo da explicação de cada Gráfico.
Podem usar MG como padrão para a maioria dos casos.

**Comment by AnaCarolinaFDias** [comment]
Exemplo do DV2: 
![image](https://cloud.githubusercontent.com/assets/15165646/15018232/1c8c794a-11ef-11e6-8122-43a05f9e3cd6.png)
