### ISSUE TITLE
Ajuda - Classificações

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#977]
Disponibilizar tabela de classificações para download, ver o DV2:

http://pt.dataviva.info/about/classification/bra/3/

**Comment by AnaCarolinaFDias** [comment]
@eltonfreitas No caso esse Ajuda -  Classificações também vai ser uma tabela como no DV2?

**Comment by rafamape** [comment]
@FredericoVieira @eltonfreitas Lembrarmos de inserir esta issue na próxima sprint. Praticamente todos os usuários interessados no download de dados precisam das tabelas de classificação e acabam entrando em contato para enviarmos por e-mail.
