### ISSUE TITLE
Tela de Erro 500

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#992]
![image](https://cloud.githubusercontent.com/assets/6808970/14998562/e1ec3ea4-115a-11e6-9e6b-b067db72028a.png)
http://develop.dataviva.info/pt/product/052601?bra_id=2ba030106

Minha escolha foi: Minério em Salvador.

Como esse é um tipo de erro relacionado a falta de dados ou informação par as opções escolhidas, a melhor mensagem não seria indicar que para aquela opção de escolhas não existe informação? Essa forma dá ideia de que o problema é na plataforma e não inexistência de dados, o usuário pode ficar esperando o problema ser resolvido.

**Comment by eltonfreitas** [comment]
Além disso, as opções relacionadas não são muito boas! O que minério teria haver com ocupações, atividades e cursos? Ou a escolha de Salvador teria com Minas Gerais?

**Comment by AnaCarolinaFDias** [comment]
#932
