### ISSUE TITLE
EUA é o principal parceiro comercial do Brasil?

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#994]
http://develop.dataviva.info/pt/trade_partner/nausa
![image](https://cloud.githubusercontent.com/assets/6808970/14999885/742153ca-1162-11e6-897b-9fb93ea5baf9.png)
Entrei para ver os parceiros comerciais do Brasil. Na foto acima dá a entender que os EUA é o principal parceiro comercial (pelo menos em exportações, pois é a informação que está do lado da bandeira de cada país, e a ordem está decrescente).
![image](https://cloud.githubusercontent.com/assets/6808970/14999935/a4ba9b22-1162-11e6-90ec-63887667ca25.png)
Ao clicar nos EUA, aparece a foto acima, dizendo que os EUA é o quarto em importação e o quinto em exportações. Ficou confuso pra mim.

**Comment by AnaCarolinaFDias** [comment]
#907
