### ISSUE TITLE
Espaço de Produtos do Brasil não está sendo exibido!!

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#997]
http://develop.dataviva.info/pt/location/all#
![image](https://cloud.githubusercontent.com/assets/6808970/15012571/185e83dc-11d0-11e6-8f91-b36df4b00572.png)

Ver no DV2:
http://pt.dataviva.info/ESNRJW/

**Comment by AnaCarolinaFDias** [comment]
Dados atualizados. Agora o Mapa está aparecendo. 

![image](https://cloud.githubusercontent.com/assets/15165646/15016750/0c77abb6-11e9-11e6-90c4-ea0ce9f272a6.png)
